heartbeat/vsftpd
=> Created new RA for vsftpd

heartbeat/iSCSILogicalUnit
This works fine in my development enviroment.
=> #526, do not set write_back when creating backstore/block

ldirectord/ldirectord.in
Connecttimeout already abolished.
=> low: ldirectord: Modify manual for negotiatetimeout

tools/ocft/caselib.in, tools/ocft/ocft.in
ocf_rarun depends on the correct setting of OCF_RESOURCE_TYPE.
Which perhaps needs to change to something more robust, but let's
play straigth for now.
=> Dev: ocft: don't fiddle with OCF_RESOURCE_TYPE

heartbeat/CTDB
As per the discussion on #566, here is a pull request without the changes to the logging mechanism.
=> Minor updates to CTDB resource agent - resubmit

rgmanager/src/resources/orainstance.sh
This small patch add a list of messages to ignore.
Some ORA message are more informative than actually a real error.
=> Handle ORA-* messages

heartbeat/VirtualDomain
The following 2 points were corrected.
* Fixed to correctly get the return code of the "virsh destroy" command
* Force the "virsh destroy" of output in C
=> Fix virtual domain

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/rabbitmq-cluster
We are planning to support this agent in rhel7.
use case scenario
https://github.com/davidvossel/phd/blob/master/scenarios/rabbitmq-cluster.scenario
=> High: introducing rabbitmq clustering agent

heartbeat/dnsupdate, heartbeat/ora-common.sh, heartbeat/oracle, heartbeat/sg_persist
dnsupdate and sg_persist fixed to use the advertised parameters.
=> various meta-data issues reported by lars

rgmanager/src/resources/utils/fs-lib.sh
=> Low: fs-lib.sh: fix misleading comment extravaganza

heartbeat/galera
- clear last know sequence number any time promote is even attempted
- don't detect active master instances during demote action.
=> Minor galera fixes

heartbeat/docker
fix some potential test failure on docker images lookup,
please see commits for detail,
thanks
=> Fix docker images lookup

rgmanager/src/resources/ip.sh
Update to use DAD to check for IPv6 address collision, which is quicker than using ping to verify to check that the address isnt in use on the network.
=> Use DAD to check for IPv6 address collision

heartbeat/SAPDatabase
This agent has been tested to work with Oracle database version 12.
=> SAPDatabase: Add Oracle 12 to list of supported databases (bsc#953991)

ldirectord/ldirectord.in
- support for custom dns ports
- dns check results are now regex ready
- fallback cmd arguments added
=> ldirectord.in: dns_check and fallbackcommand enhancements

heartbeat/Makefile.am, heartbeat/nagios
Cleaned up version of: https://github.com/ClusterLabs/resource-agents/pull/636
Any suggestions for improvements are welcome.
=> Nagios Resource Agent

heartbeat/nagios
meta-data generated errors in the log file as it is not run as root.
This patch fixes that issue.
=> Move ocf_is_root to solve issue with meta-data

heartbeat/Raid1, heartbeat/iscsi, heartbeat/ora-common.sh, heartbeat/oracle, heartbeat/oralsnr, heartbeat/pgsql, heartbeat/pingd
Five RAs updated with ocf_exit_reason support.
=> Ocf exit reason

heartbeat/pgsql
=> Low: pgsql : fix invalid log message

rgmanager/src/resources/mysql.sh
If mysqld is slow to start the first status() check would fail. This update causes it to wait up to startup_wait seconds before failing if mysqld is started but hasnt gotten to create a PID-file yet.
=> mysql.sh: wait up to startup_wait seconds before failing if mysqld startup is slow

resource-agents.spec.in, tools/ocft/Filesystem, tools/ocft/LVM, tools/ocft/Makefile.am, tools/ocft/Raid1, tools/ocft/Xinetd, tools/ocft/apache, tools/ocft/caselib.in, tools/ocft/exportfs, tools/ocft/exportfs-multidir, tools/ocft/helpers.sh, tools/ocft/iscsi, tools/ocft/mysql, tools/ocft/named, tools/ocft/nfsserver, tools/ocft/ocft.in, tools/ocft/pgsql, tools/ocft/runocft, tools/ocft/runocft.prereq
Improve some ocft test suites.
Fix some ocft issues.
Add runocft to run a set of test suites.
=> Ocft update

heartbeat/nfsserver
=> Medium: nfsserver: fix monitor for systemd

heartbeat/iSCSITarget
Added ability specify IP of a portal which will have iSCSI Extensions for RDMA (iSER) feature enabled
=> Added iSER enabled portal support

heartbeat/SAPInstance
Update stated SAP WebAS version support.
Also adds a clarification as to what the support statement means.
=> Low: SAPInstance: Update version support statement

heartbeat/apache
make sure target file existence and readable, but not just the string test
=> Low: apache: ensure readable $TESTCONFFILE

heartbeat/pgagent
=> Added pgagent RA

heartbeat/awsvip
sample config:
primitive res_awsvip ocf:heartbeat:awsvip \
params awscli="/usr/local/bin/aws" \
params secondary_private_ip="172.31.0.123"
Signed-off-by: guessi <guessi@gmail.com>
=> managing "Secondary Private IP" for EC2 instances

heartbeat/awseip
sample config:
primitive res_awseip ocf:heartbeat:awseip \
params awscli="/usr/local/bin/aws" \
params elastic_ip="52.9.0.123"
Signed-off-by: guessi <guessi@gmail.com>
=> managing "Elastic IP" for EC2 instances

heartbeat/rabbitmq-cluster
pull request for: https://github.com/davidvossel/resource-agents/commit/f82b1f794df8af69371572dcd83e76792953ada9
=> High: rabbitmq-cluster: forget stopped rmq nodes with notify=true

heartbeat/SAPDatabase, heartbeat/sapdb.sh
Reverts these submit requests: #802, #803, #806, #811 
I have learned that I handled these incorrectly and should have checked with the SAP Linux Lab before merging them.
I will let @AlexanderKrauth decide how to proceed with these changes suggested by @ionutgogu .
=> High: SAPDatabase: Revert previous changes

heartbeat/garbd
This pull request provides a resource agent for garbd, the Galera arbitrator.
It allows managing 2-nodes Galera clusters with an additional arbitrator for quorum.
=> garbd: Introduces garbd resource-agent

heartbeat/nfsserver
This fix following 2 problems on monitor.
1. It is failed delete temp files and the files remain and increase on /tmp every monitoring.
2. The log message "Status: xxx" is output every monitoring. (the status is to /dev/null).
=> nfsserver: improve nfsserver monitor

ci/build.sh, doc/man/mkappendix.sh, doc/man/ralist.sh
This updates the Travis CI configuration to run configure + make as well, to verify that scripts written in C still compile. Also ignore warnings we don't care about and distinguish between warnings and errors.
=> Dev: Updated Travis CI configuration

heartbeat/Makefile.am
RA missing: awseip, awsvip, pgagent, vsftpd
=> Dev: Clean up Makefile.am and add awseip, awsvip, pgagent and vsftpd to agent list

rgmanager/src/resources/lvm_by_lv.sh
Without this patch it'll check against all the logical volumes.
=> lvm.sh: fix status clustered to check the specified logical volume

ci/build.sh, heartbeat/ClusterMon, heartbeat/Dummy, heartbeat/SysInfo, heartbeat/ethmonitor, heartbeat/garbd, heartbeat/mysql-proxy
* Fixes to `mysql-proxy` and `garbd` are clearly broken code.
* Remove non-ASCII characters which prevent Shellcheck from analyzing the sources.
* Improved CI script which only reports an overall failure if there are failures reported by Shellcheck.
=> Dev: Updated CI configuration and fixed issues found by Shellcheck

heartbeat/CTDB, heartbeat/Filesystem, heartbeat/MailTo, heartbeat/ManageRAID, heartbeat/ServeRAID, heartbeat/SysInfo, heartbeat/apache-conf.sh, heartbeat/conntrackd, heartbeat/db2, heartbeat/eDir88, heartbeat/findif.sh, heartbeat/nginx, heartbeat/postfix, heartbeat/rabbitmq-cluster, heartbeat/redis, heartbeat/tomcat
Series of commits that clean up and fix issues reported by Shellcheck.
With these changes, the `ci/build.sh` succeeds with the current configuration (ignoring info and warning level notifications, and ignoring errors that are less relevant to resource-agents).
=> Medium: Fix issues discovered by Shellcheck

rgmanager/src/resources/bind-mount.sh, rgmanager/src/resources/clusterfs.sh, rgmanager/src/resources/fs.sh.in, rgmanager/src/resources/netfs.sh, rgmanager/src/resources/utils/fs-lib.sh
For those cases where you want to disable the write check.
=> fs.sh: add parameter to be able to disable write check

rgmanager/src/resources/bind-mount.sh, rgmanager/src/resources/clusterfs.sh, rgmanager/src/resources/fs.sh.in, rgmanager/src/resources/netfs.sh, rgmanager/src/resources/utils/fs-lib.sh
Reverts ClusterLabs/resource-agents#889
=> Revert "fs.sh: add parameter to be able to disable write check"

heartbeat/portblock
E.g. when running multiple portblock resources.
=> portblock: Use -w (wait) to avoid "insufficient privileges" error

resource-agents.spec.in
Most of these are required by heartbeat agents as well.
=> specfile: make requirements general and update comments

heartbeat/exportfs
Reverts ClusterLabs/resource-agents#906
=> Revert "exportfs: fix monitor function for IPv6 addresses"

heartbeat/IPaddr2
=> Fix typo in IPaddr2

doc/dev-guides/ra-dev-guide.asc
Correct description taken from:
http://clusterlabs.org/doc/en-US/Pacemaker/1.1/html/Pacemaker_Explained/s-ocf-return-codes.html
Fixes: #944
=> Doc: Fix description of OCF_ERR_ARGS

heartbeat/iSCSILogicalUnit
Avoids unchecked openssl dependency in this agent.
=> iSCSILogicalUnit: replace openssl call with md5sum

heartbeat/docker
Fix the following issue.
Now image_exists() can not parse the image names which has port number.
For exsample "xxx.xxx.xxx.xxx:YYYY/IMAGE:latest".
=> Midumu: docker: fix to deal with the image name correctly.

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/NodeUtilization
Adds agent which sets node utilization attributes using crm_attribute.
=> Medium: NodeUtilization: Add NodeUtilization agent

heartbeat/nginx
try to restart resource on different node if nginx configtest fails
=> fix nginx resource

heartbeat/redis
Fixes two problems found while testing the agent with redis-server 3.2.
=> redis: fixes for compatibility with redis 3.2

heartbeat/rabbitmq-cluster
- Backup and restore policies.
- Simplify code (simplify?)
=> [RFE] Backup and restore policies

heartbeat/ocf-shellfuncs.in
Reverts ClusterLabs/resource-agents#975
=> Revert "Make ocf_is_ver() handle dist. specific versions"

heartbeat/Makefile.am, heartbeat/ZFS
Adds a resource agent to import/export ZFS pools.
This resource agent has a long history of use and is well tested.
=> Add ZFS Resource Agent

heartbeat/awseip, heartbeat/awsvip
--public-ip doesnt work (tested with latest awscli from pip as well), so it had to be changed to --allocation-id and --association-id.
=> awseip/awsvip: fixes and improvements

heartbeat/Makefile.am, heartbeat/minio
Minio is a distributed object storage server
built for cloud applications and devops.
URL: https://www.minio.io/
Fixes: #1012
=> High: minio: Resource agent for the minio storage server

heartbeat/SAPInstance
Clarify MONITOR_SERVICES documentation to reduce confusion about
support for SAP Webdispatcher.
=> Low: SAPInstance: Mention monitor support in documentation (bsc#1051913)

heartbeat/varnish
Some of the parameters are no longer exist in the version 4.0 of varnish. This file is compatible with the latest version.
=> Update for version 4.0 of varnish

heartbeat/Makefile.am, heartbeat/rkt
Based on a similar docker resource agent.
=> rkt: new resource agent for managing containers

heartbeat/ovsmonitor
This resource agent is used to monitor an OVS bond:
* link state
* packets received
Some attributes are updated to use the bond status within constraints.
=> Openvswitch resource

heartbeat/Makefile.am, heartbeat/aws-vpc-move-ip
aws-vpc-move-ip from https://github.com/mguertler/AWS-VPC-move-IP with cleanup and improvements.
=> aws-vpc-move-ip

heartbeat/nfsserver
=> nfsserver: allow stop to timeout

heartbeat/LVM, heartbeat/Makefile.am, heartbeat/lvm-clvm.sh, heartbeat/lvm-plain.sh, heartbeat/lvm-tag.sh
Refactor LVM in order to reduce complexity.
clvm and tag specific stuff is moved into its own files which are
sourced depending on the resource configuration.
=> Dev: LVM: put VG protection mechanisms into separate files

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/ipsec
This adds a simple resource agent that handles ipsec tunnels.
It will associate a given tunnel witha specific VIP, and will put it up
or down depending on the VIP being there or not. This is meant to have a
collocation rule with an IP resource.
=> Add resource agent for IPSEC tunnels

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/jira
This is a new ocf ra for managing JIRA software.
=> High: jira: new resource agent

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/mpathpersist
It is a new RA hanlding persist reservation for multipath
devices. It uses mpathpersist which from package multipath-tools
as backend.
fate#324044
=> New RA for mpathpersist

heartbeat/Filesystem
Fixes https://github.com/ClusterLabs/resource-agents/issues/1100
=> Add support for cvfs

heartbeat/pgsql
* Fix incorrect judgment when include line is commented out in postgresql.conf
* Detects incorrect setting of synchronous_standby_names
=> Low: pgsql: improve validations for replication mode

configure.ac
Based on how it's done in Pacemaker.
=> build: manpage generation without internet

heartbeat/aliyun-vpc-move-ip
Add Alibaba Cloud vpc-move-ip agent.
=> Add Aliyun vpc-move-ip agent.

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/aliyun-vpc-move-ip
...also added the agent to the Makefiles.
=> aliyun-vpc-move-ip: fixes

heartbeat/awseip
Add missing permission: DescribeAddresses
Fix typo
=> awseip: Documentation updates to prerequisites

heartbeat/SAPDatabase
This PR adds additional info to the SAPDatabase resource agent.
Related Report: https://bugzilla.suse.com/show_bug.cgi?id=1089874
=> Add additional info to SAPDatabase RA

heartbeat/iSCSITarget.in
add an if-condition and remove an useless 'targetcli create'
=> possible fix for #1026

.gitignore, configure.ac, doc/man/Makefile.am, heartbeat/Makefile.am, m4/ac_python_module.m4
...and skip agents if library or Python binary is missing.
=> configure: add Python library detection

heartbeat/LVM-activate
=> LVM-activate: fix indentation

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/dovecot
Based on the postfix resource agent.
We're using it at $DAYJOB for about a year now.
=> Add resource agent for dovecot.

heartbeat/azure-events.in
Fix implicit bytes conversion that breaks py3 compatibility and reduces the amount of errors messages using default value on crm_attribute call.
=> azure-events: Fix implicit bytes conversion that breaks py3 and reduces errors on syslog.

heartbeat/podman
This is a three patch series to improve the podman RA. I tested them as per commit-messages description
=> Podman fixes 

heartbeat/Filesystem
The action was removed in https://github.com/ClusterLabs/resource-agents/commit/a753a0fdf
=> Filesystem: remove removed notify-action from metadata

heartbeat/apache-conf.sh
take resource ID as a pattern for PIDFile
=> [apache-RA]: Improve PidFile pattern

heartbeat/ocf.py
=> Fix path to example for ocf python agent

heartbeat/apache
Load apache status modules from RA cmdline for SUSE only OS
=> Load apache status modules from RA cmdline for SUSE only OS

resource-agents.spec.in
https://github.com/ClusterLabs/resource-agents/pull/1385 after fixes (unable to reopen the PR).
=> CI: "make rpm" fixes

heartbeat/apache, resource-agents.spec.in
Apache resource agent is not working when statusurl was set.
The reason was bad detecting the OS and bad start code.
=> Fix apache rs on suse

heartbeat/pgsql
These patches are aim to support PostgreSQL 12.
Please see also the following issue for a discussion of PostgreSQL12 support.
https://github.com/ClusterLabs/resource-agents/issues/1424
=> High: pgsql: Support for PostgreSQL 12

heartbeat/lvmlockd
Signed-off-by: Zhao Heming <heming.zhao@suse.com>
=> [lvmlockd] support lvm2-2.03 which removes lvmetad

heartbeat/ocf-shellfuncs.in
https://github.com/ClusterLabs/resource-agents/pull/1469
=> ocf-shellfuncs: ocf_is_clone: update comment based on clone-max fix in previous commit

heartbeat/dummypy.in
Mimicking the behaviour of the shell Dummy RA, a dummy RA wirtten in Python is provided as example.
=> Dummy RA in Python

heartbeat/exportfs
based on implementation in Filesystem agent
=> exportfs: add symlink support

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/docker-compose
This new resource agent adds functionality to manage docker services using docker-compose as an OCF resource in an High Availability setup.
It relies on a well-tested docker compose YAML file which distributed on an identical location on all cluster nodes.
=> High: docker-compose: new resource agent

heartbeat/gcp-pd-move.in
- Fixed Python 3 encoding issue
- Improved metadata
- Change monitor loglevel to debug
- Removed "regional" functionality that doesnt work with attachDisk()
- Updated rw/ro to READ_WRITE/READ_ONLY in metadata/default value
=> gcp-pd-move: fixes and improvements

heartbeat/aws-vpc-move-ip
Allow users to specify region as an instance attribute.
Resolves: RHBZ#1872999
=> aws-vpc-move-ip: Add --region attribute

doc/man/ra2refentry.xsl
https://github.com/ClusterLabs/pcs/issues/214
=> man: use promotable keyword in manpage examples

heartbeat/asterisk
Fix for issue #1582 
If directories are as expected by the RA, no action is done.
If they are not writable, they will be created with proper credentials.
=> Asterisk dir fix

resource-agents.pc.in
=> [build] export ocfrootdir consistently

ldirectord/ldirectord.in
I got the need of set thresholds for real server on a heavy loaded system installation.
Patch runned fine in production for several monts, i'm posting it in case migth turn useful to someone else.
=> added real servers threshold settings to ldirectord

heartbeat/VirtualDomain
see https://github.com/ClusterLabs/resource-agents/issues/1613 #1613
=> VirtualDomain: fix pid_status() on EL8

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/smb-share.in
https://github.com/ClusterLabs/resource-agents/pull/1628
=> build: add smb-share and fix & not passing XML check/manpage generation

configure.ac, heartbeat/openstack-info, heartbeat/openstack-info.in
- Updates due to API output format changes.
- Attempt to future-proof parsing of the output.
=> openstack-info: CLI output parsing and storage fixes.

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/openstack-virtual-ip
- New resource agent for virtual IP support in OpenStack.
=> openstack-virtual-ip: New resource agent for virtual IP support in OpenStack.

heartbeat/SAPInstance
SAPInstance: for systemd integrated sapstartsrv instances use systemd to check/start the service
=> SAPInstance: add systemd compatability

heartbeat/mdraid
Signed-off-by: Heming Zhao <heming.zhao@suse.com>
=> mdraid: add option description for OCF_CHECK_LEVEL

heartbeat/lvmlockd
https://bugzilla.redhat.com/show_bug.cgi?id=1691095
=> lvmlockd: remove cmirrord support as it's incompatible with lvmlockd

resource-agents.spec.in
=> [rpm] fix Requires to allow install on opensuse

heartbeat/podman
Fixes https://github.com/ClusterLabs/resource-agents/issues/1720.
=> podman: remove anonymous volumes

heartbeat/openstack-cinder-volume, heartbeat/openstack-floating-ip, heartbeat/openstack-info.in, heartbeat/openstack-virtual-ip
=> openstack-*: allow agents to perform insecure connections to openstackcli

heartbeat/openstack-info.in
=> openstack-info: align op timeout with other openstack agents

configure.ac
=> build: workaround gcc 12 warning

heartbeat/LVM-activate
issue #704  
LVM-activate RA update ocf_exit_reason support
=> LVM-activate: replace error log messages with calls to ocf_exit_reason

.gitignore, doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/openstack-cinder-volume, heartbeat/openstack-common.sh, heartbeat/openstack-floating-ip, heartbeat/openstack-info.in, heartbeat/openstack-virtual-ip
- clouds.yaml
- parameters (based on fence_openstack naming)
=> openstack-*: add support for multiple setup options

heartbeat/openstack-cinder-volume, heartbeat/openstack-floating-ip, heartbeat/openstack-info.in, heartbeat/openstack-virtual-ip
=> openstack agents: align timeout also for monitoring operation

heartbeat/LinuxSCSI
issue #704
LinuxSCSI RA update ocf_exit_reason support
=> LinuxSCSI:replace error log messages with calls to ocf_exit_reason

heartbeat/IPsrcaddr
Update code from https://github.com/ClusterLabs/resource-agents/pull/1745 to use tabs like the rest of the code.
=> IPsrcaddr: fix indentation in better error message code

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/ocivip
New resource agent: ocivip
This new resource agent allow to manage secondary private ip addresses for Compute instances
in the Oracle Cloud infrastructure (OCI)
=> ocivip: new resource agent

heartbeat/openstack-info.in
Also simplify striping of trailing comma.
=> openstack-info: fix bashism

heartbeat/db2
dash only allows -a as AND operator.
=> db2: fix bashism

heartbeat/docker-compose
Fixes https://github.com/ClusterLabs/resource-agents/issues/1741.
=> docker-compose: fix number of containers/running containers logic

.gitignore, configure.ac, doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/azure-events-az.in
Add a new resource agent for Azure Events that can monitor and process events on Pacemaker cluster that stretch across multiple availability zones.
=> azure-events-az: new resource agent

heartbeat/VirtualDomain
issue #704
VirtualDomain RA update ocf_exit_reason support
=> VirtualDomain: replace error log messages with calls to ocf_exit_reason

heartbeat/IPv6addr.c
Under heavy network load, the echo response to an echo request that was just sent may not immediately be available for reading, with recvmsg(MSG_DONTWAIT) failing with EAGAIN. This leads to occasional false positive "not running" events.
This wraps the recvmsg() within a poll() loop with a short timeout (10 ms) and retries reading the echo response up to 3 times, in case poll() was interrupted by some other event (e.g. EINTR).
Closes #1855
=> IPv6addr: expect ping/pong delay

configure.ac, heartbeat/storage-mon.in, resource-agents.spec.in, tools/Makefile.am, tools/storage_mon.c
Hi All,
This fix is a modified version of the following PR.
- https://github.com/ClusterLabs/resource-agents/pull/1862
This PR reflects the comments in the previous PR.
Please comment on this fix.
Best Regards,
=> Mid: storage-mon: daemonize storage_mon to deal with I/O hangs.(Add daemon/client mode)

tools/ocft/exportfs, tools/ocft/exportfs-multidir
fsid parameter is now considered optional.
=> exportfs: remove test for "fsid=" parameter

heartbeat/findif.sh
Thanks to @lge for suggesting the patch in https://github.com/ClusterLabs/resource-agents/pull/1891
=> findif.sh: fix corner cases

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/osceip
This new resource agent adds functionality to manage a outscale elastic IP. It supports being configured as a primitive or as a master/slave set.
=> outscale: new resource agent

heartbeat/azure-events-az.in, heartbeat/ocf.py
Hi all,
we updated the azure-events resource agent with the following stuff:
1. Add request timeout
2. Add retry pattern (for all azure request)
3. Add configuration parameters for all new introduces values
4. Updated the tests at the ocf.py file.
Regards
=> azure-events-az: update to API versions, add retry functionality for metadata requests, update tests

heartbeat/Filesystem, heartbeat/ocf-shellfuncs.in, heartbeat/pgsql
* pgsql: pgsql_status: silence ERROR: command failed: runuser
* Filesystem: for "probe", silence "Expected /dev/... to exist"
=> Filesystem/pgsql: silence spurious WARNING and ERROR log messages

heartbeat/powervs-subnet.in
improvements on virtual server status collection, and subnet - port handling.
=> powervs-subnet: improvements on virtual server status collection, and subnet - port handling

heartbeat/powervs-subnet.in
Recent changes in the json structure in IBM Cloud IAM for returning the Apikey.
Improve calculation for timeout interval.
=> powervs-subnet: Modify gathering of Apikey, calculation of timeout.

heartbeat/findif.sh
=> findif.sh: ignore unreachable, blackhole, and prohibit routes

heartbeat/IPaddr2
=> IPaddr2: add proto-parameter to be able to match a specific route

heartbeat/Filesystem
Add new filesystem type for Azure.
- New azure filesystem type: ["azfns"](https://github.com/Azure/AZNFS-mount)
The new implementation enables the mounting of the Azure 'azfns' filesystem type with the right tools and type.
=> Filesystem: add new azure filesystem type "azfns"

heartbeat/ocf-binaries.in
Additional fix for https://github.com/ClusterLabs/resource-agents/pull/2011.
=> ocf-binaries: add FGREP

heartbeat/azure-events-az.in
Fix isNodeInStandby block changing "isInStandy" variable to "isInStandby"
=> azure-events-az: fix typo

heartbeat/azure-events-az.in
Set params explicitly in RA description using default values to give users a sane starting point.
=> azure-events-az: Add params defaults to RA description

heartbeat/azure-events.in
Backport improvements from new agent
=> azure-events: backport relevant changes from azure-events-az

heartbeat/azure-events-az.in
To align with deployment instructions of this agent in official Azure Docs
https://learn.microsoft.com/en-us/azure/sap/workloads/high-availability-guide-suse-pacemaker?tabs=msi#configure-pacemaker-for-azure-scheduled-events
=> azure-events-az: Update Deployment info section

heartbeat/ocf-binaries.in, heartbeat/portblock
Based on @zypek's https://github.com/ClusterLabs/resource-agents/pull/2063 with changes to reuse as much code as possible, and follow the main logic of the agent.
=> portblock: add nftables and multi-state support
