ClusterLabs/resource-agents

ldirectord/ldirectord.in
On sending email alert the "local part" of the sending mailaddress
(before @) is the "user" who start ldirectord.
This however does only work if you start /usr/sbin/ldirectord on a bash
shell.
Starting it via resource agent `ocf:heartbeat:ldirectord` seems not
forward the bash environment `"$ENV{USER}"`.
/var/log/mail shows like this:
```
Dec 12 12:30:41 sles11sp301 postfix/qmgr[15049]: 06B94103B9D:
from=<@sles11sp301.vmhamming.suse.de>, size=608, nrcpt=1 (queue active)
```
The following change (using "getpwuid( $< )" instead) will fix that problem.
=> Medium: ldirectord: Get correct user for sending email (bnc#910497)

heartbeat/findif.sh
When more than one interface is configured with a network that matches
the IP address we're looking for, but with different networks, the "ip
route" command we're using returns more than one line:
ip -o -f inet route list match 10.122.24.59 scope link
10.122.0.0/18 dev eth1.12  proto kernel  src 10.122.24.159
10.122.24.0/25 dev eth0  proto kernel  src 10.122.24.53
The code assumed that only one line would be returned, and so it's
parsing only the first line, without trying to find out which line is
the best match. What we want is the route with the bigger netmask. It
turns out that it also means that it's the route with the bigger network
IP.
https://bugzilla.novell.com/show_bug.cgi?id=892755
=> findif.sh: Use the most specific matching route

ldirectord/ldirectord.cf, ldirectord/ldirectord.in
"password" option is not implemented.
"login" option is used for the attribute User-Name.
By the way, modify typo "::"->":"
=> low: ldirectord: modify manual and sample for Radius check

ldirectord/systemd/ldirectord.service.in
Can not remove virtualservice when stopping ldirectord via systemctl.
```
checktimeout=3
checkinterval=1
autoreload=yes
quiescent=no
virtual=192.168.6.240:80
real=192.168.6.2:80 gate
real=192.168.6.3:80 gate
real=192.168.6.6:80 gate
fallback=127.0.0.1:80 gate
checktype=on
root      1406     1  0 15:13 ?        00:00:00 /usr/bin/perl -w /usr/sbin/ldirectord start
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
-> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  192.168.6.240:80 wrr
-> 192.168.6.2:80               Route   1      0          0
-> 192.168.6.3:80               Route   1      0          0
-> 192.168.6.6:80               Route   1      0          0
<no process>
IP Virtual Server version 1.2.1 (size=4096)
Prot …
```
=> Medium: ldirectord: Fix can not remove virtualservice when stopping ldirectord via systemctl

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/sg_persist, tools/ocft/Makefile.am, tools/ocft/sg_persist
sg_psersist is a resource agent that implements SPC-3 Persistent
Reservations (contribution from Evgeny Nifontov).
Customers with an active-passive storage setup using MD-raid1 need
to ensure, that the MD device is only activated on one system at a
time. While this is clearly possible with the existing Raid1 RA,
there is still the possibility that crazy system administrators
assemble such devices manually from the command line, leading to
a complete data-loss as a result...
There exists an implementation of a resource agent around the "sg_persist"
Utility from the sg3_utils package. The sg_persist RA is just based on
the sg3_utils tools. It works as a Master/Slave resource. It registers a
reservation key for devices when the resource starts and holds reservation
when the resource promotes …
=> new RA sg_persist

heartbeat/iscsi
Some platforms (most?) use records the open-iscsi database in
/etc/iscsi/nodes to store some configuration data, such as
whether to login to the target on boot (node.startup). This
database is rebuilt on iscsi discovery or discoverydb (depending
on the version). Better avoid that operation unless necessary.
This patch makes the RA run discovery only if the record for the
given target and portal is not present.
=> Medium: iscsi: run iscsi discovery only when necessary

rgmanager/src/resources/utils/fs-lib.sh
Improper quoting when checking the mktemp result causes a false positive when that command failed to create the file, such as from a file-system being read-only.
=> fs-lib.sh: Fix missed detection of write failure

rgmanager/src/resources/mysql.sh
Honor the --user or -u parameter specified in mysqld_options when creating or chowning the pid directory for MySQL.
=> mysql.sh: Allow MySQL to run as user other than mysql

heartbeat/nginx
The current script will use `status10url` for both level 10 and level 20 monitor operations, but the documentation indicates that `testurl` will be used for a level 20 monitor.
This patch restores the documented behavior.
=> Fix simple transposition of options for TESTURL

heartbeat/VirtualDomain
The virsh migrate command has many options which may be passed
with this parameter. The other purpose is the possibility to
override the migrateuri option, in case the automatically
built string is not appropriate.
=> Medium: VirtualDomain: add migrate_options parameter

heartbeat/redis
I tried some of the existing redis resource agent scripts in the pull requests here and ran into a plethora of issues so I ended up creating my own. This was written completely from scratch, not done by rewriting code from another resource agent, and as such the code is a lot simpler than the other redis scripts (less than half the size).
* It does not use `start-stop-daemon`, and thus is not dependent upon debian/ubuntu
* It properly sets the default master priority based on the `slave_priority` setting from the redis config.
* It preserves the currently running master when taking the resource from unmanaged to managed. This is important as I needed to convert a single redis server into a pacemaker master/slave cluster without shutting redis down.
* It properly starts each client up in …
=> add redis resource agent script

heartbeat/portblock
This is a draft - I'm not a TCP/IP guru so someone else should verify my changes regarding TCP RST vs. ICMP port unreachable (although I did test them myself so I'm pretty sure I'm right).
Also I didn't yet test the `portno` type change or the example `crm configure` command.
=> [WIP] misc portblock fixes

heartbeat/Filesystem
- Trivial addition of overlayfs as a supported, non-block-device, cloneable filesystem.
- Fix for two misspelled log messages.
=> Filesystem: support overlayfs, fix log messages

rgmanager/src/resources/postgres-8.metadata
=> Low: rgmanager: drop unused shutdown_wait in postgres-8.metadata

heartbeat/redis
The redis agent was not properly verifying that slave connections were established with the Master instance. There were also some issues with how it used the CRM notify variables to try and predict the next and current master instances. I've resolved the issues with inaccuracies in the CRM notify actions by storing the last known active master instance in a CIB variable. This has proven to be much more consistent during my testing. It also allows us to more accurately verify whether or not a slave link to a master instance should be "up" .
I've added a new feature called "wait_last_known_master". This option makes use of persistent database storage safer in that we will not allow the redis cluster to bootstrap after a complete failure until the last known master has been promoted. The …
=> Redis cleanup

heartbeat/pgsql
This pull request aim to fix the following issue.
https://github.com/ClusterLabs/resource-agents/issues/565
=> Low: pgsql: fix check_wal_receiver to prevent incorrect "ERROR" status display and output WARN log in the master

heartbeat/pgsql
This change enable to use replication slots with pgsql RA.
Replication slots is the new feature of PostgreSQL 9.4.
Without replication slots if the slave is disconnected, it may be necessary to synchronize with the master in order to connect to the master node.
By using replication slots, slave node can connect to the master node without synchronizing.
this may solve the issue #291
=> pgsql: Support replication slots

rgmanager/src/resources/orainstance.sh
Fix a bug that can cause the script to pause for 90 seconds.
rhbz#1200639
=> orainstance.sh: Fix process name grep in exit_idle

heartbeat/apache, heartbeat/named, heartbeat/ocf-shellfuncs.in, heartbeat/zabbixserver
This should help agents that manage daemons running as non-root to create a state directory (for say PID files) which is unique and writeable by the daemon process. Should help fix #350 and #351.
=> help various RA create state directory

heartbeat/asterisk
If asterisk_monitor called from asterisk_start, return OCF_NOT_RUNNING instead of OCF_ERR_GENERIC
=> Fix return code in asterisk_monitor No.2

heartbeat/galera
I've finally been able to remove the galera resource-agent's dependence on 'read-only' mode for retrieval of the last known write sequence number. The technique I'm using now should be much more efficient and reliable. It is also backwards compatible with any previous galera resource-agent deployments.
=> High: galera: retrieve last sequence number without using read-only mode

heartbeat/redis
Current Resource Agent wait 20 seconds to initial sync to finish. 
If the sync takes longer then 20 seconds (can be if huge amount of data is synced), the start fails, altought fully OK. This fix waits for the sync to finish forever. meta op start timeut=xxx should set an appropriate value for the start to timeout.
=> Fixed redis start operation if replication sync takes > 20 seconds

.travis.yml, ci/build.sh, ci/install.sh
This adds a Travis CI which invokes shellcheck on all scripts
in the repository. It doesn't currently signal failure, but the
build job output can be inspected for any issues that should
be fixed.
=> Dev: Add Travis CI job which runs shellcheck on all scripts

heartbeat/pgsql
This pull request aim to eliminate duplicate "ocf_exit_reason" in the pgsql RA.
=> Low: pgsql: eliminate duplicate "ocf_exit_reason".

heartbeat/docker
Docker: fix docker existance test report error
according to `docker inspect --help`, `docker inspect` may report information
for both container and image, if there's a image named "XYZ", and trying to
inspect "XYZ" w/o specifying `--format {{.A.B.C}}`, it would report image
state instead of container state.
$ sudo docker inspect --help
Usage: docker inspect [OPTIONS] CONTAINER|IMAGE [CONTAINER|IMAGE...]
Return low-level information on a container or image
and further more, we should judge if it is really a container,
here we use `--format {{.State.Running}}`, and more, we should judge if
it is really a container by determining return value, if it is a container,
we should get a string of boolean value "true" or "false", and we can tell it
is a Docker container, but not a Docker image.
if …
=> Fix docker existance test

heartbeat/pgsql
Initialize the replication slot (delete an old slot if exists and create a new one)
to prevent that the old slot runs out of disk space.
Without the initialization, PostgreSQL would try to use the old slot after a node
failed once and re-joined to the cluster, and continue to accumulate WAL files for
the old slot, which would eventually run out of disk space.
Reflects following comments #619, #634
=> Medium: pgsql: delete an old replication slot when creating the slot.

heartbeat/iSCSILogicalUnit
This PR contains three improvements to `iSCSILogicalUnit`. One is generic, the other two are specific to the `lio-t` implementation.
- 1b3ac8f extends behavior previously present just for `lio` to `lio-t`, in that it checks for existence of the backing store ConfigFS entry in stop, as opposed to just that for the iSCSI LUN. Fixes #640.
- 7e051ab is being more persistent on stop. `targetcli` will fail when attempting to delete a LUN that has already been deleted; previously we would bail out then and there letting the backing store entries linger (and keeping underlying block devices busy). Fixes #642.
- aae6d1b is generic and checks the existence of the underlying block device on monitor. If the backing device is not there, we can safely assume that the LU is not exported. Fixes #641. …
=> iSCSILogicalUnit improvements

heartbeat/iSCSITarget
This is the same commit as referenced in PR #631, updated with a proper, non-`.local` email address.
=> iSCSITarget: properly create portals for lio-t implementation

heartbeat/CTDB
When updating smb.conf, the permissions are not preserved.
This may cause smbclient to be unable to read the file where
it was previously able.
Resolve the problem by copying the new configuration into
place, rather than moving it.
=> Medium: CTDB: Preserve permissions on smb.conf (bsc#935253)

heartbeat/tomcat
It is recommended to use runuser command instead of su to run resources in SELinux enforcing mode because it would generate lots of SELinux errors as shown in the blog <http://danwalsh.livejournal.com/55588.html>. The issue #632 of ocf pgsql resource agent happens to ocf tomcat resource agent because it uses su command.
=> Med: tomcat: Use runuser command instead of su to run selinux enforcing mode

heartbeat/pgsql
Commit d67c0ae (pgsql: Support replication slots) overrides return code of pgsql_real_monitor() in pgsql_real_start() function when replication_slot_name is defined.
So pgsql_real_start() never returns $OCF_RUNNING_MASTER and pgsql_promote() failed with error "Can't start PostgreSQL as primary on promote." on cluster startup.
=> pgsql: Fix return code override in pgsql_real_start()

heartbeat/pgsql
This is the fix of https://github.com/ClusterLabs/resource-agents/issues/655 .
Would you please check it and merge?
=> Low: pgsql: set_master_score use an undefined variable($target).

heartbeat/IPaddr2, heartbeat/findif.sh
Remove inaccurate statement about not passing a broadcast argument, and add description of `+` and `-` arguments for broadcast address.
These are passed to `ip address` to calculate the broadcast address based on the prefix.
=> findif.sh: Add + and - broadcast arguments (bsc#940931) (#656)

heartbeat/galera
The MYSQL_HOST and MYSQL_PORT settings are part of /etc/sysconfig/clustercheck and are interpreted by the /bin/clustercheck script; this PR ensures that they are also interpreted by the galera resource agent.
The rationale for these settings, even though right now we connect to MySQL/MariaDB using a locak socket connection, is that when using MariaDB-Galera, we have the option to use the [extra_port](https://mariadb.com/kb/en/mariadb/server-system-variables/#extra_port) option, which specifies an alternate listening port for MariaDB with its own max connections limit set via [extra_max_connections](https://mariadb.com/kb/en/mariadb/server-system-variables/#extra_max_connections).  
The primary rationale for these settings is so that the MariaDB server is able to report that it's "up" as a …
=> galera: add support for MYSQL_HOST and MYSQL_PORT from clustercheck

tools/send_arp.linux.c
send_arp.linux.c was created to avoid a libnet dependency.
It was Based on arping from iputils as it was back then,
and adapted to the command line conventions established by
the libnet based send_arp by Matt Soffen,
as it was used by IPaddr and IPaddr2.
On infiniband, the link layer addresses won't fit into a sockaddr_ll,
causing a buffer overflow.
The broadcast address may be different from "all 0xff".
This (and some more) has been fixed meanwhile in iputils arping.
This is just a re-merge from iputils, keeping the few adaptations we
need for IPaddr2 command line conventions, and some static/inline/const
fixes to quiescen the compiler warnings.
=> send_arp: fix for infiniband, re-merge from upstream iputils arping

heartbeat/docker
I know that a correction of docker RA still remains.
https://github.com/ClusterLabs/resource-agents/pull/649
https://github.com/ClusterLabs/resource-agents/pull/651
However, handling of the variable of next commit is like the mistake on
latest docker RA.
https://github.com/ClusterLabs/resource-agents/commit/5a6a77f963d90d818ca556104790a7e7fc9d84fa
But I do not know a lot about docker RA, this correction may be wrong.
Best Regards,
=> Medium: docker: Correction of the mistake of the variable name.

heartbeat/README.galera, heartbeat/galera
When a Galera cluster is starting, the joining nodes which require a SST can take a long time to transfer the required data. This can cause the resource agent to fail the promotion to Master due to timeout.
This pull request changes the way a cluster is started:
. The bootstrap galera server is still started and switched to Master during the promote 'op' as usual.
. The remaining galera servers are started by the monitor 'op'.
. The monitor 'op' tracks the progress of the SST and triggers the promotion to Master only after the SST is finished.
Squashed commit of the following:
commit d34ea174b9abdca5101fea65d0ae594f9ec45d3c
Author: Damien Ciabrini <dciabrin@redhat.com>
Date:   Mon Oct 5 12:20:45 2015 +0200
galera: document the updated boot process
commit …
=> galera: start joining nodes during 'monitor' to allow long-running SST

heartbeat/iSCSITarget
When multiple portals are provided using "portals=" switch
the old code will attempt to create IQN for every portal. This is not
correct. There should be just one IQN and multiple portals to it.
targetcli will return error if attempting to create IQN that already exists.
=> Fixed attempts to create iqn multiple times for every portal.

heartbeat/pgsql
fixes two issues:
- xlog_check_count: default value was not shown in the meta-data
- ctl_opt: default value was not initialized properly
(although it's been working perfectly as expected)
ref. https://github.com/ClusterLabs/resource-agents/issues/576#issuecomment-90826628
=> Low: pgsql: properly show default values in meta-data

heartbeat/LVM
validate-all fails when any physical volumes are missing due to vgck
returning a failure, causing start to also fail. partial_activation=true
would allow us to start successfully in those situations, so only fail
validation from vgck we're not activating partially, or the VG is not
listed as partial, or if its marked partial but all devices are
accounted for.
=> LVM: Allow vgck failures if partial

heartbeat/mysql-common.sh
Hi All,
I send a patch to improve the problem of the stop that I reported by an email
* http://clusterlabs.org/pipermail/users/2015-November/001773.html
The patch includes the next change.
* Commonization of the function
* Restraint of the output of the redundant deletion message of the PID file
Best Regards,
=> When stop processing is carried out when mysql fell while monitor does not detect an error, the cluster fails in a stop of mysql.

heartbeat/IPaddr2
what we need here should be `A && (B || C)`
please refer to the result of following simple tests
before patch:
```
true  && true  || true;  echo $?;  # return value: 0
true  && true  || false; echo $?;  # return value: 0
true  && false || true;  echo $?;  # return value: 0
true  && false || false; echo $?;  # return value: 1
false && true  || true;  echo $?;  # return value: 0
false && true  || false; echo $?;  # return value: 1
false && false || true;  echo $?;  # return value: 0
false && false || false; echo $?;  # return value: 1
```
after patch:
```
true  && (true  || true);  echo $? # return value: 0
true  && (true  || false); echo $? # return value: 0
true  && (false || true);  echo $? # return value: 0
true  && (false || false); echo $? # return value: 1
false && (true  || true); …
```
=> IPaddr2: potential syntax error on if-then-else

heartbeat/nfsserver
On SUSE systems, we do not have a nfs-lock.service service script,
but we use nfs-server.service to manage NFS using systemd.
This patch adds a new EXEC_MODE which uses nfs-server.service to manage
the NFS server, but calls rpc.statd to handle NFSv3 locking.
=> nfsserver: Add EXEC_MODE for systemd without nfs-lock.service

heartbeat/pgsql
The keywords "FAILED" or "ORPHANED" might be displayed in previous position of the role.
And the program output is a moving target , any keywords might be displayed, so I add wild card to grep pattern.
=> Low: pgsql: fix grep failure when using pacemaker 1.1.12

heartbeat/nfsserver
The previous patch to fix this issue was insufficient. From what I can tell, we need to use the `rpc-statd.service` in the same way as `nfs-lock.service` is used in `EXEC_MODE=2`. `nfs-lock.service` is simply a renamed `rpc-statd.service` from NFS upstream.
=> nfsserver: Use rpc-statd.service for NFS locking in EXEC_MODE=3

heartbeat/VirtualDomain
New VirtualDomain resource attributes
**migration_downtime**
Allow live migration of machines with higher memory pressure (milliseconds)
You can for example try to run stress test (to simulate higher memory pressure) inside guest os (cpu:2, ram:2GB):
```bash
stress --cpu 1 --vm 13 --vm-bytes 128M --vm-hang 1 --timeout 900s 
```
on the host side try to run live migration of that same vm with pcs (this cmd will probably timeout at the end and machine will be relocated (stop/start)):
```bash
pcs resource move testvm1 host2
```
then try the same cmd but with a **migration_downtime** attribute in place:
```bash
pcs resource update testvm1 migration_downtime=1000
pcs resource move testvm1 host2
```
**migration_speed**
Set the maximum migration bandwidth (in MiB/s) for a domain which is being …
=> VirtualDomain: New resource attributes migration_speed and migration_downtime

heartbeat/docker
The patch converts a container name at the time of the globally-unique
designation into a form supported in docker.
When docker RA cannot generate the name at the time of globally-unique
designation automatically, the patch returns an error.
If there is the method that is better for handling of sed of the patch,
I want you to change it.
Some problems still remain for the use with the clone of docker RA.
This is a temporary correction, but this correction blocks some problem
movement.
Best Regards,
=> Mid : Generation and error check of the container name at the time of the globally-unique designation.(repost)

heartbeat/mysql
On MySQL 5.6 or higher, the "SHOW VARIABLES" command returns the multiple rows that contains the "read_only".(innodb_read_only, read_only and tx_read_only)
So, I add "-w" to grep option.
=> High: mysql: fix grep failure on MySQL5.6 or higher when checking read_only variable

heartbeat/nfsserver
/var/lock/subsys does not exist on debian/ubuntu. Primarily a RedHat-ism. Check for it first.
=> /var/lock/subsys is non-standard, check for it first

heartbeat/mysql
The function get_slave_info() makes a tmpfile that named /var/run/resource-agents/check_slave.mysql.XXXXXX.
This tmpfile is removed by the function that called a get_slave_info().
However, The function is_slave() calls the get_slave_info() , but does not remove tmpfile.
When set the OCF_CHECK_LEVEL to 10, in the Slave node, the function is_slave() will be called from the mysql_monitor.
So, the number of the tmpfile continues increasing in every 10 seconds in the Slave node.
=> Low: mysql: tmpfile is leaking when set the OCF_CHECK_LEVEL to 10

heartbeat/ocf-shellfuncs.in
Fixes the issue: https://github.com/ClusterLabs/resource-agents/issues/734
=> Medium: ocf_shellfuncs: suppress bash specific trace_ra log on dash

heartbeat/pgsql
=> Low: pgsql: fix to be used valid charcters when the invalid characters is used in replication_slot_name.

heartbeat/sg_persist
a=`ocf_run ...` is no good, because ocf_run logs stdout/stderr outputs.
=> Medium: sg_persist: remove uncalled for ocf_run calls

heartbeat/VirtualDomain
There where several places testing how to properly exit depending on the action. That's handled properly by ocf-rarun.
=> Dev: VirtualDomain: switch to ocf-rarun to reduce complexity

ldirectord/ldirectord.in
This error was noticed in the logs:
Use of uninitialized value in numeric gt (>)
The uninitialized use comes from the "_service_up" function
which tries to read an uninitialized array element "failcount"
which get only written (set > 0) in the "_service_down" function.
This patch sets failcount to 0 in the constructor to avoid
triggering the error.
=> Low: ldirectord: Fix unset failcount error

heartbeat/iscsi
Based on issue "resource-agents/heartbeat/iscsi works incorrectly with multipath scheme #744"
=> Add portal check to open_iscsi_get_session_id()

heartbeat/README.galera, heartbeat/galera
If a Galera node is unexpectedly killed in a middle of a replication, InnoDB can retain the equivalent of a XA transaction in "prepared" state in its redo log. If so, mysqld cannot recover state (e.g. last seqno) automatically, and a special recovery flag has to be used on command line to unblock the node:
160129 14:47:27  InnoDB: Starting recovery for XA transactions...
160129 14:47:27  InnoDB: Transaction 7900 in prepared state after recovery
160129 14:47:27  InnoDB: Transaction contains changes to 1 rows
160129 14:47:27  InnoDB: 1 transactions in prepared state after recovery
160129 14:47:27 [Note] Found 1 prepared transaction(s) in InnoDB
160129 14:47:27 [ERROR] Found 1 prepared transactions! It means that mysqld was not shut down properly last time and critical recovery information …
=> galera: use mysql's --tc-heuristic-recover if crash recovery is needed

tools/ocft/Makefile.am
v3.9.7 fails to build the rpm by using the included configure scritps. Apparently runocft script is missing in the tarball which is introduced by #730.
Steps to reproduce:
```
[root@build-centos71 resource-agents (master)]# git checkout v3.9.7
[root@build-centos71 resource-agents ((v3.9.7))]# ./autogen.sh && ./configure && make rpm
(omit)
Making all in ocft
gmake[4]: Entering directory `/root/rpmbuild/devel/resource-agents/resource-agents-3.9.6.272-e697f/tools/ocft'
gmake[4]: *** No rule to make target `runocft', needed by `all-am'.  Stop.
gmake[4]: Leaving directory `/root/rpmbuild/devel/resource-agents/resource-agents-3.9.6.272-e697f/tools/ocft'
gmake[3]: *** [all-recursive] Error 1
(omit)
```
=> v3.9.7 build failure

heartbeat/LVM
Without the options being you end up with the following error message during resource startup
Feb 24 22:14:47 cluster-a lrmd[1717]:   notice: vg0_start_0:2344:stderr [ /usr/lib/ocf/resource.d/heartbeat/LVM: 415: local: --monitor: bad variable name ]
=> quote vgchange options

heartbeat/SAPDatabase, heartbeat/sapdb.sh
To work with Oracle 12c the agent needs an option
to pass the new Database Username to the resource.
Example configuration:
primitive oracle-database SAPDatabase \
params \
SID=HAO \
DBTYPE=ORA \
DBOUSER=oracle \
STRICT_MONITORING=1 \
op monitor interval=120 timeout=60
=> High: SAPDatabase: Add support for Oracle 12c

heartbeat/apache
* Added Debian Configuration File
* Added fix for folder detection/creation/configtest for debian based default configurations. This fix also removes the hardcoded ubuntu workaround
=> Fix debian start for heartbeat/apache

heartbeat/galera
mysqld's pidfile is only created after SST finished.
RA has to track mysqld process differently at startup to allow
monitoring long SST during "monitor" op.
=> galera: fix monitoring of joining node for long running SST

ldirectord/ldirectord.in
Short patch to tidy some protocol names, e.g. previously could be all different capitalisation: "HTTP", "imap" and "Radius".
=> ldirectord: Clean up protocol names/abbreviations

heartbeat/README.galera, heartbeat/galera
This is a generalization of commit 4d98bbcdadda60166faf7ccc512b9095b439e2bd.
When several nodes can be chosen as the bootstrap node (e.g. identical last seqno), we avoid choosing a node whose local file grastate.dat doesn't exist.
. This avoids choosing nodes recovered with --tc-heuristic-recovered because the agent explicitly removes grastate.dat on those nodes to force a SST at restart.
. This further improves commit 4d98bbcdadda60166faf7ccc512b9095b439e2bd as we track grastate.dat via a transient attribute in the CIB set at node start up, rather than relying on long-lived attribute "galera-heuristic-recovered" which could get out of sync with the state of the DB at the time a node is restarted.
. If other nodes have appropriate seqno, one can "force" the agent to avoid bootstrapping …
=> galera: don't bootstrap from a node with no grastate.dat when possible

tools/tickle_tcp.c
Without patch:
```
Failed to open raw socket (Invalid argument)
Error while sending tickle ack from '10.34.70.84:5000' to '10.34.71.128:6000'
255
```
=> tickle_tcp: Fix "Failed to open raw socket (Invalid argument)" issue

heartbeat/oracle
From log:
ERROR: could not create OCFMONPROFILE oracle profile
ERROR: sqlplus output: create profile OCFMONPROFILE limit FAILED_LOGIN_ATTEMPTS UNLIMITED PASSWORD_LIFE_TIME UNLIMITED#012               *#012ERROR at line 1:#012ORA-65140: invalid common profile name
Ref:
https://www.oraexcel.com/oracle-12cR1-ORA-65140
=> oracle: inform user that monprofile must start with C## for container databases

heartbeat/ocf-directories.in, heartbeat/shellfuncs.in
This change actually fixes issue #793 
With the HA_VARRUN directory changed. I could actually start the apache
Here's an example of the issues that got fixed. I delete the run and lock directory to make sure that the ocf script actually has to create them.
```
root@cluster-a:~# rm -rf /var/lock/apache2/
root@cluster-a:~# rm -rf /var/run/apache2/
root@cluster-a:~# export OCF_ROOT=/usr/lib/ocf
root@cluster-a:~# /usr/lib/ocf/resource.d/heartbeat/apache start
ERROR: cannot create /var/run/apache2 (does not start with /var/run/)
ocf-exit-reason:environment is invalid, resource considered stopped
```
After adjusting the directory path for HA_VARRUN
```
root@cluster-a:~# vi /usr/lib/ocf/lib/heartbeat/ocf-directories 
root@cluster-a:~# rm -rf /var/lock/apache2/
root@cluster-a:~# rm -rf …
```
=> Low: Fix directories in ocf-directories

heartbeat/symlink
If the directory in which the symlink target is not existing, migration
after failure fails due to the probe reporting an error on the failed
node with a broken symlink.
To handle this, use "readlink -m" over "readlink -f". From the readlink
man page:
>        -f, --canonicalize
>               canonicalize by following every symlink in every component of the given name recursively; all but the last component must exist
>
>        -e, --canonicalize-existing
>               canonicalize by following every symlink in every component of the given name recursively, all components must exist
>
>        -m, --canonicalize-missing
>               canonicalize by following every symlink in every component of the given name recursively, without requirements on components existence
=> Medium: symlink: Handle missing directories in target (bsc#973054)

heartbeat/nagios
VAR="/etc/path with spcaes"
`[ ! -f ${VAR} ]`
equals to `[ ! -f /etc/path with spaces ]` ### syntax error
`rm -f ${VAR}`
equals to `rm -f /etc/path with spaces`    ### accidentally remove files/folders
`-eq` and `-ne` with number (not string)
Signed-off-by: guessi <guessi@gmail.com>
=> Low: Fix protential error for RA:nagios

heartbeat/mysql
In case the mysql master server is running on non-standard port, like 3308 for example, and on the same machine there is another mysql server listening on 3306, the ocf script sets the wrong details.
The problem comes from the fact, that this OCF script exports a parameter replication_port, which is actually never used.
Signed-off-by: Marian Marinov <mm@yuhu.biz>
=> heartbeat/mysql: Handle non-standard mysql server port

heartbeat/VirtualDomain
Fix for unnecessary logging when using LXC (only shows on the nodes where the container hasnt been run yet):
VirtualDomain(container1)[4736]: ERROR: Unable to determine emulator for lxc1
=> VirtualDomain: fix unnecessary error when probing nonexistent domain

ldirectord/ldirectord.in
When starting up, if a service is not listed in the ipvsadm table the parent process will mark it as 'down'. Each child process will then go through its own services and mark them as 'up'.
However, if there is more than one service defined, the services from the other children are still marked as 'down'.  In this case each child will repeatedly e-mail out 'Inaccessible real server' messages for services now managed by the other children.
To prevent this, we go through the e-mail status hash as a child starts up and remove any services that now belong to other children.
=> ldirectord: Don't send Inaccessible real server e-mails in fork=yes mode

heartbeat/iSCSILogicalUnit
These are a couple of fixes to make iSCSILogicalUnit work with tgt's rbd backing store.
=> iSCSILogicalUnit: fixes for tgt's rbd (Ceph) backing store

heartbeat/rabbitmq-cluster
This fixes a very small but annoying typo. In case of rabbitmqctl cluster_monitor failure make error message print exact command failed.
Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>
=> [rabbitmq-cluster] Typo fix

heartbeat/SAPDatabase, heartbeat/sapdb.sh
> This pull request combines #802 and #803 into a single branch.
Pass the timeout on stop/start operation to saphostctrl in order to avoid that SAPDatabase will run into timeout with big databases.
-with big SAP Hana Database, saphostctrl is running into a timeout when a start/stop is triggered, because ￼SAPDatabase is not passing  the timeout parameter to saphostctrl and saphostctrl is using default start/stop timeout which is not enough.
-saphostctrl running into a timeout is reporting the exit code to SAPDatabase and Pacemaker is interpreting the response as a fail, even if the SAP Hana is stopping / starting in background.
```
-saphostctrl accept timeout as argument:
StartDatabase
-dbname <DB name> -dbtype <ada|db6|mss...> [-dbhost <hostname>] [-dbinstance <instance name>] [-dbuser …
```
=> High: SAPDatabase: Add START|STOP_TIMEOUT parameters

ldirectord/ldirectord.cf, ldirectord/ldirectord.in
This is solely for the purpose of adding more useful information into the alert e-mails so they become more useful for system administrators who have many load-balanced services.
Running a load balancer service for many different people and alerts can sometimes get confusing to try and work out exactly what service it is or who is responsible for it! Have been running this code for a couple of weeks and it's working fine here.
=> ldirectord: Add new "servicename" and "comment" options to each virtual server

ldirectord/ldirectord.in
When the daemon is starting up it sets DAEMON_STATUS to STARTING, aligns its internal tables with those of ipvsadm (in ld_start), then sets DAEMON_STATUS to RUNNING.
This means that any services which are down (which is usually the case when ldirectord is not running, unless cleanstop=no is set) will be marked as down in STARTING state.
Then when the main loop in ld_main is run, the services will all be detected as 'up', but as we are now in RUNNING state, so e-mails will be sent out. This isn't really a running state, though - we've only just started up.
To prevent this from happening, do a one off initial check of all real servers in the ld_start, which means that services will be detected as 'up' when in DAEMON_STATUS STARTING. From then on the ld_main (or the children in fork=yes …
=> ldirectord: Correctly suppress startup e-mails when emailalertstatus=running

heartbeat/nfsserver
This change adds the Debian default NFS server init script to the resource agent.
=> Low NFS: add more default init scripts to check

heartbeat/awseip
make it possible to associate secondary private ip address with elastic
ip address, if allocation-id.
if private-ip-address were both set, it will try to associate elastic
interface with the allocation-id, otherwise, it will try to associate
elastic ip with private ip instead (default).
reference docs:
http://docs.aws.amazon.com/cli/latest/reference/ec2/associate-address.html
=> Low: extend support for AWS elastic ip association

heartbeat/rabbitmq-cluster
Recent RabbitMQ versions return 69 when a node isn't running. Previous
versions return 2 in this case. This change was introduced in commit
rabbitmq/rabbitmq-server@7984540175d0b8852025165b6b6a0ac05d692c98.
See this RHBZ issue for further details:
* https://bugzilla.redhat.com/1338657#c8
=> RabbitMQ: New error code - 69

doc/man/Makefile.am, heartbeat/Makefile.am
New garbd agent is not installed and man page is not generated either.  This pull request fixes that.
=> garbd: fix install and man page

heartbeat/rabbitmq-cluster
RabbitMQ allows to create additions users (different from system ones). These users may be used for RabbitMQ cluster/node monitoring via HTTP(S). Unfortunately they are removed during the resource restart. We should keep them instead.
This patch prevents users from being wiped out by dumping them into a temporary file within RabbitMQ data directory, and restoring them later.
=> Backup and restore rabbitmq users during resource restart

heartbeat/exportfs, heartbeat/ocf-shellfuncs.in
exportfs resource relies on output from exportfs utility which in turn
stores its state data in /var/lib/nfs/etab. This file survives reboot
(e.g. after fencing) and when probe monitor operation is invoked
exportfs RA will report resource as *started* if there are respective
records in /var/lib/nfs/etab despite the fact nfsserver resource is
not started and exportfs resource is thus effectively *stopped*.
Normally this is not a problem because nfsserver clears content of
/var/lib/nfs/etab upon start, however, when only monitor operations are
executed (e.g. probing after reboot) wrong state of exportfs resource is
reported.
This solution puts alleged status of the resource in logical conjunction
with pseudo resource state (i.e. it's not pure pseudo resource, just
necessary condition). The …
=> exportfs: Add pseudo resource factor (bsc#978680)

heartbeat/exportfs
exportfs command returns IPv6 IPs without the [] around client IPs.
=> exportfs: Add IPv6 support

heartbeat/rabbitmq-cluster
If a first attempt at joining an existing cluster has failed and we
resort to wiping the local RabbitMQ data, make sure we also request the
local node to be forgotten from the existing cluster before we make the
join attempt, otherwise the node will be rejected.
=> RabbitMQ: Forget node before 2nd joining attempt

heartbeat/galera
On Debian and Ubuntu distributions, the ``/etc/sysconfig/`` directory doesn't exist.
This directory is replaced by ``/etc/default/``.
=> [galera] Add /etc/default/clustercheck importation

heartbeat/pgsql
This pull request fixes the issues below as discovered in #795.
- stop escalation did not work and caused an unnecessary fencing when a stop timeout is configured too short (approx. <= 60s)
- 'stop_escalate' parameter was obscure and hard to estimate the time to invoke stop escalation
=> pgsql: fix stop_escalate parameter issue

ldirectord/ldirectord.in
This patch includes the following two points.
* Fix the issue (pointed out in #796) in IPv4/IPv6 mixed environment.
It was resolved by always overwrite EXTRA_SOCK_OPTS in either case IPv4/IPv6.
* Modify the IPv6 workaround (added in #379 #470) to be applied only some environment 
where old perl libraries are installed.
Libraries versions of interest are the following URL for reference.
https://rt.cpan.org/Public/Bug/Display.html?id=75618#txn-1390771
=> Medium: ldirectord: Fix the issue in IPv4/IPv6 mixed environment

heartbeat/rabbitmq-cluster
We must add the following POSIX error codes in order to detect node
failure:
* 68 - EX_NOHOST
* 69 - EX_UNAVAILABLE
* 70 - EX_SOFTWARE
* 75 - EX_TEMPFAIL
* 78 - EX_CONFIG
The following commits introduced these return values:
* rabbitmq/rabbitmq-server@7984540175d0b8852025165b6b6a0ac05d692c98
* rabbitmq/rabbitmq-common@92ae50e5964d4f079c7b2abed1caaa8ab54a439b
For the error codes meanings go to:
* http://www.sbras.ru/cgi-bin/www/unix_help/unix-man?sysexits+3
* http://linux.die.net/include/sysexits.h
* https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=misc/sysexits.h;hb=HEAD
Note that the following error valies do not mean that the node is
stopped and therefore doesn't covered by this commit:
* 64 - EX_USAGE
* 65 - EX_DATAERR
* 67 - EX_NOUSER
Signed-off-by: Peter Lemenkov …
=> More RabbitMQ POSIX error codes

heartbeat/rabbitmq-cluster
When joining a node into an existing cluster, check to see if it is
already clustered before force removing it from the cluster and
re-adding.  If the clustering is already functional there's no need to
force it again.
=> rabbitmq: Allow automatic cluster recovery before forcing it

heartbeat/oracle
Added quotes to all occurrences of $MONPROFILE to avoid issues when it's set to e.g. "C##....":
>  stderr: ERROR: could not create OCFMON oracle user
>  stderr: ERROR: sqlplus output: create user OCFMON identified by "OCFMON" profile C##MPROFILE
>  stderr:             *
>  stderr: ERROR at line 1:
>  stderr: ORA-65096: invalid common user or role name
=> oracle: fix issue with C## in monprofile

tools/ocft/runocft
The script is executable, but doesn't have a shebang.
=> Dev: Add shebang to runocft script

heartbeat/sapdb.sh
When working with Multi-Tenant Databases in SAP Hana it creates multiple index servers and others  services with repeated names..
```
hana01:/usr/sap/hostctrl/exe> saphostctrl -function GetDatabaseStatus -dbname HPA -dbtype hdb 01 slehaloc
Database Status: Warning
Component name: hdbdaemon (HDB Daemon), Status: Running (Running)
Component name: hdbcompileserver (HDB Compileserver), Status: Running (Running)
Component name: hdbnameserver (HDB Nameserver), Status: Running (Running)
Component name: hdbpreprocessor (HDB Preprocessor), Status: Running (Running)
Component name: hdbwebdispatcher (HDB Web Dispatcher), Status: Running (Running)
Component name: hdbindexserver (indexserver-DB1), Status: Running (Running)
Component name: hdbindexserver (indexserver-DB2), Status: Running (Running) …
```
=> adjusting sapdb.sh to work with HANA Multi-Tenant Databases

heartbeat/docker
Using `docker exec` is a more reliable method for executing commands in the container than using `nsenter` directly.
=> Medium: docker: Use docker exec for monitor_cmd if supported

heartbeat/sg_persist
Various changes to improve robustness of the resource agent:
- Improve parsing of sg_persist (the tool) output to only match node ids, not arbitrary other numbers that happen to fit the pattern;
- fix invalid attribute names when running in debug mode;
- don't send informational output to stderr;
- cleanup nesting of code.
=> improve robustness of sg_persist resource agent

heartbeat/nfsserver
Services like NIS/ypbind use rpcbind and will stop when it is stopped
=> nfsserver: dont stop rpcbind, as other services might use it

heartbeat/docker
Reduce log level of successful monitor cmd to debug.
Set more informative exit reason on monitor failure.
=> Medium: docker: Reduce monitor log spam

heartbeat/redis
When selinux rules packages are installed, rundir does not yet exist,
and security context for it cannot be applied. Calling restorecon after
dir creation ensures that the proper context is applied to the rundir.
If the context is not applied, selinux denies write permission, the unix
socket cannot be created, and redis does not start
=> Redis: restore rundir security context

ldirectord/ldirectord.in
A fairly obscure bug to trigger, but in forking mode the following can happen:
* start ldirectord (children fork, EMAILSTATUS empty)
* service down (children notice, EMAILSTATUS set in children, reminders start)
* "reload" ldirectord (parent marks EMAILSTATUS set, children inherit EMAILSTATUS set)
* service up (children clears EMAILSTATUS, reminders stop)
* "reload" ldirectord (parent still has EMAILSTATUS set, children inherit EMAILSTATUS set)
children then start sending reminder notifications even though service is up.
This solution here is to completely clear %EMAILSTATUS after forking. The downside is that children will stop sending reminders after a parent reload, but they would in other situations anyway such as when a child process dies and is restarted.
This is a simplification of …
=> ldirectord: a further fix for spurious reminder e-mails

heartbeat/docker
Background:
Running a monitor_cmd regularly generated a lot of warning output in syslog from containerd. When investigating this, I got the following response:
```
The problem is that containerd is trying 
to keep track of all of the container processes, and you're starting and 
stopping processes using `docker exec`.
The warnings aren't really much to worry about, but AFAIK the only way 
of removing the warnings is patching container to stop emitting them. :/
However, I would in general warn against using Docker exec a lot. Due to 
a lot of ... interesting ... design choices, Docker exec isn't the best 
thing to be spamming against running containers.
```
Taking another look at the interaction between the resource agent and docker, it is probably better to recommend that a container …
=> Doc: docker: Clarify limitations of monitor_cmd in parameter description

heartbeat/slapd
Hi All,
I change the stop processing to the ocf_stop_processes processing.
Because the time-out of the KILL stop becomes effective, it may become late than before, but is not different in movement.
This correction changed former pullrequest.
- https://github.com/ClusterLabs/resource-agents/pull/850
Best Regards,
=> Low: slapd: Change of the stop processing.

heartbeat/apache
There is no need to log on every successful monitor action.
=> Low: apache: Reduce log spam for success

heartbeat/galera
Starting with mariadb 10.1.18, mysqld_safe does no longer output the WSREP last commit to the standard output when called with command line option --wsrep-recover. Instead, it logs that information into mariadb's error log.
Change the way the resource agent recovers that information by forcing logging to a file and parsing info from this file.
The change is backward compatible. Tested with ra-tester.
=> galera: make last commit parsing compatible with mariadb 10.1.18+

heartbeat/galera
During a demote, let the resource agent clear the master score of the
resource rather than letting pacemaker do so once demote finishes.
This way a promote cannot take place right after the current demote,
even if pacemaker is requested to do so. It will first have to run a
start/monitor op, to reprobe the state of the other galera nodes and
act accordingly.
=> galera: prevent promote right after demote

heartbeat/IPaddr2
This commit introduces a new parameter:
arp_count_refresh (default: 0)
This parameter allows to specify whether to send gratuitous ARP packets during
the monitoring of the resource, and how many.
This is to alleviate issues with potentially stuck switch ARP caches,
which can arise in case of split brain situations. Example:
- a two node cluster is connected directly and also to a switch. Node A
is master, node B is slave
- communication between master and slave is severed (split brain)
- node B initializes the virtual IPs and sends gratuitous ARP packets
- the switch updated its ARP table to point to B
- node B dies (without node A noticing)
- node A never notices anything wrong
Also, cleaned up mixed indentation.
=> Send gratuitous ARP packets during IPaddr2 monitor action

heartbeat/pgsql
greather then 2
the problem is that tr changes the replication slot string not
correnctly:
opsdbatest03 -> repl_slot_opsdbatest]]
replication slot name "repl_slot_opsdbatest]]" contains
invalid character.
this fix resolve this problem
=> pgsql: fix problem with creating replication slot names, when node count

heartbeat/rabbitmq-cluster
This PR fixes dump/restore users from RabbitMQ 3.6.x where internal structure was changed a little. Also it allows dumping/restoring users' permissions (see RHBZ 1342376).
=> Dump/restore users even in case of RabbitMQ 3.6.x and also dump/restore user permissions during restarts

heartbeat/ocf-shellfuncs.in
Check fails due to duble slashes in string comparison.
Path /var/run/apache2 is compared with /var/run//* giving the following error in the logs:
Dec 21 13:17:53 node1 apache(apache_/etc/apache2/apache2.conf)[826]: [868]: ERROR: cannot create /var/run/apache2 (does not start with /var/run/)
=> ocf_mkstatedir: fix path check

heartbeat/pgsql
PostgreSQL 9.6 introduced a new syntax for specifying
synchronous_standby_names. The old syntax, used by the pgsql RA, is
still valid but PostgreSQL now treats the standby-names in
synchronous_standby_names as SQL identifiers. This means such values
need to be double-quoted since they can easily contain dashes or other
characters that are not valid in a bare SQL identifier.
See the docs for synchronous_standby_names in
https://www.postgresql.org/docs/9.6/static/runtime-config-replication.html
for confirmation and
https://www.postgresql.org/message-id/21183.1481253534%40sss.pgh.pa.us
for a short discussion.
=> pgsql: Double-quote value of synchronous_standby_names in rep_mode.conf

heartbeat/nfsserver, heartbeat/nginx, heartbeat/scsi2reservation
This patch had been part of the Debian package since at least 2011.
=> Fix grammar and spelling in some resource agents

heartbeat/galera
Add a new option pcmk_host_map to the galera resource agent in case
names to be used in wsrep_cluster_address need to differ from names
used for the pacemaker nodes. (e.g. when galera names map to IP
from a specific network interface)
Option pcmk_host_map allows mapping pacemaker nodes to galera
nodes; it replicates the syntax used to set up fencing resources:
pcmk1:node.1.galera;pcmk2:node.2.galera;pcmk3:node.3.galera
=> galera: allow names in wsrep_cluster_address to differ from pacemaker nodes' names

heartbeat/rabbitmq-cluster
--=== !!!! WARNING !!!! Don't merge it yet - we're still testing it. ==--
We should reset Mnesia always beore joining cluster. Any necessary data
will be fetched from live node(s), so why care? Not doing so could led
to stuck node which needs manual repair.
Why bother with these Mnesia bytes? Better kill it and refetch!
Also related:
* https://bugs.launchpad.net/fuel/+bug/1431761
* https://bugs.launchpad.net/fuel/+bug/1620649
* https://bugzilla.redhat.com/show_bug.cgi?id=1397393
* rabbitmq/rabbitmq-server#946
=> RFC: RabbitMQ: Reset Mnesia before joining existing cluster

resource-agents.spec.in
Make rpm of v4.0.0rc1 fails.
Is not it necessary to collect metadata.rng?
```
(snip)
Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/rpmbuild/BUILDROOT/resource-agents-4.0.0-0rc1.el7.x86_64
error: Installed (but unpackaged) file(s) found:
/usr/share/resource-agents/metadata.rng
RPM build errors:
Installed (but unpackaged) file(s) found:
/usr/share/resource-agents/metadata.rng
make: *** [rpm] Error 1
```
=> specfile: Add metadata.rng to the file to be collected

heartbeat/Filesystem
This is requiered when using a zfs dataset with mountpoint=legacy in
order to mount/umount such dataset as a cluster resource.
=> Adds support for fstype=zfs on Filesystem resource agent

heartbeat/LVM
Detects partial issues even when the old code didnt (and if it's partial after the device becomes available again).
=> LVM: fix partial activation

heartbeat/galera
The current monitoring of long running SST does not work as expected.
A new monitoring approach is being implemented to tackle the issue;
until then, revert these PR.
Revert tested with ra-tester
=> galera: revert "long SST monitoring" PR #684 and #762

heartbeat/exportfs
regexps are valid inputs to clientspec (like `node[0-2].example.com`), which breaks if internal brackets are stripped.
Technically, removing from the beginning and end also breaks some regexps, but at least this should help some cases.
=> Medium: exportfs: Only strip brackets from edges of clientspec

heartbeat/iSCSILogicalUnit
Listen on both IPv4 and IPv6 if IPv6 is available.
targetcli listens to IPv6 as well as IPv4 if you delete the IPv4 listener address and replace it with the IPv6 equivalent, as explained here:
http://atodorov.org/blog/2015/04/08/how-to-configure-targetcli-to-listen-on-ipv4-and-ipv6/
=> iSCSILogicalUnit: lio-t IPv6-support

heartbeat/pgsql
Hi Dejan,
Hi All,
This is a repost of next pullrequest.
* https://github.com/ClusterLabs/resource-agents/pull/928
From the next release of Pacemaker, user and RA cannot appoint INFINTIY by crm_failcount command.
* https://github.com/ClusterLabs/pacemaker/commit/95db10602e8f646eefed335414e40a994498cafd
I abolish the use of crm_failcount.
By this correction, crm_resource -U(--clear) is necessary for restoration from trouble.
Best Regards,
=> Mid: pgsql: Change to crm_resource.

heartbeat/iSCSILogicalUnit, heartbeat/iSCSITarget
targetcli is not concurrent-safe. Using iscsi resources in different groups and shutting down a node causes race conditions.
=> targetcli lockfile

heartbeat/galera
Since MariaDB/server@8fcdd6b0ecbb966f4479856efe93a963a7a422f7,
mysqld_safe relies on a helper subprocess to write into log files.
This new logging mechanism expects log file to be writable by the
user configured to run mysqld.
Fix the generation of temporary log file accordingly.
=> galera: fix permission of temporary log file for mariadb 10.1.21+

heartbeat/galera
The resource agent selects the first node to go into Master state
based on the biggest commit version found on each node. If case no
data were written yet into the galera cluster, the current node is
selected as a "fallback" node to bootstrap the cluster.
The way the "fallback" node is selected is wrong because every node
takes a different decision, and this ultimately yields to 3
single-node galera clusters being started. To fix that, let the
"fallback" node be the last one in the wsrep_cluster_address, so that
the selection algorithm yields coherent results across nodes.
=> galera: fix the first bootstrap when cluster has no data

heartbeat/clvm
Remove reload-action as it's announced, but not available in the resource agent.
Decided to remove it as some settings require a restart, while others does not, so it's better to keep it consistent, as it's possible to do the reload changes yourself while unmanage'ing the resource.
=> clvm: remove reload action from metadata

heartbeat/rabbitmq-cluster
This was first observed via
https://bugzilla.redhat.com/show_bug.cgi?id=1435982. Due to the way
the resource agent looks for attrd entries, it will filter out any
node which does not have the @crmd=online attribute. This is the
case for pacemaker-remote nodes. To fix this we chose the more
conservative approach and only do an additional query when the first
one returned no entries. Note that this issue exhibits itself
when 'pcs status' reports rabbitmq started on a bunch of nodes:
Clone Set: rabbitmq-clone [rabbitmq]
Started: [ overcloud-rabbit-0 overcloud-rabbit-1 overcloud-rabbit-2
But the cluster_status command returns a single node:
[root@overcloud-rabbit-1 ~]# rabbitmqctl cluster_status
Cluster status of node 'rabbit@overcloud-rabbit-1' ... …
=> Allow the rabbitmq cluster to work on pacemaker remote nodes

heartbeat/named
The `named` resources agent only suppports options for `named`, but no [`rndc` options](https://ftp.isc.org/isc/bind9/cur/9.11/doc/arm/man.rndc.html).
I needed these changes to support multiple instances.
The `rndc` & `rndc-confgen` options are not identical, so the options configured for the resource are only used for the `rndc` commands.
=> Add support for rndc options in named resource agent.

heartbeat/pgsql
This will fix a bug where pgsql resource agent can't switch a node from sync to async mode because of wrong check.
Bug introduced in commit 6e91193
=> pgsql: fix regex in set async mode

heartbeat/galera
When option cluster_host_map is in use, it is assumed that galera node
names map to pacemaker node names _because_ those galera names are not
part of the pacemaker cluster in the first place.
This is not always the case (e.g. when using pacemaker bundles), so
fix accordingly.
=> galera: fix master target during promotion with cluster_host_map

heartbeat/IPaddr2
This change allows setting the preferred_lft option when creating an
IPv6 address. This can be used to ensure that the created IP address
will not be used as a source address for routing.
=> IPaddr2: add option for specifying IPv6's preferred_lft

heartbeat/db2
"db2pd -hadr" output changed in DB2 V98.
Reference: search for "In DB2 V97 and earlier releases, the output is like:" at: https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/DB2HADR/page/HADR%20monitoring
=> DB2: fix HADR support for DB2 V98+

heartbeat/ocf-shellfuncs.in
When calling `ocf_run` people expect that the function returns with the
exit status of the subprocess. In case of 0 exit code we returned
$OCF_SUCCESS which is 0 as well, but that doesn't read well. Refactoring
the return statements, so it is evident that the function always returns
with the exit code of the subprocess.
=> Refactor ocf-shellfuncs.in/ocf_run

heartbeat/SAPInstance
* `IS_ERS`
If `IS_ERS` is true, mark a per cluster attribute for a
specific ASCS/ERS pair describing which node is the
best place to failover a failed ASCS.
=> Medium: SAPInstance: Add IS_ERS parameter (bsc#1036486)

heartbeat/Raid1
=> Low: Raid1: Clean up spelling and whitespace

heartbeat/LVM
--cache is not available for LVM 1.x.
=> LVM: use vgscan --cache to update metadata during start/relocate

heartbeat/ocf-shellfuncs.in
Comment on this function says letters are ignored, but that was not the case. 
For example: 1.1.14-8.el6_8.1
=> Make ocf_is_ver() handle dist. specific versions

heartbeat/exportfs
Otherwise, it would be possible to circumvent the handling logic in
multiple ways, at the very least:
a. inject new (and potentionally unchecked as in standard flow)
export options through fsid parameter
b. accidentally make sed expression intended to override
fsid option present in export options with explicitly
provided fsid invalid if this explicit input contains
a character finalizing the sed substutition command
c. allow for repeated fsid specification in the resulting
export options, possibly verging on undefined (implementation
specific) behavior, because of matching only numerical fsid
already existing in options
Because in standard Linux implementation of NFS exports, there
is no strict restriction on string reprezentation of UUID data
type[*], solution on the resource-agents' …
=> Low: exportfs: check fsid parameter for not containing a comma

heartbeat/rabbitmq-cluster
Unfortunately we introduced a regression with commit
1f57e26816d8148e0c77ff7573457b8d2599bf8b. This patch addresses it and
fixes #982.
Thanks @seabres for the heads up.
=> [rabbitmq] Typo fix

rgmanager/src/resources/Makefile.am
It fails to find fs.sh.in when srddir and builddir are not the same:
make[5]: Entering directory '/path/to/builddir/rgmanager/src/resources'
cat fs.sh.in | sed \
-e 's#@''LOGDIR@#/var/log/cluster#g' \
> fs.sh.out
cat: fs.sh.in: No such file or directorychmod +x fs.sh.out
mv fs.sh.out fs.sh
Add abs_srcdir to fix this.
Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
=> fs.sh: fix builds when srcdir and builddir are seperated

heartbeat/rabbitmq-cluster
fix a small typo which causes errors in corosync.log e.g.
Jun 08 09:00:14 [6504] overcloud-controller-1.localdomain       lrmd:   notice: operation_finished:     rabbitmq_start_0:7504:stderr [ Error: syntax error before: ')' ]
=> rabbitmq-cluster: typo fix

Makefile.am, configure.ac, heartbeat/LVM, heartbeat/clvm, heartbeat/ocf-shellfuncs.in, resource-agents.spec.in, systemd/Makefile.am, systemd/resource-agents-deps.target
clvmd and LVM will create drop-ins on start to avoid nodes being fence during shutdown or reboot.
=> systemd: add resource-agents-deps target

heartbeat/iSCSILogicalUnit
Fixes #610 
Ideally I'd make it work for all iSCSI subsystems that can support them, but that's a bit beyond the time I'm currently able spend on.
=> Add support for LIO-T SCSI tpu,3pc and caw emulation attributes

heartbeat/mysql
Many MySQL system variables include "read_only" in their names. Use a
stricter query in get_read_only() to ensure that the value of read_only
is obtained, not innodb_read_only, tx_read_only, or some other
similarly-named variable.
=> Properly Detect read_only State

heartbeat/mysql
…ing master scores to -1 in certain conditions.
```
Consider the following scenario:
- crm got mysql master slave resource configured without providing check_level and test_table in the config
- crm is put into maintenance mode
- mysql replication is adjusted automatically or by hand
- crm is restarted on all nodes
- crm resources are reprobed
- crm is put into live mode
- at this point all nodes are working as expected but NONE of them got any master-mysql score set thus defaulting to -1. monitor of the resource never called crm_master.
- master fails
- crm will refuse to elect any slaves with the following error
failednode.com pengine: debug: master_color: mysql:0 master score: -1
When ms_mysql resource is configured master-mysql attribute/score for each node is not set by default thus …
```
=> Medium: mysql: Correct master score after maintenance mode

heartbeat/anything
- Start should return OCF_SUCCESS only if monitor suceeds
- Allow multiple instance of the resource with the same binfile (pidfile will be unique)
- Attempt to fix missing PID directory before starting
=> anything: minor fixes and enhancements

heartbeat/portblock
Dont log output from dd during monitor. E.g. "vip1_unblock_monitor_10000:16295:stderr [ 0+0 records in ]"
=> portblock: dont log dd "0+0 records in/out"

heartbeat/Raid1
For the mddev name, the function raid1_monitor_one()
should parse whether or not the $mddev is a symlink,
because the symlink name wouldn't show in /proc/mdstat
and result in "raid1_monitor_one()" returns failure.
=> Medium: Raid1: Handle case when mddev is a symlink

heartbeat/sg_persist
bsc#1048288
Tested on local cluster, happens only when in probe monitor operations.
=> Low: sg_persist: Read empty value when when no attribute exists

heartbeat/sapdb.sh
Adding hdbnameserver to the list of monitor services for HANA databases (dbtype HDB/hdb). The goal is to change the default to address older and newer HANA versions. In newer HANA versions the hdbindexserver is typically not listed as an own service.
=> Add hdbnameserver to monitor services

heartbeat/kamailio
- BUGFIX: Adding support for kamailio 5.X. Kamctl now reports uptime in format up_since, therefore monitor command needs to be updated
- Enhancement: Adding possibility to provide extra parameters in kamailio config files. This is needed in advanced scenarios, where TLS, memory options, etc. are needed.
=> kamailio: fixes and enhancements for v5.0

heartbeat/VirtualDomain
The `remote_user` attribute allows to specify a username that might be useful if you want to use a different username then root when using `qemu+ssh://` transport and restrict virsh access to a non-root user. (if root login is not permitted)
The `remote_network_suffix` attribute is similar to the `migration_network_suffix` attribute and modifies the remoteuri if the virsh signaling should be moved to a different network.
Example: Move virsh control and migration traffic (if combined with `migration_network_suffix`) to a more reliable network (f.e. crosslink bonding) and allow live migration while the main network is down (this is where the virsh connection would fail before the migration could even begin).
=> VirtualDomain: new attributes migrateuri, remoteuri, migration_user 

heartbeat/Route
Make the address family for routes configurable. This is required because it is not always possible to auto-detect the correct family, eg 'ip route add default eth0' is valid for both IPv4 and IPv6.
Falls back to the old (fallible) behaviour when not specified.
Fixes #996
=> Route: Configurable address family

heartbeat/Makefile.am, heartbeat/aws-vpc-route53
This agent changes a private zone Route 53 agent to
the appropriate IP address. This agent has been
developed in collaboration of SUSE and Amazon/AWS.
=> High: aws-vpc-route53: Add agent for AWS Route 53 (fate#322781)

heartbeat/pgsql
You can now add new nodes to the cluster and they will be automatically included in the resource management.
Allowing to specify parameter node_list in the resource creation to keep compatibility with older version.
changes:
- node_list parameter is now optional: if not specified nodes list is asked to cluster itself
- replication slots are created on master during promotion rather than on all nodes during resource's starting
- RA only use qualified replication slot
=> pgsql: allow dynamic membership

heartbeat/VirtualDomain
This commit allows operators to define virsh shutdown --mode in case traditional 'virsh shutdown' does not work.
virsh 3.5.0 supports one of the following --mode parameters - acpi|agent|initctl|signal|paravirt
By default shutdown_mode is empty and --mode is passed on the command line only in case is set
=> VirtualDomain - virsh shutgdown shutdown_mode support 

heartbeat/ocf-shellfuncs.in
When monitoring a pgsql database using `ocf:heartbeat:pgsql`,
each monitor produces two empty INFO messages in the ha logfile.
This is caused by a broken ocf_run in
`/usr/lib/ocf/lib/heartbeat/ocf-shellfuncs` which runs:
```
output=`echo "$output" | tr -s ' \t\r\n' ' '`
```
This causes output always being `' '`, even if the called
command has no output.
The following two tests for `! -z "$output"` are broken
and causes these empty messages to appear.
Proposed fix is to only run the tr command if `$output`
actually has content.
=> Low: ocf-shellfuncs: Avoid printing empty INFO messages (bsc#1053621)

heartbeat/ocf-shellfuncs.in
This change improves locking by ocf_take_lock(). It uses mkdir(1)
to prevent two instances from creating the same directory (named
by the lock).
The major difficulty is to prevent a race when a stale lock is
discovered. If two processes try to remove the stale lock at
about the same time, the one which runs slightly later can remove
the lock which just got created by the one which run slightly
earlier. The probability of this race is significantly reduced by
testing for stale lock twice with a random sleep in between.
Though this change does not exclude a race entirely, it makes it
extremely improbable. In addition, stale locks are result of only
abnormal circumstances and occur seldom.
The function providing random numbers has been modified to use
either /dev/urandom or awk (with the …
=> Medium: ocf-shellfuncs: improve locking (ocf_take_lock)

heartbeat/Makefile.am, heartbeat/lvmlockd
"lvmlockd" is a pretty new feature from LVM2 project.
It plays the same role as "clvmd" whose resource agent
is "clvm", but with much more proper design. The primary
benefit of "lvmlockd" is that it supports two lock
managers: dlm and sanlock. Refer to lvmlockd.8 for more
information.
This new agent only aim to support "dlm + lvmlockd",
because "sanlock" lock mananger plugin is suggested
to be used in scenario where HA clster softwares, i.e.
corosync/pacemaker/dlm are not already being needed/used.
Signed-off-by: Eric Ren <zren@suse.com>
=> lvmlockd: add resource agent for lvmlockd daemon

heartbeat/galera
Under certain circumstances $OCF_RESOURCE_INSTANCE as passed to the
resource agent contains and instance number (e.g. "galera:0"). This
happens e.g. when using "crm_resource --force-stop/--force-start". In
those cases "master_exists()" doesn't work correctly.
Use $INSTANCE_ATTR_NAME which is set in "mysql-common.sh", based on
$OCF_RESOURCE_INSTANCE with the instance number stripped.
=> galera: Fix instance name in master_exists()

heartbeat/galera
With version 3.19 galera introduced the "safe_to_bootstrap" flag to
the grastate.dat file [1]. When a cluster is shutdown cleanup, the last
not to shutdown gets this flag set to 1. (All other get a 0).
This commit enhances the galera resource agent to make use of that flag
when selecting an appropriate node for bootstrapping the cluster.  When
any of the cluster nodes has the "safe_to_bootstrap" flag set to 1, that
node is immediately selected as the boostrap node of the cluster.
When all nodes have safe_to_bootstrap=0 or the flag is not present the
current bootstrap behaviour mostly unchanged. We just set
"safe_to_bootstrap" to 1 in grastate.dat on the selected bootstrap node
to a allow for galera to start, as outlined in the galera documentation
[2].
Fixes: #915
[1] …
=> galera: Honor "safe_to_bootstrap" flag in grastate.dat

heartbeat/rabbitmq-cluster
We're using $RMQ_CTL instead of a direct rabbitmqctl invocation almost everywhere. Let's do it everywhere - for the sake of consistency.
=> rabbitmq: Use RMQ_CTL var everywhere instead of rabbitmqctl

heartbeat/galera, heartbeat/ocf-shellfuncs.in, heartbeat/rabbitmq-cluster, heartbeat/redis
This PR is split in two commits: the first one introduces the
shell function attribute_target() and the second one makes
redis, rabbitmq and galera use this new function.
Note that this function has simply no effect when this is run
against a pacemaker version that does not yet have the corresponding
changes for the container-attribute-target meta attribute.
=> Introduce the attribute_target function

heartbeat/docker
Docker 1.12 introduced native health checks. This PR adds code to optionally let this resource agent query docker for the container's health status when monitoring the container.
=> Feature: adding docker-native healthcheck query to docker

heartbeat/LVM-activate, heartbeat/Makefile.am, heartbeat/lvmlockd
Hi all,
The LVM-activate RA supports 4 activation mode: lvmlockd, clvmd,
systemID and lvm tag (hosttag?). I have tested them one by one on
my two-node pacemaker cluster with shared disks. But, I didn't stack
filesystem or other service on top of LVM yet. The resource agents
I tried variant combinations of them are:
controld (dlm), clvm, LVM, lvmlockd and LVM-activate. So far, they
works well for me. There were several problems during working on this,
but we (David and me) have solved/worked around them. Thanks David's
support!
Of course, there are still some potential issues to improve. I marked
them with "TODO" comments in the code.
One thing still not clear to me is about the "tagged-based" exclusive
activation. The old LVM RA just uses normal tag feature and activation/
volume_list to …
=> Request for review of LVM-activate RA

heartbeat/LVM-activate
Edit and move comments regarding usage from the file header into the long description, so that they are visible in user tools.
=> Low: LVM-activate: Move notes from comment to long description

heartbeat/LVM
Reverts ClusterLabs/resource-agents#980
Reverting due to --cache failing on older 2.x when lvmetad isnt running.
=> Revert "LVM: use vgscan --cache to update metadata during start/relocate"

heartbeat/galera
While running, a galera node keeps track of the last known state of
the cluster in a temporary file gvwstate.dat. This file is normally
deleted once a node is shutdown gracefully.
Some ungraceful shutdowns can leave an empty gvwstate.dat on
disk. This will prevent galera to join the cluster if it is
configured to attempt PC recovery. Removing that file makes the
node fall back to the normal, unoptimized joining process next
time it is restarted.
=> galera: recover from empty gvwstate.dat

resource-agents.spec.in
The path of the command that made this modification seems to be different from the path of the command included in the package provided with RHEL(CENT)7.
Therefore, packages are not automatically installed using yum.
```
(snip)
Error: Package: resource-agents-4.0.1-1.el7.x86_64 (/resource-agents-4.0.1-1.el7.x86_64)
Requires: /sbin/fuser
Error: Package: resource-agents-4.0.1-1.el7.x86_64 (/resource-agents-4.0.1-1.el7.x86_64)
Requires: /sbin/mount.cifs
You could try using --skip-broken to work around the problem
You could try running: rpm -Va --nofiles --nodigest
```
An example is shown below.
```
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
* base: ftp.iij.ad.jp
* extras: centos.usonyx.net
* updates: centos.usonyx.net
No matches found
Loaded plugins: …
```
=> specfile: Changed some commands to the correct PATH used in rhel(centos) 7

heartbeat/apache
Hi All,
We propose two patches.
If a failure occurs while processing time-consuming accesses it will fail to determine apache's stop.
This takes 9 seconds to stop apache, but apache RA is due to the short wait time.
- https://svn.apache.org/repos/asf/httpd/sandbox/replacelimit/server/mpm_unix.c
Also, there is no point in repeatedly sending a TERM signal in a loop.
Apparently, this problem seems to have entered with the next correction.
- https://github.com/ClusterLabs/resource-agents/commit/62d35a05abb18db03255df519bceaaf98c3f5c0f#diff-c43424e68c05e396a15f6c9b257b36af
Also, the signnal_child process may terminate the apache process at the end.
Run the stop determination last, and correct it to correctly execute apache process stop.
We would like to include this fix in agents-4.1.0 if …
=> Mid: apache: Change stop loop and move stop judgment.

heartbeat/db2
... also fixed OCF_GENERIC_ERR (non-existing return code).
=> db2: fix HADR promote when master failed

heartbeat/ocf-shellfuncs.in
For bundles, various resource agents now use ocf_attribute_target to
get the name of the pacemaker node to store attributes on.
If a recent version of the resource agent is being run on a pacemaker
version which does not support bundles, ocf_attribute_target will
return an empty string as hostname.
Provide a fallback path so the resource agent gets a valid name when
the resource is not containerized.
=> Fix fallback name for ocf_attribute_target

heartbeat/oracle
after modify users on oracle, the alter user not works.
This is the error:
ERROR: sqlplus output: alter user MONRHCS profile 'OCFMONPROFILE'#012*#012ERRORE alla riga 1:#012ORA-00931: identificativo mancante( DEFAULT )
The corrrect query have not the '
https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_4003.htm
=> Fix alter user syntax for set_mon_user_profile

heartbeat/CTDB
When upgrading from Red Hat 7.3 to 7.4 the script stated that the location of the
configuration file had moved from /etc/sysconfig/ctdb to /etc/ctdb/ctdbd.conf.
=> CTDB: Add new possible location for CTDB_SYSCONFIG

heartbeat/IPsrcaddr
`ifconfig` is deprecated on Linuxes, so only check for it where it is actually used.
=> Low: IPsrcaddr: Only check for ifconfig on BSD/solaris

heartbeat/CTDB
Keep it only if we find it in the original smb.conf file and change the default
to the non-deprecated "idmap config * : backend =" format.
=> CTDB: Cope with deprecated "idmap backend" smb.conf option

.travis.yml, doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/lxd-info, heartbeat/machine-info
@oalbrigt Hm, noticed that something isn't quite working with the CI: The agent name was typoed as LXCInfo in `doc/man/Makefile.am` but the CI check still passed. Will need to investigate.
=> Rename LXDInfo to lxd-info and MachineInfo to machine-info

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/README.mariadb.md, heartbeat/mariadb
This is a fork of the mysql resource-agent for use with MariaDB
with GTID support. This simplifies a number of steps in failover
scenarios as slaves no longer require notification of the log
positions in the master.
This GTID could in theory have been integrated into the mysql
agent, but as MariaDB and MySQL are diverging it seems wise
to likewise fork the resource-agents.
=> Implement GTID based MariaDB Master/Slave resource-agent

heartbeat/NodeUtilization, heartbeat/Xen, heartbeat/db2, heartbeat/galera, heartbeat/redis, heartbeat/vmware, tools/sfex_daemon.c
I didn't find any resource agents use the CLI options lately *dropped* from pacemaker-2.0 branch. By the opportunity I just replaced some of the deprecated ones.
=> Replace deprecated CLI options

heartbeat/tomcat
"--force" is invalid option for stop. it should be "-force".
=> Low: tomcat: Fix invalid stop option

heartbeat/redis
Add parameters in the resource agent to assign specific redis port to
each pacemaker node. When redis slave wants to connect to a redis
master, it will instead connect to a tunnel host, on the port assigned
to the targeted redis master.
This makes it possible for redis replication traffic to go through
pre-existing tunnels. This can be used to encrypt such traffic.
=> redis: add support for tunneling replication traffic

heartbeat/Raid1
The following sequence of events was observed in the wild:
```
16:19:04.379377+01:00 Raid1(rsc_Raid1_md7)[25734]: INFO: Stopping array /dev/md7
16:19:04.389490+01:00 kernel: [12955.559495] md7: detected capacity change from 429496664064 to 0
16:19:04.389499+01:00 kernel: [12955.559513] md: md7 stopped.
16:19:04.511817+01:00 Raid1(rsc_Raid1_md7)[25734]: ERROR: mdadm failed on /dev/md7.
16:19:04.520194+01:00 Raid1(rsc_Raid1_md7)[25734]: ERROR: RAID /dev/md7 still active after stop command!
```
As pointed by @neilbrown, the `-W` and `--wait-clean` flags are ignored (when they come *after* device) and useless as `mdadm --stop` only returns when the device is stopped.
The false positive is a transient device that may be created for short periods when the removal uevent is being processed by …
=> Fix raid1 stop detection

rgmanager/src/resources/nfsserver.sh
I noticed servers without selinux installed get spammed in the messages log by the monitor operation output of that command:
e.g.
lrmd[]:   notice: operation_finished: nfs-server_monitor_10000:6025:stderr [ /usr/lib/ocf/resource.d/heartbeat/nfsserver: line 183: selinuxenabled: command not found ]
=> redirect standard output/error of selinuxenabled

heartbeat/pgsql
Quote grep regexp to prevent possible shell expansion and
fix bashism warning:
possible bashism in pgsql line 1949 ([^] should be [!]):
echo "$OCF_RESKEY_replication_slot_name" | grep -q -e [^a-z0-9_]
=> pgsql: fix possible bashism

doc/dev-guides/ra-dev-guide.asc
It fails with an error if an user wrote an RA as the examples verbatim.
I believe that it's pretty obvious so I'm going to merge it now.
=> doc: RA dev guide: fix unnecessary quotations in examples

heartbeat/LVM, heartbeat/VirtualDomain, heartbeat/clvm, heartbeat/ocf-shellfuncs.in, heartbeat/tomcat
There are three actors in sum controlling the VMs:
- pacemaker/VirtualDomain RA
- issuing cluster resource operations,
- libvirtd
- executing the given commands,
- systemd and systemd-machined
- manages scope units of running VMs.
During shutdown both libvirtd and systemd-machined termination runs
concurrently with pacemaker so it cannot properly communicate with
libvirtd and terminate the machines (e.g. stopped scope unit would turn
the VM off instead of migration that's usually intended in a HA
cluster).
We add ordering dependency both on libvirtd.service and
virt-guest-shutdown.target so that pacemaker is terminated *before* the
other mechanisms would stop the VMs. Thus it can invoke appropriate
resource action on the running VM.
In order the ordering against virt-guest-shutdown.target …
=> VirtualDomain: Properly migrate VMs on node shutdown (bsc#1074014)

heartbeat/pgsql
Database fails to start correctly if the stats_temp_directory
is specified in the configuration but does not exists.
=> pgsql: try to create stats_temp_directory

heartbeat/exportfs
This patch fixes the issue of the `exportfs` RA failing its monitor
operation if the `clientspec` matches either of two conditions:
- It includes a character class wildcard at the beginning or end of
the string.
Example:
`clientspec='[ab]-host.example.com'`
In this case, the leading square bracket is incorrectly stripped,
leaving `'ab]-host.example.com'`.
- It consists of an IPv6 network with a CIDR netmask.
Example:
`clientspec='[fe80::]/64'`
In this case, the closing square bracket is incorrectly left intact,
leaving `'fe80::]/64'`.
In either of these conditions, the `start` operation creates the export
successfully, but the `monitor` immediately fails when it does not find
the string it's looking for. Similarly, the `stop` operation succeeds but 
does not actually remove the export. …
=> Medium: exportfs: Fix square bracket stripping in clientspec

heartbeat/exportfs
In commit 64d392d412ce9e14d4b33a70cb2180890db15a36, I introduced some
inconsistent whitespace in the exportfs_monitor function. This patch
fixes it.
=> Low: exportfs: Fix inconsistent whitespace in exportfs_monitor

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/gcp-vpc-move-ip
Hello
This Resource Agent uses the GCP API to move a floating IP addresse within a GCP VPC by changing an entry in the routing table, as discussed in the [documentation](https://cloud.google.com/solutions/best-practices-floating-ip-addresses#option_4_failover_using_routes_api_calls).
This agent also configures the floating IP locally on the instance OS.
=> New RA that manages IP moving in GCP

configure.ac
The -Wcast-align parameter isnt used for arping in iputils, and from the below mails it seems to usually report false-positives.
https://lists.isc.org/pipermail/inn-workers/2011-August/017857.html
https://lists.isc.org/pipermail/inn-workers/2011-August/017861.html
=> send_arp: dont use "-Wcast-align" due to false-positive fail on ARM.

heartbeat/awseip, heartbeat/awsvip
Improved:
- High: fix allocation_id not found error
- Low: get secondary-private-ip more precisely
- Low: get network-id from meta-data directly
=> Low: Improve awsvip awseip

heartbeat/ocf-shellfuncs.in
Changes introduced in dd9f8d47ec0dbec067442db4e4461a72aab0585e leave
behind warning messages in logs.
Pacemaker/lrmd sets umask(0026) we override that for file creation in
RA and make new directories more carefully.
=> Low: VirtualDomain: fix warning messages in log

heartbeat/findif.sh
Without this patch findif fails to find NIC for IPv6 addresses with 128 netmask.
=> findif: improve IPv6 NIC detection

heartbeat/SAPInstance
For ENSA2 the S/4 HANA Enqueue Services 2 we need two strings to be
added to the default services list to be monitored: enq_server, enq_replicator.
=> Medium: SAPInstance: Add monitored services for ENSA2 (bsc#1092384)

heartbeat/SAPInstance
move logging when we detect missing binaries earlier to see that this was issue even during 'stop' action
=> SAPInstance improvements 2018/05 (1/4) - move logging in abnormal_end()

heartbeat/pgsql
When  the return value of `ocf_version_cmp()` is `2` the right `test` command does not match because the  `$?` is replaced to the result of left test  command.
As a result incorrect SQL statement (i.e. pg_last_xlog*) is selected and fail to promote with PostgreSQL 11 or later.
=> Medium: pgsql: Fix incorrect SQL is selected with PostgreSQL 11 or later

doc/dev-guides/ra-dev-guide.asc
Thanks to @helen-fornazier for pointing out our instructions needed an update in:
https://github.com/ClusterLabs/resource-agents/pull/1167
=> ra-dev-guide: update instructions for GitHub

heartbeat/IPaddr2
Hi All,
Correct the return value of IPaddr2.
This content corresponds to the next issue.
- https://github.com/ClusterLabs/resource-agents/issues/1163
Best Regards,
=> Mid: IPaddr2: Change return code.

heartbeat/galera, heartbeat/rabbitmq-cluster, heartbeat/redis.in
Starting with pacemaker-1.1.19 a "crm_node -n" call triggers
a CRM_OP_NODE_INFO cluster operation. If this is called
from a bundle with 1.1.19 code (or later) running on a 1.1.18
cluster, during a meta-data call we will get the following error in the
cluster logs:
Jul 14 11:35:27 [20041] controller-0 crmd: error: handle_request: Unexpected request (node-info) sent to non-DC node
Jul 14 11:35:27 [20041] controller-0 crmd: error: handle_request: Unexpected <create_request_adv origin="send_node_info_request" t="crmd" version="3.0.14" subt="request" reference="node-info-crm_node-1531568127-1" crm_task="node-info" crm_sys_to="crmd" crm_sys_from="e67698a2-6f50-45fc-b8de-423c94e11c99" acl_target="root" crm_user="root" src="controller-0"/>
By not calling ocf_attribute_target (which triggers a …
=> Do not call ocf_attribute_target in the meta-data function

heartbeat/gcp-vpc-move-vip.in
Don't list all the instances in the project, filter only the one we are
interested in.
=> gcp-vpc-move-vip.in: filter call to aggregatedList

heartbeat/SAPInstance
The reload method is needed to avoid resource restarts after a non-unique parameter has been changed. This is in special for interest of the MONITOR_SERVICES parameter.
=>  SAPInstance: implemeted reload method

heartbeat/findif.sh
...due to new "ip" printing an additional line without netmask for IPv4 "route list match".
=> findif: only match lines containing netmasks

heartbeat/SAPInstance
SAPInstance has been initially written for NetWeaver 6.x and 7.0. In these times SAP instances have had a START_xx profile and a <SID>_xx parameter profile. Beginning with SAP NetWeaver 7.1 or 7.2 SAP removed the START_xx profile and added the content to the <SID>_xx parameter profile.
Since that change the automated detection of the start-profile failed and each cluster needed to use
the parameter setting for START_PROFILE. 
The given patch re-implements the automated profile detection. While the START_xx profile is still preferred to be backward compatible, SAP installations without an outdated START_xx profile could
now be detected via the <SID>_xx profile.
=> SAPInstance: Improved SAP instance profile detection

heartbeat/rabbitmq-cluster
When a node tries to join an existing cluster, it fetches a node
list to try to connect from any of those running nodes.
If the nodes from this list become unavailable while we're joining
the cluster, the rabbitmq server will fail to get clustered and
make the start operation fail.
Give the resource a chance to start anyway by retrying the entire
start actions until it succeeds or until the start timeout is
reached and pacemaker stops the start operation.
Co-Authored-by: <michele@acksyn.org>
Suggested-by: <abeekhof@redhat.com>
=> rabbitmq-cluster: retry start when cluster join fails

heartbeat/aws-vpc-move-ip
When pinging the assigned address during initial monitor (probe) on one
node we may actually ping the reachable address when the resource is
running on another node. This yields false positive monitor result on
the pinging node. Avoid this by merely checking the assignment of the
address to an interface.
The patch is not tested, this is a RFC.
=> RFC: aws-vpc-move-ip: Use ip utility to check address

heartbeat/mysql
The DEBUG_LOG functionality built into the mysql agent
has temp race problems (see #1049), but it is also
deprecated by the ocf trace facility.
The simplest fix is to remove it.
=> Medium: mysql: Remove obsolete DEBUG_LOG functionality (bsc#1021689)

heartbeat/ipsec
This option makes brings up a fallback tunnel if the main tracked tunnel
goes down. This is useful for when there is a failover in the VIP (which
is our main tunnel), and then we need to establish a tunnel to the new
node that has the VIP.
The fallback mechanism is a little bit hacky, but it's the only way I
could get it to work... basically it's put up in a background process,
which will keep trying retry putting up the fallback node. Meanwhile,
the resource agent will keep doing its job and put up the main node on
the host that received the VIP. eventually, a retry on the original node
will bring up the fallback tunnel.
=> ipsec: Add tunnel fallback option

resource-agents.spec.in
...in conditional (there's no "fedora_version" macro akin
to "suse_version" convention, just mere "fedora"; introduced
with e2e76528).
Note that resource-agents got mentioned recently regarding Fedora
packaging affairs, in particular with respect to /bin/sed Requires[1].
[1] https://src.fedoraproject.org/rpms/redhat-rpm-config/pull-request/29#comment-12256
=> spec: fix some overkil path-based Requires, trailing whitespace, thinko

heartbeat/rabbitmq-cluster
If mnesia is not running (for example if `rabbitmqctl stop_app` has
been called, or the service has paused during partition due to the
pause_minority strategy) then the cluster_status command to
rabbitmqctl will read the cached cluster status from disk and the
command returns 0 even though the service isn't really running at all.
Instead, force the cluster status to be read from mnesia.  If mnesia
is not running due to the above or similar circumstances, the command
will catch that and properly fail the monitor action.
Resolves: RHBZ#1595753
=> rabbitmq-cluster: get cluster status from mnesia during monitor

heartbeat/Filesystem
Filesystem monitor operation fails when the `directory` attribute is a
symlink.
The monitor operation calls the `list_mounts` function, which cats
`/proc/mounts` if it exists, else cats `/etc/mtab` if it exists, else
runs the `mount` command. It then greps for `" $MOUNTPOINT "` in the
output, where `$MOUNTPOINT` is the value of the `directory` attribute.
`/proc/mounts`, `/etc/mtab`, and the `mount` command resolve symlinks
to their canonical targets. So while the monitor operation greps for
the symlink path (surrounded by spaces) as defined in the directory
attribute, the symlink will not be present in the `list_mounts` output.
Only the symlink's target will be present.
This patch uses `readlink -f $MOUNTPOINT` to resolve the symlink to its
canonical name before using it as a grep pattern …
=> Filesystem: Support symlink as mountpoint directory

heartbeat/aws-vpc-move-ip
The argument 4th to `ip` is passed with single quotes around which
cannot be parsed as valid IP address. Furthermore, we need to expand the
$OCF_RESKEY_ip for grep. This breaks correct detection of the assigned
address.
Fixes 7632a85bcf642b484df52a25dbffbfa0031421bc.
=> aws-vpc-move-ip: Fix broken shell quoting

heartbeat/pgsql
The check_log_file performs a -f test on the log file which is set to
/dev/null by default and it returns 1 for non-regular files.
=> pgsql: Avoid the change of /dev/null to postgres owner/group

heartbeat/aws-vpc-move-ip
1. Check the routing table also during the monitor probe action
2. Force text output during the awscli call
3. Includes support for the address parameter with backward compatibility purposes.
=> aws-vpc-move-ip: Fixes

heartbeat/Filesystem
Commit 2aa8015 added support to `Filesystem_status()` for mountpoints
that are symlinks. However, it missed two other places where `readlink`
calls should have been added to canonicalize symlinks.
=> Filesystem: Canonicalize mountpoint symlinks

heartbeat/LVM-activate
=> LVM-activate: return OCF_ERR_CONFIGURED for incorrect vg_access_mode

.gitignore, heartbeat/Squid.in, heartbeat/garbd, heartbeat/portblock
So netstat has been deprecated on Linux for a long time, but we still have a lot of agents that need it.
It should be possible to replace any use of netstat with ss.
These commits don't fix all of the uses, but a few.
=> Try to enable use of ss wherever netstat is used

heartbeat/Xen
Set resource utilization attributes in the monitor
action like it is done for KVM in VirtualDomain agent.
=> Xen: Set utilization for cpu and hv_memory

heartbeat/galera
It is present on all commands except a single 'crm_mon' invokation.
=> Use ${HA_SBIN_DIR} on all the command invokation

heartbeat/sg_persist.in
If a comp hardly poweroffed there are staled old registration keys on the scsi
device. On a poweron the module sg_persist recognizes them by the monitor-probe and
set itself state to the "slave" state without "start" action and thus
don't set ACT_MASTER_SCORE. And without it the comp can never be
"master". This patch is for fixing this. It add ACT_MASTER_SCORE or
remove ACT_MASTER_SCORE in the "monitor" if the "monitor" see that the
keys unexpectedly exists or absent, thus simulate normal behaviour of
the "start" or "stop".
=> Correctly pickup old keys (improved v 0.0.2)

heartbeat/Xen
If node utilization is also not set, resource might not
be able to start anywhere.
=> Xen: disable utilization autoset by default

heartbeat/LVM-activate
- read parameters for start/stop/monitor-actions
- fail during monitor-action when run with incorrect access_mode
=> LVM-activate: fixes

heartbeat/apache
Hi All,
The apache's monitor may cause "not runnnig" by graceful restart.
This is because apache shortens the contents of the PID file for a moment when rewriting the PID file at a short time.
It may change in the future, but the previous versions of apache are treated in the same way.
- httpd-2.2.15-39.el6/ server/log.c
-----------------------------------------------------------------------
771 AP_DECLARE(void) ap_log_pid(apr_pool_t *p, const char *filename)
772 {
773     apr_file_t *pid_file = NULL;
:
807     if ((rv = apr_file_open(&pid_file, fname,
808                             APR_WRITE | APR_CREATE | APR_TRUNCATE,
809                             APR_UREAD | APR_UWRITE | APR_GREAD | APR_WREAD, p))
810         != APR_SUCCESS) {
811         ap_log_error(APLOG_MARK, APLOG_ERR, rv, …
=> Mid: apache: Retry pid check.

heartbeat/redis.in
The reason for this is that newer kernels (we saw this on a 4.18 kernel)
can limit access to /proc/<pid>/{cwd,exe,root} and so pidof will fail to
identify the process when using the full path names.
This access limitation happens even with the root user:
()[root@ra1 /]$ ls -l /proc/32/ |grep redis-server
ls: cannot read symbolic link '/proc/32/cwd': Permission denied
ls: cannot read symbolic link '/proc/32/root': Permission denied
ls: cannot read symbolic link '/proc/32/exe': Permission denied
For this reason the 'pidof /usr/bin/redis-server' calls will fail
when running inside containers that have this kernel protection
mechanism.
We tested this change and successfuly obtained a running redis cluster:
podman container set: redis-bundle [192.168.222.1:5000/redis:latest]
Replica[0] …
=> Do not use the absolute path in redis' pidof calls

heartbeat/Dummy
The Dummy agent hasn't had the delay functionality for quite some time.
=> Dev: Dummy: Fix comment that has been incorrect since 2007

heartbeat/pgsql
A PostgreSQL instance can be promoted to master either with or without a
restart of the PostgreSQL service. When restart_on_promote=false
creation of replication slots works correctly, but with
restart_on_promote=true the replication slots are created upon promoting
the master (in pgsql_promote()) but they are deleted shortly afterwards
when PostgreSQL is restarted (in pgsql_real_start()).
This results in the slave node failing with an error indicating that it
cannot find the specified replication slot, because, indeed, no such
replication slot exists after it is deleted.
This change fixes that problem by moving the creation of replication
slots to a point in time *after* the PostgreSQL instance has been
promoted to master and thus after the service has been restarted if …
=> pgsql: create replication slots after promoting master

heartbeat/oracle
Hi All,
This PR was modified by Mr.Mori(@kskmori) and I performed the test.
(I should have put out this PR a long time ago, but I forgot.)
Since the clear_backmode parameter of Oracle RA corresponds only to lowercase letters, we fixed it.
Also, the current RA does not output the cause details when a startup error occurs in backupmode.
This fix makes it possible to guess that it was bakupmode because it will appear in the error log of ORA - 10873.
```
May 14 09:29:12 rh74-ora1 oracle(prmOracle)[27920]: ERROR: oracle test1 can not be opened: alter database open#012*#012ERROR at line 1:#012ORA-10873: file 1 needs to be either taken out of backup mode or media#012recovered#012ORA-01110: data file 1:#012'/u01/app/oracle/oradata/TEST1/datafile/o1_mf_system_fgz28zyo_.dbf' …
```
=> [Oracle] Modification of Oracle RA.

heartbeat/ocf.py
I'm not 100% sure this breaks Pacemaker, but it causes crmsh to warn about missing monitor action.
=> dev: ocf.py: depth is not a time parameter and shouldn't a suffix

heartbeat/ZFS
`zpool list -H -o health "$OCF_RESKEY_pool"` may hang on heavy load (e.g. snapshot send, please see https://github.com/zfsonlinux/zfs/issues/7331). 
Since ZFS version 0.7.10 status can be obtained without locks (https://github.com/zfsonlinux/zfs/pull/7563), use it when possible.
Signed-off-by: George Melikov <mail@gmelikov.ru>
=> ZFS agent: check status without locks when possible

heartbeat/pgsql
The pgsql resource of replication mode will cause an error if it is promoted again to the master node.
```
[root@hpdb0301 ~]# crm_mon -1 -Af
Stack: corosync
Current DC: hpdb0301 (version 1.1.19-c3c624ea3d) - partition with quorum
Last updated: Tue Oct 16 16:27:20 2018
Last change: Tue Oct 16 16:27:12 2018 by root via crm_attribute on hpdb0301
2 nodes configured
11 resources configured
Online: [ hpdb0301 hpdb0401 ]
(snip)
Master/Slave Set: msPostgresql [pgsql]
Masters: [ hpdb0301 ]
Slaves: [ hpdb0401 ]
(snip)
[root@hpdb0301 ~]# crm_resource --force-promote -r msPostgresql --force                                                                                                                                     
resource msPostgresql is running on: hpdb0301 Master
resource msPostgresql is …
```
=> Mid: pgsql: Fix to ignore Master's re-promote.

heartbeat/rabbitmq-cluster
It's possible for mnesia to still be running, but for mnesia to be
partitioned.  And it's also possible to get into this state without
pacemaker seeing the node go down so no corrective action is taken.
When monitoring, check the number of nodes that pacemaker thinks is
running, and compare to the number of nodes that mnesia thinks is
running.  If mnesia only sees a minority of the total nodes, fail it
so corrective action can be taken to rejoin the cluster.
This also adds a new function, rmq_app_running, which simply checks
whether the app is running or not and does not care about the
partition status.  This is now used instead of the full monitor in a
few places where we don't care about partition state.
Resolves: RHBZ#1639826
=> rabbitmq-cluster: fail monitor when node is in minority partition

heartbeat/ZFS
Signed-off-by: George Melikov <mail@gmelikov.ru>
Looks like many agent files have different indentations (tabs and spaces) per file and just wrong indentations. This PR is for ZFS only,
but I think it would be great to cleanup other files too (first example is https://github.com/ClusterLabs/resource-agents/blob/master/heartbeat/IPaddr2).
=> ZFS: cleanup different indentations

resource-agents.spec.in
Actually orthogonal to how buildroot (usually used also for building
source packages alone) looks like/which packages are always present.
In a container, for instance, may not be any systemd (and hence its
RPM macros) at all.
Still rather fragile but working "is systemd a native platform where
you build this SRPM" detecting macro borrowed from upstream pacemaker
spec (I happen to author there, for completeness and as a reminder,
please keep these snippets in sync if at all possible).
=> spec: fix broken reliance on systemd_requires defined in SRPM build time

doc/dev-guides/ra-dev-guide.asc
This tiny typo confused me for a few minutes. Thought I'd throw up a patch to prevent others from getting confused by the same.
=> Fix demote example log line.

heartbeat/rabbitmq-cluster
This regression was introduced in PR#1249 (cc23c55).  The stop action
was modified to use rmq_app_running in order to check the service
status, which allows for the following sequence of events:
- service is started, unclustered
- stop_app is called
- cluster_join is attempted and fails
- stop is called
Because stop_app was called, rmq_app_running returns $OCF_NOT_RUNNING
and the stop action is a no-op.  This means the erlang VM continues
running.
When the start action is attempted again, a new erlang VM is launched,
but this VM fails to boot because the old one is still running and is
registered with the same name (rabbit@nodename).
This adds a new function, rmq_node_alive, which does a simple eval to
test whether the erlang VM is up, independent of the rabbit app.  The
stop action now …
=> rabbitmq-cluster: fix regression in rmq_stop

heartbeat/ocf.py
role=Master / role=Slave is commonly used to define
different monitor actions when agent is promoted or
demoted.
=> Dev: ocf.py: Add support for role argument to actions

heartbeat/lxc.in
This adds an "use_lxc_stop" switch which enables stopping
the container using lxc-stop instead of kill -PWR.
This was tested on a two node pacemaker cluster with drbd.
I wonder why it isn't already used and if we could change it to the default stop action.
=> lxc: Add Support for lxc-stop

heartbeat/ocf-distro, heartbeat/tomcat
without this patch it falls back to running the command manually which fails due to missing PID-file.
The -e check might be a bit confusing, but it'll avoid issues if it's backported to older RHEL where it's setup with catalina.sh available.
=> tomcat: use systemd on newer RHEL where catalina.sh is unavailable

heartbeat/SAPDatabase
Exemplify the HANA Standalone usage and improves the Monitor Services
defaults documentation.
=> SAPDatabase: Improves the documentation about HANA usage

heartbeat/aws-vpc-move-ip
This is a proposed fix to avoid a race condition with "grep" while parsing the results from AWS CLI. 
Currently, "grep" will match for IPs that don't belong tho the cluster resource. For example, if your cluster resource IP address is "192.168.1.1", "grep" will match "192.168.1.1*" (192.168.1.1,10,11,...,111).
This could have been fixed by a simple "grep -w" but we (AWS) thought it is more elegant to directly use the API to query for the IP.
I also included a debug log line.
=> Enable --query flag in DescribeRouteTable API 

heartbeat/ocf-shellfuncs.in
There might be situations (e.g. bundles) where the HA_debug variable
is unset. It makes little sense to enable debug logging when the HA_debug env
variable is unset.
So let's skip debug logs when HA_debug is set to 0 or is unset.
Tested inside a bundle and observed that previously seen 'ocf_log debug'
calls are now correctly suppressed (w/ HA_debug being unset inside the
container)
Signed-off-by: Michele Baldessari <michele@acksyn.org>
=> Do not log at debug log level when HA_debug is unset

heartbeat/rabbitmq-cluster
Ensure that the attribute is removed at the end of the stop action.
Also if rmq_app_running or rmq_node_alive shows the service as down,
ensure the attribute is deleted as well.
Resolves: RHBZ#1656368
=> rabbitmq-cluster: better ensure node attributes are removed

heartbeat/aws-vpc-move-ip
Hello,
This pull request is to add support for multiple AWS VPC routing tables within a single aws-vpc-move-ip cluster resource as requested by some customers.
Design options were discussed with different people and the options considered were:
a) A single aws-vpc-move-ip resource with a multiple routing tables in `routing_tables` parameter
b) Multiple aws-vpc-move-ip resources but including a "dummy" flag to the ones that were only supposed to manipulate routing tables and not local IPs - basically an aws-vpc-move-ip resource for managing routing tables only
We decided to go with option "A", as it keeps the cluster configuration and topology the way it is today and only modifies a single configuration parameter. For example:
```
primitive res_AWS_IP ocf:suse:aws-vpc-move-ip \
params …
```
=> Add support for multiple VPC routing tables in routing_tables parameter

heartbeat/docker
The docker RA's stop operation doesn't behave properly in some cases.
1. It returns a false success code in case of an error response from
the daemon.
2. It fails at `remove_container()` if the container does not exist
but another docker object of the same name does exist.
In case #1, the `container_exists()` function returns the same exit code
(1) if the container is not found (an expected error) or if there is an
error response from the docker daemon (an unexpected error). These types
of errors should be handled differently.
In case #2, the `docker inspect` calls do not limit their search to
containers. So if a non-container object is found with a matching name,
the RA attempts to remove a container by that name. Such a container may
not exist.
This patch fixes these issues as follows: …
=> docker: Fix issues with stop operation

heartbeat/rabbitmq-cluster
On older rabbitmq versions, rabbitmqctl appends "...done." at the end
of the output.  However we expect eval without this extra output so it
can be used for further processing.  The -q option to rabbitmqctl
suppresses the extra output, so ensure we always pass that when
calling eval.
Resolves: RHBZ#1659072
=> rabbitmq-cluster: always use quiet flag for eval calls

heartbeat/LVM-activate
If activating one lvname at a time, vgname will not be unique.
=> LVM-activate: make vgname not unique

heartbeat/LVM-activate
When there are no devices in the system dmsetup outputs one line:
No devices found
=> LVM-activate: fix dmsetup check

heartbeat/pgsql
When you have a single postgresql cluster managed by corosync
and pacemaker you cannot have any further slaves either with
streaming or logical replication. This patch enables connecting
other postgresql servers as slaves to the cluster without breaking
or interfering with the running cluster.
Signed-off-by: Dimitar Ianakiev <dimitar.q@siteground.com>
=>  Added support for multiple slaves to pgsql.

heartbeat/azure-lb
Removing, as it's ["historical (deprecated) synonym for monitor"](https://github.com/ClusterLabs/resource-agents/blob/master/doc/dev-guides/ra-dev-guide.asc#actions) and it wasnt in the agent in the first place.
=> azure-lb: remove reference to status from usage

heartbeat/pgsql
Reverts ClusterLabs/resource-agents#1291
Upon further extensive testing we found a corner case where the replication is broken when a failed node joins the back cluster. Please revert until we find the root cause and provide a fix.
=> Revert " Added support for multiple slaves to pgsql."

heartbeat/CTDB.in
Based on how it's set in ctdbd_wrapper, which we dont use.
=> CTDB: add ctdb_max_open_files parameter

heartbeat/redis.in
In some versions of redis (starting with 4.0.10) we have commits [1] and
[2] which add a warning on stderr which will be printed out every single
time a monitor operation takes place:
foo pacemaker-remoted[57563]:  notice: redis_monitor_20000:1930:stderr
[ Warning: Using a password with '-a' option on the command line interface may not be safe. ]
Later on commit [3] (merged with 5.0rc4) was merged which added the option
'--no-auth-warning' to disable said warning since it broke a bunch of
scripts [4]. I tried to forcibly either try the command twice (first
with --no-auth-warning and then without in case of errors) but it is
impossible to distinguish between error due to missing param and other
errors.
So instead of inspecting the version of the redis-cli tool and do the following:
- >= …
=> redis: Filter warning from stderr when calling 'redis-cli -a'

heartbeat/Squid.in
New versions of Squid (e.g. 4.2) saves the PID of the parent process to the pidfile instead of the PID of the listener child process as it used.
=> Squid: fix pid file issue due to new Squid version saving the PID of the parent process instead of the listener child process

Makefile.am, configure.ac, resource-agents.spec.in
It corresponds to the https://github.com/ClusterLabs/resource-agents/issues/1292 that can not build and install on RHEL 6.
* https://github.com/ClusterLabs/resource-agents/commit/ba0d5e1aa919f8496f8846361314c5dcf2c90546 : fix the issue that AC_PYTHON_MODULE added in https://github.com/ClusterLabs/resource-agents/pull/1294 is not loaded.
* https://github.com/ClusterLabs/resource-agents/commit/edc3e6ba2374b86a1eb13b32529c84edd02b5d4f : in the environment of Python 2.6 or less, skip the build such as ```azure-events```, ```gcp-pd-move```, etc. that use [ocf.py which requires Python 2.7+](https://github.com/ClusterLabs/resource-agents/blob/v4.2.0/doc/dev-guides/writing-python-agents.md#introduction).
* https://github.com/ClusterLabs/resource-agents/commit/73cd7bbd331a5c10dff753a2483bc3382a2397 …
=> Support build and install on RHEL 6

heartbeat/IPaddr2
Simple implementation of network namespace support. Basically the script changes its own network namespace if configured. Then any commands run by the script inherit the namespace.
Just FYI, we've been using this since around the time this PR was created (now 7 months as of mid-June) on 15 different servers, with 255 total different VIPs, and have not had any issues with it.
=> add network namespace support to IPaddr2

heartbeat/rabbitmq-cluster
The command only runs on the bootstrap node and we actually are very
interested in the output of it, because if it failed we want to know
why. It produces zero extra output when successful so let's get some
debuggability for free here.
f
=> [rabbitmq] Stop redirecting all output to /dev/null in set_policy

heartbeat/IPsrcaddr
Also updated NETWORK to only return 1 match to avoid failing when there's more than 1 match.
=> IPsrcaddr: make proto optional to fix regression when used without NetworkManager

heartbeat/ethmonitor
This patch changes the '-f inet' parameter to '-f link' so that all
interfaces are listed correctly in the is_interface() function. Since
this changes output from 'ip' slightly, we also remove a trailing
semicolon from the interface name.
The is_interface() function in ethmonitor tries to match an interface
to a list obtained from the 'ip' tool. It lists interfaces using the
'inet' family, which omits interfaces that don't have an IP address
assigned:
$ ip -a -o -f inet addr show | cut -d ' ' -f2 | sort -u \
| grep -v '^ipsec[0-9][0-9]*$'
lo
lxdbr0
tun0
virbr0
wlp3s0
If the interface that we're looking for is e.g. a VLAN bridge that does
not have an IP address, it won't show up in the listing and
is_interface() will return false. If we list available interfaces by
link instead, we also …
=> ethmonitor: check if interface exists by link

tools/sfex_lib.c
Fixes a compiler warning. There's not going to be any discernable effect on the application because both fields are 256 byte long.
=> sfex_lib.c: restrict strncpy by size of target, not of source. Fixes gcc error/warning

heartbeat/ethmonitor
Commit 40d05029ce0b changed is_interface() to list by link instead of address. We need to adjust the grep filter for the new output format, else we'll miss interfaces.
Apologies for missing this previously. This commit should fix is_interface() to behave as expected for all interfaces:
$ ip -o -f link a | grep " lo "
$ ip -o -f link a | grep " lo:"
1: lo: <LOOPBACK,UP,LOWER_UP> ...
=> ethmonitor: fix is_interface() regression

heartbeat/LVM
Hi All,
We reviewed the return code of the start process of OCF resource agent in connection with the following Pacemaker fix.
- https://github.com/ClusterLabs/pacemaker/pull/1748
- https://bugs.clusterlabs.org/show_bug.cgi?id=5383
LVM start processing was not consistent with other resource agents.
It's not 'Must', but I think it's 'Better' to change the return code for consistency.
Best Regards,
=> Low: LVM: Change of return code when start fails.

heartbeat/aws-vpc-move-ip
In case that AWS VM is having more that one network interface the following command with fail:
```
hostname01:/usr/lib/ocf/resource.d/suse # /usr/bin/aws --profile cluster --output text ec2 replace-route --route-table-id rtb-1234a567812a34567 --destination-cidr-block 192.168.1.1/32 --instance-id i-1234567890b012345
An error occurred (InvalidInstanceID) when calling the ReplaceRoute operation: There are multiple interfaces attached to instance 'i-1234567890b012345'. Please specify an interface ID for the operation instead.
```
In such case the command should use `--network-interface-id` parameter.
The adjustment is using value `$OCF_RESKEY_interface` that is already passed down and used in the code to determine MAC address of given network interface and this value is subsequently used to …
=> aws-vpc-move-ip - fix for defect making update of route table fail in case VM has multiple network interfaces

heartbeat/galera
We've seen a case where one node in the cluster had safe_to_bootstrap as
1 in grastate.dat, but apparently the UUID and the last commit (or
seqno) were 00000000-0000-0000-0000-000000000000 and -1 -- which matches
a fresh state.
In that case, we do not want to use that node as a bootstrap node, as it
causes a risk of losing everything.
=> galera: Ignore safe_to_bootstrap in grastate.dat in some cases

heartbeat/CTDB.in
commit 4a31eb7 should handle a -VENDOR trailer
+ e.g. 4.0.0-VendorVersion
however when using the sed from 4a31eb7 on a version string with vendor trailer e.g.
echo "4.0.0-VendorVersion" | awk '{print $NF}' | sed "s/.?[[:alpha:]].*//"
yields
4.0.0-
after fix
echo "4.0.0rc1" | awk '{print $NF}' | sed "s/[-\.]\?[[:alpha:]].*//"
4.0.0
echo "4.0.0-VendorVersion" | awk '{print $NF}' | sed "s/[-\.]\?[[:alpha:]].*//"
4.0.0
echo "4.0.0.GIT.1a2b3c4d" | awk '{print $NF}' | sed "s/[-\.]\?[[:alpha:]].*//"
4.0.0
Fixes: https://github.com/ClusterLabs/resource-agents/issues/1333
Signed-off-by: Noel Power <noel.power@suse.com>
=> CTDB: fix version string with vendor trailer comparison

heartbeat/docker
Using the docker RA, when a docker resource is configured then the cluster reports the following error from all nodes without docker:
```
* docker-tutorial1_stop_0 on mgr 'unknown error' (1): call=253, status=complete, exitreason='/usr/lib/ocf/resource.d/heartbeat/docker:241: /usr/lib/ocf/resource.d/heartbeat/docker: docker: not found',
last-rc-change='Thu May 16 12:56:14 2019', queued=0ms, exec=35ms
```
This is caused by `container_exists` which does not catch this error when running `docker inspect`.
Other RAs (e.g.: mysql, jboss) fail more gracefully on nodes where the commands are not available.
This patch adds 2 more checks to the monitor action:
* Checks if the `docker` command is available on the node. If not, fails with `OCF_ERR_INSTALLED`
* Checks if the docker daemon is runnig …
=> Fails docker RA gracefully when command not found or daemon is not running

heartbeat/galera
There is one case in the RA which changes the grastate.dat file for
galera. Write a log message when the file is changed.
This is useful when trying to find out why "safe_to_bootstrap" was
set.
=> galera: Log message when changing content of grastate.dat file

heartbeat/galera
When using a custom "check_user" without a "check_password" *and* the
user has a .my.cnf file in its home directory, the monitoring fails
like:
Operation promote for galera:0 (ocf:heartbeat:galera) returned: 'unknown error' (1)
>  stderr: INFO: Node <d52-54-77-77-01-02> is bootstrapping the cluster
>  stderr: ERROR: MySQL is not running
>  stderr: INFO: Waiting on node <d52-54-77-77-01-01> to report database status before Master instances can start.
>  stderr: INFO: MySQL is not running
>  stderr: INFO: MySQL is not running
>  stderr: ERROR 1045 (28000): Access denied for user 'monitoring'@'localhost' (using password: YES)
>  stderr: ocf-exit-reason:Unable to retrieve wsrep_cluster_status, verify check_user 'monitoring' has permissions to view status
>  stderr: ocf-exit-reason:local node …
=> galera: Add "check_passwd_use_empty" parameter

heartbeat/openstack-cinder-volume, heartbeat/openstack-floating-ip, heartbeat/openstack-info
This PR:
* provides a better layout
* uses crm_node -n result instead of $HOSTNAME
* deals with API v3 (tenant / project)
I had some rebase problems (#1198). I have recreated the PR.
=> [openstack agents] Volume re-attaching, v3 API, get hostname from corosync

heartbeat/Filesystem
This corrects the problem reported in #1325.
The problem is that if readlink fails and the output is empty, it will be mistaken as umounted.
=> Low: Filesystem: Fix a problem umount is not executed in the event of a disk failure

heartbeat/Filesystem
I create 80 Filesystem resources in the my test environment and encountered the following problems.
- sometimes mount point remains after stop all Filesystem resources
- incorrect monitor error detected when  stop one of Filesystem resources
These problems are caused by corrupted mount list returned from list_mounts().
"grep -q " $MOUNTPOINT "" does not matches and missing mount point although the mount point exists.
- create many Filesystem resource(I create 80 resources)
- set "node-action-limit=80" and "batch-limit=80"
- stop all Filesystem resource using "crm node standby active-host"
Under the above conditions, issue occur about once every 100 times.
(It depends on the performance of the test environment)
Why list_mounts() returns corrupted mount list is that atomicity of read data …
=> Low: Filesystem: Fix missing mount point due to corrupted mount list

heartbeat/named
The `host` options can be used to set the timeout (`-W`) or number retries (`-R`) for example to make the monitor action more reliable.
On my systems the monitor actions fails every now and then due to timeouts:
```
Jun 12 08:18:48 resolver01 named(named1)[27366]: ERROR: named didn't answer properly for localhost.
Jun 12 08:18:48 resolver01 named(named1)[27366]: ERROR: Expected: 127.0.0.1.
Jun 12 08:18:48 resolver01 named(named1)[27366]: ERROR: Got: ;; connection timed out; no servers could be reached
```
This PR makes the monitor action more configurable.
=> Add support for host options in named resource agent.

heartbeat/pgsql
Currently, pgsql RA does not set an initial score for primary and hot standby in the prove operation.
This behavior cause following problems.
1. If primary PostgreSQL instance detected in the probe operation, then pgsql RA have no chance to set a master score "1000" because pgsql_promote() is not executed.
It cause unnecessary fail over in some situations. (E.g. restart Pacemaker in the maintenance mode)
2. If hot standby PostgreSQL instance detected in the probe operation, then control_slave_status() can't update master score for hot standby because master score for hot standby is null.
It cause lack of master score for hot standby in the "crm_mon -A". 
This patch aim to avoid above problems by setting an initial score for primary and hot standby in the prove operation.
=> Medium: pgsql: Set an initial score for primary and hot standby in the prove.

heartbeat/azure-events.in
Reduces the verbosity on the log when the RA has no events to process.
The messages can still be seen using the verbose parameter.
=> azure-events: change message log level for the RA non action messages

heartbeat/aws-vpc-route53.in
If AWS API returns an error for some reason (e.g. API unavailable or insufficient IAM rights), the stop function in aws-vpc-route53 resource agent will have a syntax error on line 254, because the ARECORD variable will be empty.
Adding quotes around the variables will prevent that. This is how the if condition is written in other places within the script e.g. in ec2ip_monitor() function.
=> aws-vpc-route53.in: Add missing quotes in ec2ip_stop()

heartbeat/aws-vpc-route53.in
This pull request is to add improvements to this agent's monitor function and general code cleanup.
Currently, the monitor function uses AWS CLI to call "list-resource-record-sets" AWS API call, and if the AWS CLI fails for any reason (ex.: throttling, network errors, etc) it may cause the cluster to failover because there is not exception handling for the AWS CLI commands.
Route53 API calls have a limit of five API calls / second per account [1] it is desirable to avoid doing API calls, so I added a "dig" DNS check and only in case of a DNS lookup failure from the "dig" DNS check the monitor function will fallback and try to execute the "list-resource-record-sets" API call for monitoring.
I also changed the way the EC2 instance's IP address it checked, instead of using a 3rd party script …
=> aws-vpc-route53 - Improvements on monitor function and general changes to the code

heartbeat/podman
Under heavy IO load, podman may be impacted and take a long time
to execute some actions. If that takes more than the default
20s container monitoring timeout, containers will restart unexpectedly.
Replace all IO-sensitive podman calls (inspect, exists...) by
equivalent "podman exec" calls, because the latter command seems
less prone to performance degradation under IO load.
With this commit, the resource agent now requires podman 1.0.2+,
because it relies on of two different patches [1,2] that improve
IO performance and enable to distinguish "container stopped"
"container doesn't exist" error codes.
Tested on an OpenStack environment with podman 1.0.2, with the
following scenario:
. regular start/stop/monitor operations
. probe operations (pcs resource cleanup/refresh)
. unmanage/manage …
=> podman: only use exec to manage container's lifecycle

heartbeat/ZFS
The VAR=(< filename) syntax does not work in all situations (i.e. not on debian 10), changing it to VAR=(cat filename) does work.
Found this problem because I am using debian 10, will create a debian bug report that points to this request.
=> changing bashism to generic solution

heartbeat/podman
When podman creates a container, it creates two additional systemd
scope files dynamically:
- libpod-conmon-<CONTAINERID>.scope - runs a conmon process that
tracks a container's pid1 into a dedicated pidfile.
- libpod-<CONTAINERID>.scope - created dynamically by runc,
for cgroups accounting
On shutdown, it can happen that systemd stops those scope early,
which in turn sends a SIGTERM to pacemaker-managed containers
before pacemaker has scheduled any stop operation. That
confuses the cluster and may break shutdown.
Add a new option in the resource-agent to inject additional
dependencies into the dynamically created scope files, so that
systemd is not allowed to stop scopes before the pacemaker
service itself is stopped.
When that option is enabled, the scopes look like:
c329819a1227 …
=> Generate addition drop-in dependencies for podman containers

heartbeat/Filesystem
=> Filesystem: don't call readlink on path if it does not exist

heartbeat/docker
This amends 5941b98140b09e39b4dc2ee155817b287ef32859 (Fails docker RA
gracefully when command not found). That commit checked for a pidfile
which tends to be less robust in the presence of stale pidfiles and
also adds a configuration option for the pidfile location which is
more churn than needed to simply check for a service availability.
Let's simply call 'docker version'. When that commands returns 1 the docker
daemon is not running and also return OCF_ERR_GENERIC instead of
OCF_NOT_RUNNING. This is a key point because if the docker daemon
is stopped and not running it can very well be that the containers
are still up (e.g. when you use live-restore in docker). In this
situation we want an explicit fence event to be triggered due to
the failure of stopping.
Not doing so would mean that …
=> Make the check for the docker daemon being up more robust

heartbeat/docker
In docker_stop() let's store the return code of docker_simple_status
otherwise the second branch of the elif risks reflecting the return
code of the previous operaiton and not of docker_simple_status()
Retested this with a bunch of stop/start commands on a rabbitmq bundle
and observed no issues.
This fixes a stop() regression introduced in
b7ae1bfbe7d393a9e9d993da3da35cc4d1bc9eb4 ("Make the check for the docker
daemon being up more robust")
Thanks to Kota Akatsuka for spotting it.
Signed-off-by: Michele Baldessari <michele@acksyn.org>
=> Fixup docker_stop condition on error

heartbeat/exportfs
Point out the standard of the format is aligned with `man exportfs`, and also point out the correct way to deal with the use case to export the same directory(-ies) to multiple subnets.
=> exportfs: doc clarification for clientspec format

heartbeat/ora-common.sh
Hi All,
If user specify the sid parameter of oracle / oralsnr incorrectly without specifying the OCF_RESKEY_home parameter, "sqlplus: required binary not installed" is displayed as an error message.
With this error, it is very difficult for the user to understand the sid mistake.
The following display of crm_mon is an example when the sid parameter is specified incorrectly.
```
Stack: corosync
Current DC: rh76-oracle2 (version 1.1.21-1.el7-f14e36f) - partition with quorum
Last updated: Mon Aug 19 11:07:03 2019
Last change: Mon Aug 19 11:06:46 2019 by root via cibadmin on rh76-oracle1
2 nodes configured
1 resource configured
Online: [ rh76-oracle1 rh76-oracle2 ]
No active resources
Node Attributes:
* Node rh76-oracle1:
* Node rh76-oracle2:
Migration Summary:
* Node rh76-oracle1:
prmOracle: …
```
=> Low: ora-common: Properly output message when sid parameter is invalid.

heartbeat/rabbitmq-cluster
See https://bugzilla.redhat.com/1744467#c1
Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>
=> rabbitmq-cluster: also restore users/perms/policies when starting in single node mode

heartbeat/nfsserver
> I found two critical actions in the script:
> - systemctl status nfs-server  (which also calls journalctl)
> - systemctl list-unit-files
source:
https://lists.clusterlabs.org/pipermail/developers/2019-September/002214.html
=> nfsserver: performance improvements for systemd enabled systems

heartbeat/redis.in
New commit with expanded reasoning in the commit message instead of
https://github.com/pokotilenko/resource-agents/commit/28207caf5e028ac99bb9df9053d4f815933114c9
=> fix master_is_active() erroneously reporting there is master when there is no

heartbeat/redis.in
This is more enhanced version of
https://github.com/pokotilenko/resource-agents/commit/cbd0cf2e2c37298b15e95d99e5c733c29430f09c
Introduced new redis_cli_features() function to set redis-cli features based on its version. This may be used in the future for other features checks.
Now this is used to choose optimal password passing method and warning filtering workaround:
>= 5.0.3: use environment variable
or >= 5.0.0: use --no-auth-warning
or >= 4.0.10: use warning filter
or: old behavior: pass password via arg and do not use warning filter
=> redis: consider redis-cli features to choose optimal password passing method and warning filtering workaround

heartbeat/nfsserver
Based on suggestion from @jpokorny in https://github.com/ClusterLabs/resource-agents/pull/1398#issuecomment-532152129
=> nfsserver: use "--no-legend" for systemctl "list-unit-files" calls

heartbeat/aws-vpc-route53.in
This pull request is to add general improvements to different parts of the code.
* **Increasing MYSECONDS time interval:** Changing from 8 seconds to 20 seconds to decrease the amount of ListResourceRecordSets API calls and decrease the change of Route53 API throttling from my observation and tests this will decrease the number of ListResourceRecordSets from 5-6 to 2-3 (50% reduction)
* **Changes in log level:** Making the agent a little more verbose - good for day-to-day troubleshooting
* **Improve API error handing on _update_record():** Previously I had included error handling on r53_monitor() function and now I'm adding the same handling to _update_record()
* **Strip empty line on AWSCLI output:** Cleanup from AWSCLI/API response to make the logging more readable
* **Fix potential …
=> aws-vpc-route53: Improvements and fixes

heartbeat/gcp-pd-move.in
gcp-pd-move use parameter 'OCF_RESKEY_stackdriver_logging', 
but  parameter 'stackdriver_logging' not exists in METADATA..
I will add parameter 'stackdriver_logging' !!
thank you.
=> gcp-pd-move: add parameter stackdriver_logging

configure.ac, heartbeat/LVM-activate
It needs to be called before validate attempts to look at the VG.
=> LVM-activate: move pvscan --cache to validate

heartbeat/apache
Permission to execute that file must be granted so as not to preclude
the happy case (also, hopefully, the respective "test" program
implementation is not naive about "uid=0 equals superprivileges" for
when the script is not owned by such user while there can be further
security domain constraints, such as a lack of "CAP_DAC_OVERRIDE"
on Linux [imposed, e.g., with SELinux]).
=> apache: testing to-execute-file for mere presence is not enough

heartbeat/NodeUtilization
Fix shell quoting in function `Host_Total_Memory()`. Missing quotes caused that if no Xen command (`xl` or `xm`) was found the function made a non-sense call to the `info` utility. This could have resulted in unexpected messages appearing in pacemaker logs. Example:
```
lrmd[3476]:   notice: prm_node_util_monitor_300000:3915:stderr [ info: Writing node (dir)Top... ]
lrmd[3476]:   notice: prm_node_util_monitor_300000:3915:stderr [ info: Cannot find node `(dir)GNU Free Documentation License'. ]
lrmd[3476]:   notice: prm_node_util_monitor_300000:3915:stderr [ info: Done. ]
```
The proposed patch also removes a warning about no Xen command being available. With the fixed quoting, if a NodeUtilization resource was configured to use the default `utilization_hv_memory=true` parameter but the Xen …
=> Low: NodeUtilization: Fix checking for Xen commands

heartbeat/mysql-common.sh
PID value is not captured correctly so the startup
fails with the wrong exit code.
Starting 'mysql' case 8 'check lib file':
Setting agent environment:    export OCF_RESKEY_CRM_meta_timeout=15000
Setting system environment:   chmod u-w /var/lib/mysql
Running agent:                ./mysql start
ERROR: The agent was hanging, killed it, maybe you damaged the agent or system's environment, see details below:
Oct 23 18:46:06 INFO: MySQL is not running
runuser: warning: cannot change directory to /nonexistent: No such file or directory
runuser: warning: cannot change directory to /nonexistent: No such file or directory
runuser: warning: cannot change directory to /nonexistent: No such file or directory
Oct 23 18:46:06 INFO: MySQL is not running
Oct 23 18:46:08 INFO: MySQL is not running
Oct 23 …
=> Low: mysql-common: fix startup check

heartbeat/iSCSILogicalUnit.in
- Added new variable liot_bstype to handle different backend storage engine for lio-t (targetcli), which allows better flexibility. Changed the targetcli commands accordingly.
- Changed the behaviour of lio-t when using explicit portal addresses other than 0.0.0.0, and IPv6 is in use. Now it will not remove existing IPv4 0.0.0.0 address (and fail) and then attempt to add ::0.
=> iSCSILogicalUnit.in fixes

heartbeat/MailTo
Wrong kind of braces used (expand to 0 or fail
to expand with dash as shell).
=> Low: MailTo: fix variable expansion

heartbeat/azure-lb
Socat was tested on SUSE and it works fine. To avoid the need to change the configuration we set socat to default on SUSE distributions.
=> azure-lb Set socat to default on SUSE distributions.

heartbeat/Filesystem
In the case a fresh filesystem is just created from another node on the
shared storage, is not visible yet. Then try partprobe to refresh
/dev/disk/by-uuid/* up to date.
Signed-off-by: Roger Zhou <zzhou@suse.com>
=> Filesystem: refresh UUID in the start phase

heartbeat/iSCSILogicalUnit.in
When using XenServer with multipath as iSCSI client for PCS, the lio-t module calculates the scsi_sn automatically, if not specified explicitly. The scsi_sn (saved in /sys/kernel/config/target/core/<backend>/<lun name>/wwn/vpd_unit_serial when targetcli defines the backend) is not maintained during failovers. Clients 'multipath' daemon might fail to re-identify the disks. XenServer is extremely vulnerable to this, because the wwn is kept in a file and explicitly used. Failover of a cluster iSCSIlogicalUnit to another node, and then reboot to XenServer host might lead to storage inaccessible. This was proven true, especially when multiple backend devices (and LUNs) are present in the same resource group.
The change added some note about it for the meta-data section of scsi_sn and added a …
=> iSCSI logical unit fix

heartbeat/IPaddr2, heartbeat/ocf-binaries.in
Reference:
https://lists.clusterlabs.org/pipermail/users/2019-December/026674.html
(thread also sketches a future ambition for a [presumably, to revert
the habit of a functional overloading] separate agent to use
"xt_cluster" extension/cluster match).
=> IPaddr2: ipt_CLUSTERIP "iptables" extension not "nft" backend compatible

ldirectord/ldirectord.in
```
IPVSADM(8):
-b, --sched-flags sched-flags
Set scheduler flags for this virtual server.  sched-flags is a comma-separated list of flags.  See  the  scheduler  descriptions  for
valid scheduler flags.
```
=> ldirectord: Support sched-flags

heartbeat/Filesystem
There is a race condition that partprobe might return before the UUID
symlink get created. Particularly, when the system has many devices, the
udev daemon could need visible time to process the udev event queue.
Hence, wait udev for a moment.
Filesystem RA's DEVICE parameter accepts "-U <uuid>" and "-L <label>" in
addition to "/dev/xxx". Let's add a new function
trigger_udev_rules_if_need() to accommodate them all.
Merry X'mas and Happy New Year!
=> Filesystem: respect udevd need time to create symlinks and also accomodate -U -L device

heartbeat/podman
Let's switch to the existing 'podman image exists' to determine if
an image is local to the machine or if it needs pulling.
Let's change this for a number of reasons:
- It simplifies the code greatly
- It makes everything work even when the image is prefixed with 'localhost/'
names which are not detected as local images
- It makes the code faster as we do not need to list all the images as
that is more expensive
Tested by running a couple of full containerized OpenStack deployments,
one with images tagged as 'localhost/foo/mysql:pcmklatest' and one
with a normal registry host prefix.
Co-Authored-By: Damien Ciabrini <dciabrin@redhat.com>
=> podman: simplify the code for checking if an image exists

heartbeat/rabbitmq-cluster
If the stop action fails, we want to remove the nodename from the crm
attribute.  Currently it is possible for the stop action to fail but
the rabbitmq server does actually stop.  This leaves the attribute
still present.  This means if the entire rabbitmq cluster is stopped,
it is not possible to start the cluster again because the first node
to start will think there is at least one other node running.  Then
the node tries to join an existing cluster instead of rebootstrapping
the cluster from a single node.
=> rabbitmq-cluster: ensure we delete nodename if stop action fails

heartbeat/LVM-activate
When LVM underlying devs disappear, eg iSCSI SAN disks suffer network
disconnect, the pvs/vgs/lvs won't show related PVs/VGs/LVs, but dm
devs won't disappear. This makes the lvm_status() doesn't work as
expect.
This patch uses simple & stupid method "read 1 byte from underlaying
dev" to detect abnormal underlying devices.
=> LVM-activate: verify vg or lv validity

heartbeat/redis.in
In redis RA fixes file status checks in `validate_all`
Closes #1446
=> redis: validate_all: fixes file status tests

heartbeat/SAPInstance
Clear out the $DIR_EXECUTABLE variable so we catch the situation when we
lose the directory with binaries after first sapinstance_init
invocation. The second sapinstance_init invocation will not detect it as
it will have already preset the $DIR_EXECUTABLE from previous run.
This may allow us running actions after second sapinstance_init
invocation that would be not run if we knew that we miss the needed
binaries.
This affect the following functions/operations:
- sapinstance_monitor_clone
- sapinstance_promote_clone
- sapinstance_demote_clone
This is limited to only Master/Slave resource and only when the
sapinstance_init is invoked multiple times during one operation.
=> SAPInstance improvements 2018/05 (4/4) - clear $DIR_EXECUTABLE variable between runs of sapinstance_init

heartbeat/pgsql
Changed:  "PostgreSQL is already Master. Don't execute promote."
=> Change 'alredy' to 'already'

heartbeat/lvmlockd
Patch to remove locking_type parameter from lvm.conf if you're upgrading to LVM > v2.03.
Suggested by @teigland.
=> lvmlockd: remove locking_type parameter from lvm.conf for LVM > v2.03

heartbeat/iSCSILogicalUnit.in
Failed with invalid if command because value was not set to default.
Rest of the changes are space and syntax cleanups.
=> iSCSILogicalUnit: fix default value for OCF_RESKEY_liot_bstype

heartbeat/aws-vpc-move-ip
When leveraged in Organizations, often times the profile executing commands will have to assume a role in order to access the route table (this is especially the case in a shared VPC model). Being able to optionally assume a role for route table api calls is advantageous to large organizations.
=> Allow user to specify role with which to query/update route table

heartbeat/Filesystem
Lustre client mounts have a device that looks like:
172.60.0.1@o2ib,172.60.0.2@o2ib:172.60.0.3@o2ib,172.60.0.4@o2ib:/fsname
Signed-off-by: Nathaniel Clark <nclark@whamcloud.com>
=> Filesystem: Add lustre as networked filesystem

heartbeat/ClusterMon, heartbeat/openstack-cinder-volume, heartbeat/sapdb-nosha.sh, rgmanager/src/resources/oradg.sh.in, tools/ocft/caselib.in
There are various problems with tmp-races. Some of them may be used for LPE.
This changes makes resource-agents safer.
=> Make secure tmp files

rgmanager/src/resources/oradg.sh.in, tools/ocft/drbd.linbit
* Change the drbd.linbit tmp file location to a more secure place. (https://github.com/ClusterLabs/resource-agents/issues/1049)
* Correct the stdout parameter from start to stop.
=> Fix audit issue with secure tmp file

heartbeat/galera
When check_passwd_use_empty option was introduced, it added a possibility
to connect to mysql explicitly using empty password, thus bypassing defaults
set in ~/.my.cnf.
However the the empty password set for MYSQL_OPTIONS_CHECK variable was wrong,
adding too many levels of escaping and ultimately failing when passed to mysql client.
This commit changes the password value in MYSQL_OPTIONS_CHECK so that it really
ends in passing the empty string.
Original PR here: https://github.com/ClusterLabs/resource-agents/pull/1330
=> galera: Fix value used for connecting with the empty password.

heartbeat/oracle
With static default credentials for a user is not safe
even for limited privilege. A local user may login to
the DB to do some attack by bugs or leaks. (https://github.com/ClusterLabs/resource-agents/issues/1049)
It is better to replace the automatic creation with
new user and leave the default password for legacy update.
Also an open issue discussion (#1030) for this.
=> Increase the security of monitor user in oracle

heartbeat/ZFS
In a case of multiple pools on the same server, the unique argument for
importforce will prevent a 2nd resource from being added with the following
message:
```
Error: Value 'true' of option 'importforce' is not unique across 'ocf:heartbeat:ZFS' resources.
```
=> ZFS: Importforce should not be a unique parameter.

heartbeat/gcp-vpc-move-route.in, heartbeat/gcp-vpc-move-vip.in
The underlying google api code cache discovery process
uses deprecated code. In order to avoid the usage of that
code and the related warning messages the cache usage is
disabled
=> gcp-vpc-move: Disable google api cache discovery

heartbeat/aws-vpc-route53.in
- use _default variables for all parameters
- reorganize actions to make it easier to find what you're looking for
- add ip parameter to specify whether to use local, public or a specific IP (e.g. secondary private IP)
=> aws-vpc-route53: improvements and new ip parameter

heartbeat/aws-vpc-move-ip, heartbeat/aws-vpc-route53.in
While testing the AWS resource agents, I ran into some problems where instead of using the OCF_RESKEY_awscli variable, the 'aws' command is just assumed to be in the path.  These patches fix this issue and make some other changes that help with consistency with other agents.
=> Replace aws command line with OCF_RESKEY_awscli property.

heartbeat/pgsql
The output of crm_mon has been changed since Pacemaker-2.0.3, so master/slave of pgsql doesn't work properly.
This fix corresponds to the crm_mon output of Pacemaker -2.0.3.
=> pgsql: support to crm_mon output for Pacemaker-2.0.3.

heartbeat/ocf.py
That method installed a root logger to be used with logging methods.
The root logger is a stream logger which sends output to stderr,
so every log data ended up in stderr as well
=> Eliminated logging.basicConfig()

heartbeat/rabbitmq-cluster
After we start the rabbitmq process we wait for the pid to show up
and then declare the server to be started successfully.
This wait is done via 'rabbitmqctl wait'. Now from
From https://www.rabbitmq.com/rabbitmqctl.8.html we have:
If the specified pidfile is not created or erlang node is not started
within --timeout the command will fail. Default timeout is 10 seconds.
This default of 10 seconds might not be enough in overloaded
environments. So what we want to do here is wait for as much time as
the start() operation allows us. So we wait for OCF_RESKEY_CRM_meta_timeout
minus 5 seconds. In the rare and non-sensical case that it is less than
10s we do not pass a timeout string at all to rabbitmqctl.
Co-Authored-By: John Eckersberg <jeckersb@redhat.com>
=> Increase the rabbitmqctl wait timeout during start()

heartbeat/azure-events.in
The locking in azure-events does not correctly handle some
failures.
If the metadata server is not recheable or has an error
handling the request, attr_globalPullState will never go
back to IDLE unless the administrator manually changes it.
> azure-events: ERROR: [Errno 104] Connection reset by peer
> lrmd[2734]: notice: rsc_azure-events_monitor_10000:113088:stderr [ ocf-exit-reason:[Errno 104] Connection reset by peer ]
=> azure-events: handle exceptions in urlopen

heartbeat/db2
...promote standby node when master node disappears (e.g. via fencing)
=> db2: HADR add STANDBY/REMOTE_CATCHUP_PENDING/DISCONNECTED to correctly

heartbeat/Squid.in
squid_opts parameter has been invalid due to missing metadata.
=> Medium: Squid: made squid_opts parameter available.

heartbeat/nfsserver
When disabling NFSv2 and NFSv3 mountd doesnt register with rpcbind, but
it's still running. This patch checks that mountd is running instead of
basing its status on it being registered w/rpcbind.
=> nfsserver: fix NFSv4-only support

heartbeat/podman
https://github.com/ClusterLabs/resource-agents/pull/1501 reimagined.
It may happen that some "podman exec" commands don't finish
cleanly and leave lingering "Exec sessions" in the container's
state. In that case, a "podman rm" command will always fail.
To overcome the podman bug, issue a "podman rm -f" command when
we detect a container is stopped but still has some lingering
"Exec sessions" associated with it.
Related-Bug: rhbz#1839721
=> podman: make sure to remove containers with lingering exec sessions

heartbeat/aliyun-vpc-move-ip
1. Add error log output
2. Modify 'grep "$OCF_RESKEY_address"' to 'grep "\s${OCF_RESKEY_address}/"', to solve the problem that the corresponding IROUTE_TO_INSTANCE cannot be obtained when both 10.0.1.2 and 10.0.1.21 exist at the same time
=> Add error log output

heartbeat/nfsserver-redhat.sh
On RHEL8, /etc/sysconfig/nfs is deprecated and has been replaced by /etc/nfs.conf [1],
the following error is output when nfserver is started.
Added a check to prevent users from getting confusing messages.
```
Jun 08 14:08:00 r81-1 pacemaker-execd     [4241] (operation_finished)   notice: nfs-daemon_start_0:6981:stderr [ cat: /etc/sysconfig/nfs: No such file or directory ]
Jun 08 14:08:00 r81-1 pacemaker-execd     [4241] (operation_finished)   notice: nfs-daemon_start_0:6981:stderr [ mv: cannot stat '/etc/sysconfig/nfs': No such file or directory ]
```
[1] https://access.redhat.com/solutions/3938381
=> nfsserver: prevent error messages when /etc/sysconfig/nfs does not exist

heartbeat/Filesystem
… as they are likely to use more than 6 seconds to stop
=> Filesystem: set "fast_stop" default to "no" for GFS2 filesystems

heartbeat/ocf-shellfuncs.in, heartbeat/pgsql
- ocf_is_ms(): also check OCF_RESKEY_CRM_meta_promotable to make it work w/Pacemaker 2.x
- pgsql: use XML output for better backward and forward compatibility, and "Promoted" keyword to be ready for Pacemaker 2.1
=> ocf-shellfuncs/pgsql fixes and improvements

heartbeat/docker-compose
1. removed svcname and used prefix name instead, to avoid terminlogogy confusion.
2. improved accuracy of service status determination using 'docker ps' instead of 'docker-compose ps'
=> docker-compose: bugfix

heartbeat/IPv6addr.c, heartbeat/send_ua.c
based on https://pubs.opengroup.org/onlinepubs/009695399/functions/siginterrupt.html
Thanks @wenningerk for reviewing and suggesting improvements.
=> send_ua/IPv6addr: use sigaction() instead of deprecated siginterrupt()

heartbeat/iSCSITarget.in
Existing model allows incoming CHAP authentication only when specifying a list of initiators, and sets the auth attribute for each initiator
Add support to set CHAP username/password at target portal group level (tpg auth attributes) if no list of initiators is provided
=> Add support for LIO-T incoming CHAP auth for TPG

heartbeat/gcp-vpc-move-vip.in
If a cluster contains two `gcp-vpc-move-vip` resources, only one can run
on a particular node at a given time. If a second `gcp-vpc-move-vip`
resource starts up on a node where one is already running, the existing
alias IP range is removed before the new one is added.
This places unnecessary limits on functionality. Per the GCP
documentation: "A VM instance virtual interface can have up to 10 alias
IP ranges assigned to it."
- [Configuring alias IP ranges](https://cloud.google.com/vpc/docs/configure-alias-ip-ranges)
The existing behavior prevents one node from being able to effectively
host two floating IP addresses simultaneously (unless they are in a
contiguous range and can be managed as a single unit, which is
uncommon).
This patch modifies the RA so that it updates the existing list …
=> [gcp-vpc-move-vip] Support for multiple alias IPs, and metadata improvements

heartbeat/sybaseASE.in
The `sybaseASE` resource agent runs the `verify_all()` function at the
beginning of start, stop, and monitor operations.
When `verify_all()` is run for a probe (monitor) operation and
`sybase_home` resides on a cluster-managed filesystem, the probe often
fails with `$OCF_ERR_GENERIC` because the filesystem isn't mounted yet.
This prevents the resource from starting on that node.
For the stop operation, there's simply no reason to run `verify_all()`.
This patch removes `verify_all()` for the stop and monitor operations.
It is now only run for the start operation.
Resolves: RHBZ#1848673
Resolves: RHBZ#1848025
=> sybaseASE: Run verify_all() for start operation only

heartbeat/azure-lb
The `lb_start()` function spawns an `nc` listener background process
and echoes the resulting pid to `$pidfile`. Due to a bug in the
redirection, all future data received by the `nc` process is also
appended to `$pidfile`.
If binary data is received later and appended to `$pidfile`, the
monitor operation fails when `grep` searches the now-binary file.
```
line 97: kill: Binary: arguments must be process or job IDs ]
line 97: kill: file: arguments must be process or job IDs ]
line 97: kill: /var/run/nc_PF2_02.pid: arguments must be process or job IDs ]
line 97: kill: matches: arguments must be process or job IDs ]
```
Then the start operation fails during recovery. `lb_start()` spawns a
new `nc` process, but the old process is still running and using the
configured port.
``` …
```
=> azure-lb: Don't redirect nc listener output to pidfile

heartbeat/pgsql
CRM_FEATURE_SET of pacemaker bundled with RHEL 8.1 is 3.2.0,
but crm_mon --output-as=xml is not implemented.
Fixes: https://github.com/ClusterLabs/resource-agents/issues/1527
=> pgsql: support RHEL 8.1 pacemaker

heartbeat/iSCSILogicalUnit.in
With minimal changes LIO-T 'pscsi' backing store can be implemented. As use case example this enables possibility to export tape library robot devices via SCSI passthrough to virtual machine in HA KVM setup where same multiple library robots are zoned to multiple corosync nodes in multiple datacenters via SAN to achieve HA. In such scenario corosync just switch iSCSILogicalUnit to online node. This solution can work with persistent device naming such as '/dev/tape/by-id/<wwn>' but firstly this patch has to be implemented https://github.com/open-iscsi/rtslib-fb/pull/165 into rtslib-fb because otherwise targetcli returns error when scsi_generic device is being exported via pscsi backend.
=> iSCSILogicalUnit: lio-t: Add pscsi LIO-T backing store

heartbeat/Filesystem
Whitespace in a device name (e.g., a CIFS share) or a directory name
breaks resource operations.
One issue is that many of the variable occurrences aren't quoted, so a
string containing whitespace is split into multiple tokens. This is a
problem when the string meant to be passed as a single argument to a
function (e.g., `list_submounts()`).
Another issue involves the parsing of `list_mounts()` output.
`list_mounts()` can pull data from `/proc/mounts`, `/etc/mtab`, or the
`mount` command. `/proc/mounts` and `/etc/mtab` represent spaces within
a field as octal `\040` strings, while `mount` represents them as
literal space characters.
`list_mounts()` had to be modified to output the mount list as three
distinct fields ((`device`, `mountpoint`, `fstype`), separated by tab
characters) …
=> Filesystem: Support whitespace in device or directory name

heartbeat/ocf-shellfuncs.in
Following the discussions on bsc#1170354, one of our customers
reports this function cannot detect the version strings used by SUSE:
2.0.3+20200128.df6c286d9-1.28
4.3.0184.6ee15eb2-4.19.1
2.0.1+20190417.13d370ca9-3.9.1
4.4.0+git57.70549516-1.2
=> Fix ocf_is_ver() to recognize SUSE version strings

heartbeat/nfsnotify.in, heartbeat/nfsserver
This patch has been tested on RHEL6, 7 and 8.
=> nfsserver/nfsnotify: fix SELinux issue due to newer ls versions giving additional output.

heartbeat/Filesystem
The grep command that populates mmap_procs is too unspecific, and will
return false positives from /usr or /etc if you attempt to manage
mount points named /u or /e, respectively.
=> filesystem: mmap search not specific enough

heartbeat/gcp-vpc-move-vip.in
python2 sorts a list of dicts of `{'ipCidrRange': <alias>}` correctly by
default. python3 fails with a TypeError:
`TypeError: '<' not supported between instances of 'dict' and 'dict'`
Fix this by using the key parameter of sorted(). python2 also supports
this.
=> gcp-vpc-move-vip: Fix sort for list of dicts in python3

heartbeat/aws-vpc-move-ip
In a shared network pattern where the cluster resides in shared subnets the instance ids of the nodes are not retrievable but the eni ids are and this optional feature gives transparent support in that situation.
=> aws-vpc-move-ip: Enable eni lookup for AWS shared networks via RAM

heartbeat/galera
When selecting a bootstrap node, the Galera resource agent primarily depends on the `safe_to_bootstrap` flag in `grastate.dat`. If none of the nodes have this flag set to 1 then functions `detect_last_commit()` + `detect_first_master()` provide a recovery logic to select the bootstrap node based on each node's last commit, as obtained from `grastate.dat` or `mysqld_safe --wsrep-recover`.
Fix 65f35e9172407e64ded90f29ea8fc0dfca9643e3 introduced a problem for this recovery logic. If a whole cluster is not gracefully stopped, `grastate.dat` on every node contains `safe_to_bootstrap: 0` and `seqno: -1`. Function `detect_safe_to_bootstrap()` then considers each node with this seqno as not suitable for bootstraping and clears the `safe_to_bootstrap` attribute. Nonetheless, functions …
=> galera: Fix automatic recovery when a cluster was not gracefully stopped

heartbeat/ocf.py
I have noticed that the `ocf.py` usage fails for python2, when the methods used in the handlers are coming from an object instance.
The `inspect.getargspec(func).args` piece of code returns `self` attribute, that we don't really want to use it.
This is the raised error:
```
ocf-exit-reason:validate() takes exactly 1 argument (2 given)
ocf.py(None)[22377]:	Sep 17 09:18:10 ERROR: validate() takes exactly 1 argument (2 given)
```
Removing `self` from the parameters list fixes the issue.
This doesn't affect to python3 as it goes for the other branch of the `if` statement
=> Fix ocf.py usage for py2 when self param is involved

heartbeat/Filesystem
Set OCF_RESKEY_fast_stop_default="no" for RHEL and CentOS major releases
9 and above, and for all other distros.
In the past, this attribute has defaulted to "yes", which has caused a
lot of confusion for users. fast_stop preempts the resource's stop
timeout, causing the agent to give up on unmounting the filesystem after
six seconds and declare a stop failure. (The resource operation does not
time out.)
The existence of a stop operation timeout renders fast_stop unnecessary,
and users typically expect that the agent will keep trying to unmount
the filesystem until the full stop operation timeout expires.
Resolves: RHBZ#1843577
=> Filesystem: Default fast_stop to no for RHEL 9+ and for other distros

heartbeat/galera
galera being a M/S resource, the resource agent decides
when and how to promote a resource based on the current
state of the galera cluster. If there's no cluster,
a resource is promoted as the bootstrap node. Otherwise
it is promoted as a joiner node.
There can be some time between the moment when a node is
promoted and when the promote operation effectively
takes place. So if a node is promoted for joining a cluster,
all the running galera nodes are stopped before the promote
operation start, the joining node won't be able to join the
cluster, and it can't bootstrap a new one either because it
doesn't have the most recent copy of the DB.
In that case, do not make the promotion fail, and force
a demotion instead. This ensures that a normal bootstrap
election will take place eventually, …
=> galera: recover from joining a non existing cluster

heartbeat/gcp-pd-move.in
- Fixed "regional" PD functionality in attach_disk()
- Improve to exact match disk_name with disks.source in detach_disk()
As current implement is done by partial match by "in", so this would wrongly take the different disk in the case that disk-a and disk-aa are attached to the host and configured this RA for disk-a.
Tested with zonal and regional pd to attach by this updated RA.
=> fixes and improvements for gcp-pd-move

heartbeat/ethmonitor
Vlan names end not with : but are suffixed with the @devices-name
=> ethmonitor: is_interface: RE matches vlan names

heartbeat/galera
When the master detection takes place, the node chosen for
becoming the master is given two attributes in the CIB:
a master score and a bootstrap flag. The master score makes
pacemaker schedule a promote operation, and the bootstrap flag
drives how the galera server is started.
The order in which we set the attributes is racy; it may happen
that a promote operation is started before the current master
detection function has set the bootstrap flag, in which case
the promotion will fail.
Reverse the order in which we set the attributes on a bootstrap
node to close the race.
=> galera: set bootstrap attribute before promote

heartbeat/galera
The new way of setting parameter defaults for the galera
resource agent has a side effect that broke the automatic
set up of OCF_RESKEY_check_user with clustercheck.
Revert to the original semantics of not not setting
default user to root early, as it prevents clustercheck
credentials to be used. Only set user to root as a fallback
if no other options configured it.
=> galera: fix check user configuration with clustercheck

heartbeat/galera, heartbeat/redis.in
Additional fixes based on https://github.com/ClusterLabs/resource-agents/pull/1518.
=> galera/redis: use --output-as for crm_mon w/newer Pacemaker, and prepare for Promoted role

heartbeat/galera
Galera maintains its own quorum, and when a network split
occurs in a two node cluster, both node becomes inquorate.
The resource agent always demotes a node when it loses
galera quorum; however it cannot promote it back because
it waits for the other node to advertise its DB sequence
number in the CIB, and that information is unavailable
during the network split.
Overcome this limitation by telling the resource agent
to use the quorum information from pacemaker. After fencing
took place, the surviving node is the only one active, so
it is safe to restart galera from it. Once the fenced node
comes back online, it won't have quorum until network
is restored, so it cannot restart galera locally so
split-brain is avoided.
This heuristic is made available via a new option
"two_node_mode". By …
=> galera: recover after network split in a 2-node cluster

heartbeat/aws-vpc-move-ip
Make log levels more appropriate to the situation. Before this patch, a
normal start looked like this:
```
Operation start for aws-vip (ocf:heartbeat:aws-vpc-move-ip) returned: 'ok' (0)
>  stderr: Nov 09 02:38:20 INFO: EC2: Moving IP address 10.0.1.65 to this host by adjusting routing table rtb-01b4ea1ae0ec0a4d9
>  stderr: Nov 09 02:38:20 INFO: monitor: check routing table (API call) - rtb-01b4ea1ae0ec0a4d9
>  stderr: Nov 09 02:38:22 WARNING: IP 10.0.1.65 not assigned to running interface
>  stderr: Nov 09 02:38:22 INFO: EC2: Adjusting routing table and locally configuring IP address
>  stderr: RTNETLINK answers: Cannot assign requested address
>  stderr: Nov 09 02:38:24 WARNING: command failed, rc 2
>  stderr: Nov 09 02:38:24 INFO: monitor: check routing table (API call) - …
```
=> aws-vpc-move-ip: Don't warn for expected scenarios

heartbeat/podman
When podman containers are created by the resource-agent, the podman
runtime spawns a side process (conmon) to monitor the container and
record the exit status.
If the conmon process dies unexpectedly (e.g. kill -9), the podman
container can still be stopped, even if the cli returns a generic
error.
Try to distinguish this specific failure condition and make the stop
operation resilient; when it happens, just log a warning and finish
the usual stop actions.
=> podman: recover from killed conmon side process

heartbeat/podman
If a system crash while podman is stopping a container (e.g. a fencing action
took place), it might happen that on reboot, podman is not able to recreate
a container as requested by the resource agent.
When such a start operation fails, it might be because the internal storage
layer still references an old container with the same name, even though podman
itself thinks there is no such container. If so, purge the storage layer to try
to clean the corruption and try recreating the container.
=> podman: recover from podman's storage being out of sync

heartbeat/ocf.py
In my LAB I have seen  that ocf.py is_probe fails on unset OCF_RESKEY_CRM_meta_interval
See also Issue #1579
=> fix problem with unset OCF_RESKEY_CRM_meta_interval by cluster framework

configure.ac
this also fixes make distcheck as normal user and
does not install ldirector systemd unit in / by mistake
=> [build] fix systemd paths when using non standard prefix

heartbeat/iface-vlan
Machines commonly have several vlan_id attached to one interface,
and may also have a vlan_id attached to several interfaces.
vlan_name will still be unique, usual names are:
- bond_in.83@bond_in
- bond_in.84@bond_in
fixes #1581
=> heartbeat/iface-vlan: vlan_{interface,id} do not have to be unique.

heartbeat/apache, heartbeat/azure-lb, heartbeat/ocf-distro
This PR seeks to address several issues in ocf-distro. Summary:
- `get_os_ver()` is missing a check for SUSE OSes. This PR adds one.
- `get_os_ver()` does two jobs. This PR creates a new `get_os_version_id()` function to get the OS version, to parallel the existing `get_release_id()` function that gets the OS release. `get_os_ver()` now calls each of these functions to reduce code duplication. We do keep `get_os_ver()` for backwards compatibility in case anyone uses it in a custom script. It's unused upstream.
- We have `is_redhat_based()` already. This PR adds `is_debian_based()` and `is_suse_based()`, and then calls them instead of using `get_release_id()` and case statements in the `azure-lb` and `apache` agents.
- The Red Hat distro regex fails for Scientific Linux when `lsb_release` …
=> ocf-distro: Improve robustness and specificity

heartbeat/ocf-distro
Align ocf-distro's accepted version format with the current
ocf_version_cmp()-accepted format.
See commit b4df0873. I apparently wasn't working with the latest version
of ocf-shellfuncs when creating #1558.
I don't think that the literal backslash should be an allowed character in a
version string, but it's present in ocf_is_ver() currently.
=> ocf-distro: Update version format

heartbeat/LVM-activate
If storage services (e.g., iscsi-shutdown.service) stop before an
LVM-activate resource stops, the managed VG may become unavailable. Then
the LVM-activate resource may fail to deactivate the volume group and
thus fail its stop operation.
This commit adds a systemd drop-in "After=blk-availability.service"
directive for resource-agents-deps.target during the LVM-activate start
op. blk-availability includes "After=" directives for other storage
services and thus serves as a convenient wrapper.
blk-availability is not enabled by default, and a "Wants=" drop-in
that's created after Pacemaker starts would not be able to start
blk-availability automatically. So here we also start blk-availability
during LVM_start().
Resolves RHBZ#1902208
=> LVM-activate: Stop before blk-availability.service

tools/ocft/caselib.in
Convert timeout to milliseconds for OCF_RESKEY_CRM_meta_timeout
=> Dev: ocft: fix OCF_RESKEY_CRM_meta_timeout

heartbeat/pgsql
In PostgreSQL 11 and later the wal receiver process is named
"walreceiver" instead of "wal receiver process". This change makes the
check for a running wal receiver process compatible with both variants.
Fixes #1551
=> pgsql: make wal receiver check compatible with PostgreSQL >= 11

heartbeat/Route
In combinations with other agents such as heartbeat/iface-vlan,
interfaces on which routes are managed might not exist
if that resource is stopped.
In this case, the status check can safely assume that the route
is not present when the interface does not exist.
fixes #1588
=> heartbeat/Route: Return OCF_NOT_RUNNING status if iface doesn't exist.

heartbeat/mysql-common.sh
MariaDB startup hangs if the datadir is not writable.
=> mysql-common: check datadir permissions

heartbeat/gcp-vpc-move-route.in, heartbeat/gcp-vpc-move-vip.in
The current route and vip resources fail if the instance is in a shared service project.
Resolves: RHBZ#1913932
Resolves: RHBZ#1913936
=> gcp-vpc-move-route, gcp-vpc-move-vip: Parameterize project ID

heartbeat/nfsserver
Fail to stop if unmounting rpcpipefs_dir or /var/lib/nfs fails.
After:
```
Operation stop for nfs-daemon (ocf:heartbeat:nfsserver) returned: 'error' (1)
Feb 02 17:58:58 INFO: Stopping NFS server ...
Feb 02 17:58:58 INFO: Stop: threads
Feb 02 17:58:58 INFO: Stop: rpc-statd
Feb 02 17:58:58 INFO: Stop: nfs-idmapd
Feb 02 17:58:58 INFO: Stop: nfs-mountd
Feb 02 17:58:58 INFO: Stop: nfsdcld
Feb 02 17:58:58 INFO: Stop: rpc-gssd
Feb 02 17:58:58 INFO: Stop: umount (1/10 attempts)
umount: /var/lib/nfs: target is busy.
Feb 02 17:58:59 ERROR: Failed to unmount /var/lib/nfs
ocf-exit-reason:Failed to unmount a bind mount
```
Resolves: RHBZ#1924363
=> nfsserver: Error-check unbind_tree

heartbeat/docker-compose
The current docker-compose resource only handles docker-compose.yml file. It doesn't matter what you set when creating resource in pacemaker with **ymlfile** parameter.
Fixed missing **-f $YML** when doing start/stop/monitor actions.
=> docker-compose: Bugfix handle ymls correctly

heartbeat/azure-lb
This fixes a regression introduced in commit d22700fc.
When the `nc` listener process created by an `azure-lb` resource attempts to
write to `stdout`, it dies with an `EPIPE` error.
This can happen when random/garbage input is sent to the `nc` listener, as
may happen during a port scan. For example, if the listener is on port
62000, and a client sends some text (e.g.,
`echo test | nc node1 62000`), then the listener attempts to echo "test" to its
`stdout`. This fails with an `EPIPE`.
Prior to commit d22700fc, all output was redirected to the pid file.
This caused its own problems, but it prevented this particular behavior.
The fix is to redirect the listener's `stdout` and `stderr` to `/dev/null`.
Resolves: RHBZ#1937142
Resolves: RHBZ#1937151
=> azure-lb: Redirect stdout and stderr to /dev/null

heartbeat/aws-vpc-move-ip, heartbeat/aws-vpc-route53.in, heartbeat/awseip, heartbeat/awsvip
Fixes https://github.com/ClusterLabs/resource-agents/issues/1624 and https://github.com/ClusterLabs/resource-agents/issues/1625.
=> AWS agents: dont partially match similar IPs during monitor-action and dont spam log files when getting token

heartbeat/VirtualDomain
When starting a VM or migrating it, some of the storage pools or
networks it requires may not be started. Start those if needed.
Refreshing the storage pools may also be needed. For instance when using
an pool of dir type on an OCFS2 mount, the mount may not be done at the
time of the pool start. Libvirt would then think there is no volume in
the pool...
=> VirtualDomain: Ensure needed virtual storage pools and networks are up and refreshed

heartbeat/openstack-info.in
- Use OSInfo_validate in start action and remove superfluous final exit.
=> openstack-info: Use OSInfo_validate in start action.

heartbeat/openstack-floating-ip
- Use osflip_validate in start & validate-all actions and fix OCF_SUCCESS ocf_log info to make sense.
=> openstack-floating-ip: Proper use of osflip_validate and small log message fixes.

heartbeat/openstack-cinder-volume
- Reduce getting node/instance ID methods down to one via openstack-info (same as all other openstack agents)
- Fix order of operations in checking for OCF_RESKEY_openrc
- Updates due to API output format changes.
- Attempt to future-proof parsing of the output.
=> openstack-cinder-volume: CLI output parsing fixes, fetch of node ID consistency, monitor action simplification, and proper use of osvol_validate.

heartbeat/azure-events.in
According to Microsoft's document, current version of API is "2019-08-01"
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/scheduled-events
=> azure-events: update api_version

heartbeat/gcp-ilb
This is a wrapper for nc or socat (depending on availability) to reply to health check probes. The only GCP specific piece is the optional default logging using the gcloud CLI.
=> gcp-ilb: resource wrapping nc or socat to respond to health checks

heartbeat/LVM-activate
The autoactivation property of volume group will be disabled when
vg_access_mode is set to system_id, to fix HA-LVM systemid race
condition, which introduces an error "active on 2 nodes".
For HA-LVM systemid use case, the node might introduce the
unexpected outage of the cluster service. In details, the node
might suffer from some race condition and reports "active on 2 nodes"
on one node after reset the active node. This will cause the active
service to be restarted which is unexpected.
=> LVM-activate: Disable VG autoactivation in system_id access_mode

heartbeat/gcp-vpc-move-vip.in
If the cluster fails a monitoring event, it will try to restart the resource. If the resource agent makes an API/metadata call that fails at that time, the resource will be considered "failed", but in certain case also "unconfigured", which prevents further operations.
These changes can help the agent recover on certain intermittent failures.
=> gcp-vpc-move-vip.in: Adds retries

heartbeat/LVM-activate
Fixes https://github.com/ClusterLabs/resource-agents/issues/1647
=> LVM-activate: fix drop-in check to avoid re-creating drop-in file when it already exists

heartbeat/VirtualDomain, tools/ocft/VirtualDomain
This is required to make it compatible with the values set by the NodeUtilization resource agent when running on a kvm based Hypervisor (RHEL, CentOS)
On CentOS, 
NodeUtilization can set available host_memory and cpu for the node but sets hv_memory to 0
VirtualDomain only sets cpu and hv_memory usage which means these two RAs cannot be used together.
=> Added code to set the host_memory value for Utilization in the VirtualDomain RA

heartbeat/podman
podman and OCI runtime have a race that sometimes causes
a container to fail to be created and run [1] if the
cgroup to be used is not available yet. When that happens,
try to recreate it until it succeeds or the start
timeout is reached.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1972209
=> podman: workaround race during container creation

tools/findif.c
=> findif: popen requires pclose and not fclose

heartbeat/CTDB.in
Timelimit is enough to manage resource timeoutin CTDB module
#1660
=> CTDB: replace timeout override w/ctdb_timeout parameter

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/nvmet-namespace, heartbeat/nvmet-port, heartbeat/nvmet-subsystem
Three new resource agents that allow to operate NVMe-oF Targets.
You need to have a NVMeSubsystem RA first, followed by namespace(s)
and port(s). In order to enable failover you need to set the UUID
on the namespace. I guess it is a good idea to set the nguid (on
the namespace) and the serial (on the subsystem) as well.
=> NVMe-oF-Target: New RAs nvmet-subsystem nvmet-namespace nvmet-port

heartbeat/ocf-shellfuncs.in
The function `ocf_bash_has_xtracefd` and its alias `ocf_is_bash4` break non bash shells (in my case dash) because of how bash version is tested. Due to local environment idiosyncrasies it is perfectly possible to have dash running a script while the variable `SHELL` has a value of `/bin/bash`. It works fine for most of the code except the tracing functionality.
What I propose is to fix the version detection mechanism by first checking against the usually not exported variable `BASH_VERSION`.
=> Remove a bashism in ocf-shellfuncs.in

heartbeat/iSCSILogicalUnit.in
Since Linux kernel commit [0322913cab79](https://github.com/torvalds/linux/commit/0322913cab79e47282fa98910559cbf6f3660b52) ("scsi: target: Add device
product id and revision configfs attributes"), setting a SCSI product id
via the product_id configfs attribute is supported in the target
subsystem.
Thus, forward the value of the product_id resource agent parameter there
and remove it from the list of unsupported parameters for lio-t.
---
This is a relatively modern feature, only being present in mainline kernels >5.1. Though it seems like at least RedHat have backported this to their 4.18.0 series (RHEL8):
```
[root@test1 ~]# uname -r
4.18.0-305.7.1.el8_4.x86_64
[root@test1 ~]# cat /sys/kernel/config/target/core/iblock_0/lu1_target1/wwn/product_id
Custom Product
```
=> iSCSILogicalUnit: lio-t: support setting product_id

doc/man/Makefile.am, heartbeat/Makefile.am
the main problem is that some agents are built in builddir, while
others will stay in srcdir. This include ocflibs and some helper
scripts.
when building man pages, we can only point to one dir for OCF_ROOT
and related scripts, and in this case it has to be builddir.
Hack around this OCF limitations by using symlinks into the builddir
for agents that are not "built".
=> [build] fix out-of-tree build for man pages

heartbeat/Filesystem
Calling partprobe is a heavy fallback.
(And should not be used at all, IMO, as it masks somebody elses problem, really.
If you need it, you _actively_ created something on one cluster node that did
not exist before, so you actively added this to the cluster configurtion just
now as well, so you can actively call partprobe yourself after creating the
thing and before adding it to the cluster config, right?)
Anyways. Now partprobe is called for each and every bind mount since
a9fb8077 Filesystem: add trigger_udev_rules_if_need() for -U, -L, or /dev/xxx device
I suggest to only do it if we know it is supposed to be a block device.
=> Filesystem: do not call partprobe for bind mounts

heartbeat/VirtualDomain
Since 'xenmigr' scheme was no longer supported by libvirt, we
should remove the prefix 'xenmigr' from migrate uri.
Otherwise, there will be an error when migrate VM.
=> VirtualDomain: drop prefix xenmigr from migrate uri

heartbeat/mysql, heartbeat/mysql-common.sh
Added support for local MySQL connection over SSL.
**Use Case:**
once a `REQUIRE  SSL` for MySQL user is set, the cluster will not be able to manage its MySQL resource any further.
A good practice is to require SSL for all MySQL external users. A replication user is one of those.  A replication by itself may _(and should)_ be configured over SSL, however the enforcement for replication user to use SSL may be occasionally not set.
This patch allows to configure MySQL resource to use SSL _(by default is set to `false` - so no running setups will be affected)_.
**_How To:_**
1. Enforce SSL for MySQL user _(MySQL v5.7+)_:
```
mysql> show variables like 'version';
+---------------+-----------------------------+
| Variable_name | Value                       | …
```
=> MySQL: add Support for local SSL connection

tools/tickle_tcp.c
tickle_tcp.c: In function ‘send_tickle_ack’:
tickle_tcp.c:60:26: error: ‘phdr’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
sum += (uint32_t)ntohs(*data);
^
tickle_tcp.c:60:26: error: ‘*((void *)&phdr+2)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
tickle_tcp.c:60:26: error: ‘*((void *)&phdr+4)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
tickle_tcp.c:60:26: error: ‘*((void *)&phdr+6)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
cc1: all warnings being treated as errors
gmake[3]: *** [Makefile:697: tickle_tcp.o] Error 1
=> [tools] fix build on opensuse 15.3

heartbeat/symlink
Hi,
this change allows using a symlink in the target path by getting canonical path of target as well as wanted link
=> fix symlink vs target realpath comparison

heartbeat/nfsnotify.in
When start the nfsnotify resource on debian, throw an error "stderr: id: 'rpcuser': no such user" .
=> nfsnotify: fix rpcuser error when resource start on debian

heartbeat/nfsserver
Problem: https://github.com/ClusterLabs/resource-agents/issues/1644
RFC8881, 8.4.2.1 State Reclaim:
| If the server scope is different, the client should not attempt to
| reclaim locks. In this situation, no lock reclaim is possible.
| Any attempt to re-obtain the locks with non-reclaim operations is
| problematic since there is no guarantee that the existing
| filehandles will be recognized by the new server, or that if
| recognized, they denote the same objects. It is best to treat the
| locks as having been revoked by the reconfiguration event.
That's why for lock reclaim to even be attempted, we have to define and set
the same server scope for NFSD on all cluster nodes in the NFS failover
cluster. And in linux, that is done by setting the uts nodename for the
command that starts the …
=> nfsserver: Fix NFSv4 lock failover: set NFS Server Scope

heartbeat/rabbitmq-cluster.in
Currently when a rabbitmq-server resource is started,
the forget_cluster_node command is executed to ensure the node being
started is not part of the existing cluster.
This command is dependent on the local node name defined as a node
attribute but there are some situations like the examples below where
the attribute is not yet defined when the resource is started.
- When a cluster is freshly deployed and started for the first time
- When a cluster node is broken and replaced by a new node
This change ensures the node attribute exists to run the command,
to avoid invalid usage of the command without the target node name.
=> rabbitmq-server-ha: Avoid forget_cluster_node without node name

heartbeat/asterisk
To avoid the case where the sipsak check runs before the sip starts at the start action
=> asterisk: fix sipsak check during start-action

heartbeat/db2
Fixes https://github.com/ClusterLabs/resource-agents/issues/1717.
=> db2: use -l forever instead of -t nodes -l reboot, as they conflict with eachother

heartbeat/nginx
nginx RA updated with ocf_exit_reason support.
a number of agents don't have support for ocf_exit_reason #704
=> nginx: replace error log messages with calls to ocf_exit_reason

heartbeat/Filesystem
When unmount a file system, we should unmount any bind mounts on
this device firstly. Otherwise, the device still has file system
mounts, this may cause the deactivation of the device to fail.
=> Filesystem: unmount bind mounts before unmount file system

heartbeat/asterisk, heartbeat/db2
added ocf variable between quotation mark because there are a special character ":"
=> asterisk: Sipsak check fix

heartbeat/Filesystem
`mount.efs`, the mount helper for Amazon Elastic File System (EFS)
provided by `amazon-efs-utils` [1], is a wrapper for `mount.nfs4`. It offers
a number of AWS-specific mount options and some security improvements
like encryption of data in transit.
Here we add support by treating an `fstype=efs` like `fstype=nfs4` for the
most part.
This PR also does the following:
- fixes a check that's been causing us to skip `fstype_supported()` since it was added 8 years ago.
- informs the user when we have to use a different name in order to check fstype support. I'm logging to info instead of debug because we only call `fstype_supported()` during start operations and this will make the exit reason less confusing if we fail.
[1] https://docs.aws.amazon.com/efs/latest/ug/efs-mount-helper.html …
=> Filesystem: Add support for Amazon EFS mount helper

heartbeat/rabbitmq-server-ha
SERVER_START_ARGS's -sname should be used with short host names,
otherwise it should take -name <FQDN>.
Signed-off-by: Bogdan Dobrelya <bdobreli@redhat.com>
=> rabbitmq-server-ha: Fix SERVER_START_ARGS sname/name use for FQDN

heartbeat/rabbitmq-server-ha
ocf_is_true is better, as users may use other true/false values as well
Signed-off-by: Bogdan Dobrelya <bdobreli@redhat.com>
=> rabbitmq-server-ha: Use ocf_is_true, if applicable

heartbeat/README, heartbeat/ocf-shellfuncs.in
The `OCF_TRACE_FILE` takes the precedence. If it's not defined,
the `OCF_RESKEY_trace_dir` is used. Otherwise the log is stored by default
in `$HA_VARLIB/trace_ra/<type>/`
This PR comes together with https://github.com/ClusterLabs/crmsh/pull/935 .  The crmsh stores the log-dir in the cib.xml. This PR uses the stored log-dir.
@gao-yan @liangxin1300 could you please have a look?
=> ocf-shellfuncs: Parametrise the log destinarion by OCF_RESKEY_trace_dir

heartbeat/IPsrcaddr
If DHCP is enabled for the interface that serves `OCF_RESKEY_ipaddress`,
then NetworkManager (and possibly `dhclient` in systems without NM;
unsure) may later re-add a route that the `IPsrcaddr` resource replaced.
This may cause the resource to fail or cause other unexpected behavior.
So far this has been observed with a default route, albeit with an edge
case of a configuration (`OCF_RESKEY_ipaddress` on a different subnet)
that may not be totally valid. There are likely to be other situations
as well where DHCP can cause conflicts with `IPsrcaddr`'s manual updates
via `iproute`. The safest option is to use only static configuration for
the involved interface.
Resolves: RHBZ#1654862
=> IPsrcaddr: Add warning about DHCP

heartbeat/IPsrcaddr
If `OCF_RESKEY_destination` is not explicitly set and `ip route list`
can't find a route matching the specifications, the `NETWORK` variable
doesn't get set. This causes a certain failure of the start operation,
because there is no `PREFIX` argument to `ip route replace` (syntax
error). It may also cause unexpected behavior for stop operations (but
not in all cases). During a monitor, this event can only happen if
something has changed outside the cluster's control, and so is cause
for warning there.
Exit `OCF_ERR_ARGS` for start, log debug for probe, log warning for all
other ops.
Resolves: RHBZ#1654862
=> IPsrcaddr: Better error message when no matching route found

heartbeat/ocf-shellfuncs.in
Usage of pidfile variable was not quoted so it was not possible to call
ocf_pidfile_status with path containing space. Solution is to add quotes
to -e test and cat command. Also use $() syntax for cat command and
unify indentation.
Signed-off-by: Jan Friesse <jfriesse@redhat.com>
=> ocf-shellfuncs: quote pid in ocf_pidfile_status

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/corosync-qnetd
Mostly for better monitor operation using corosync-qnetd-tool. As qnetd
is (almost) stateless only directory which has to be copied (once)
across the nodes is nss db directory (usually
/etc/corosync/qnetd/nssdb).
Signed-off-by: Jan Friesse <jfriesse@redhat.com>
=> corosync-qnetd: Add resource agent

heartbeat/IPsrcaddr
- use findif.sh to detect secondary interfaces
- get metric and proto to update the correct route/update it correctly
- match route using interface to fail when trying to update secondary
interfaces without specifying destination (would update default route
before)
- also use PRIMARY_IP/OPTS during stop-action for default routes (to get
back to the exact routes we started with)
- dont fail during stop-action if route doesnt exist
- use [[:blank:]] for WS to follow POSIX standard (suggested by nrwahl)
=> IPsrcaddr: fixes

heartbeat/LVM-activate
hi  ，I found a problem when building a cluster  , When the cluster uses LVM-activate and the on-fail=fence parameter is set, if  the vg is lost, the return value of the monitor function is ocf_not_running  that the cluster cannot trigger the fence action
=> LVM-activate:change lvm_status return value from ocf_not_running to ocf_err_generic

heartbeat/IPaddr2
Allow the user to disable Duplicate Address Detection for IPv6 and to send unsolicited Neighbor Advertisements in background.
=> IPaddr2: Enable more control for IPv6 addresses

heartbeat/ocf-distro
AlmaLinux, Oracle Linux, and Rocky Linux are now detected as RHEL based
distributions. Enables usage of additional RHEL specific options for the
nfsserver resource agent as defined in nfsserver-redhat.sh.
=> ocf-distro: improve RHEL based distro detection

heartbeat/storage-mon.in, ldirectord/ldirectord.in
Also remove trailing space at the end of the line.
=> storage-mon,ldirectord: fix spelling errors

heartbeat/ethmonitor, heartbeat/mariadb.in, heartbeat/ovsmonitor
bc might not be installed by default on a minimal Debian system.
=> ethmonitor,ovsmonitor,mariadb: check for bc binary

heartbeat/ocivip
Also remove trailing space at the end of the line.
=> ocivip: fix spelling errors

heartbeat/podman
hi, I found a problem when using podman. If the parameters are incorrectly filled when creating a podman resource, podman will not return the corresponding error message as exit_reason, so some modifications have been made in podman to add podman parameter error judgment.
=> podman: add podman parameter error judgment

heartbeat/iSCSILogicalUnit.in
When using Allowed_initiators parameters, the resource status is stopped state
=> iSCSILogicalUnit: fix issue where resource was in stopped state when using allowed_initiators parameter

heartbeat/rabbitmq-server-ha
Running `meta-data` or `help` causes a `mkdir -p /var/run/rabbitmq`.  This even occurs when generating the documentation during a build.
=> Do not mkdir -p when getting meta-data or help

heartbeat/aws-vpc-move-ip
Add a parameter to specify an interface label to distinguish the IP address managed by aws-vpc-move-ip, similarly as can be done with IPaddr2. This allows to easily recognize the address from other addresses assigned to a given interface.
=> aws-vpc-move-ip: Allow to set the interface label

heartbeat/LVM-activate
Splitting this commit out from #1600.
OCF_ERR_ARGS should be used when the configuration isn't valid for the
**local** node, and so the resource should not attempt to start again
locally until the issue is corrected.
OCF_ERR_CONFIGURED should be used when the configuration isn't valid on
**any** node, and so the resource should not attempt to start again
anywhere until the issue is corrected.
One remaining gray area:
- Should lvmlockd/clvmd improperly running (or improperly not running)
be an OCF_ERR_GENERIC or OCF_ERR_ARGS? The fact that it's a state issue
rather than a config issue suggests OCF_ERR_GENERIC. The fact that it
won't be fixed without user intervention suggests OCF_ERR_ARGS.
More info about return code meanings:
- https://clusterlabs.org/pacemaker/doc/en-US/Pacemaker/2.0/html …
=> LVM-activate: Fix return codes

heartbeat/mariadb.in
This change was already done for mysql in https://github.com/ClusterLabs/resource-agents/pull/1191
=> mariadb: Remove obsolete DEBUG_LOG functionality #1191

heartbeat/openstack-cinder-volume, heartbeat/openstack-floating-ip, heartbeat/openstack-virtual-ip
- openstack-cinder-volume: dont do volume_local_check during start/stop-action
- openstack-floating-ip/openstack-virtual-ip: dont fail in validate()
during probe-calls
- openstack-floating-ip: fix awk only catching last id for node_port_ids
=> openstack-agents: fixes

tools/storage_mon.c
Previously specifying the maximum allowed number (MAX_DEVICES, currently 25)
of devices and scores as arguments could cause storage_mon to fail unexpectedly
with the error message "too many scores, max is 25". This issue happened
because storage_mon checked whether the number of specified scores
exceeded the upper limit by using the local variable "device_count" indicating
the number of specified devices (not scores). So after the maximum number
of devices arguments were interpreted, the appearance of next score argument
caused the error even when the number of interpreted scores arguments had
not exceeded the maximum.
This patch fixes storage_mon so that it uses the local variable "score_count"
indicating the number of specified scores, to check whether arguments for
scores are specified …
=> storage_mon: Fix bug in checking of number of specified scores.

tools/storage_mon.c
When storage_mon detects that a child process exits with zero,
it resets the test_forks[] entry for the child process to 0, to avoid
waitpid() for the process again in the loop. But, previously,
storage_mon didn't do that when it detected that a child process
exited with non-zero. Which caused waitpid() to be called again
for the process already gone and to report an error like
"waitpid on XXX failed: No child processes" unexpectedly.
In this case, basically storage_mon should wait until all the child
processes exit and return the final score, instead.
This patch fixes this issue by making storage_mon reset test_works[]
entry even when a child process exits with non-zero.
=> storage_mon: Fix bug in handling of child process exit.

heartbeat/ethmonitor, heartbeat/ovsmonitor, heartbeat/pgsql
attrd_updater in 2.1.3 no longer ignores the -q parameter, which makes
these agents break. It never did anything in attrd_updater, and is
probably left-over from copy/paste crm_attribute code that got changed
to attrd_updater.
=> ethmonitor/ovsmonitor/pgsql: remove ignored attrd_updater "-q" parameter

tools/Makefile.am, tools/storage_mon.c
Use of O_DIRECT in open() eliminates the possibility of false negatives resulting from buffer cache reads.
please refer to https://lists.clusterlabs.org/pipermail/users/2022-August/030459.html for background.
=> storage_mon: Use the O_DIRECT flag in open() to eliminate cache effects

heartbeat/portblock
Currently, the portblock agent can only operate on the INPUT chain. Blocking our own host from sending traffic on a specific port is presently not possible.
To enable this, introduce a "direction" parameter that specifies whether to operate on incoming traffic (INPUT chain with destination ports) or outgoing traffic (OUTPUT chain with source ports).
A word on the use case we have for this: we have deployments that export storage via an iSCSI target (using the iSCSITarget resource agent), with a DRBD disk underneath it.
When the underlying DRBD device loses quorum, it freezes the pending IO requests. When it later re-joins the cluster and finds that another node was made primary, it has to "thaw" these IO requests, ending them with IO errors.
The problem arises when the iSCSI initiator is …
=> portblock: implement blocking of outgoing ports

heartbeat/iface-macvlan
We needed a Resource-Agent for adding / removing macvlan devices. This is because we are using a Gateway in one place which only supports forwarding to a destination if you keep the MAC-Address for a specific IP.
I found other people searching the Web with the need of a macvlan RA, so I had the Idea to publish this. It is currently limited to bridge type because I only have tested it with type bridge.
=> iface-macvlan: new resource agent

configure.ac
configure scripts need to be runnable with a POSIX-compliant /bin/sh.
On many (but not all!) systems, /bin/sh is provided by Bash, so errors like this aren't spotted. Notably Debian defaults to /bin/sh provided by dash which doesn't tolerate such bashisms as '=='.
This retains compatibility with bash.
Signed-off-by: Sam James <sam@gentoo.org>
=> configure.ac: Fix bashisms

heartbeat/SAPInstance
The code using pid could break, if kill.sap includes unexpected content. Now the scanner checks more focused, if the third element is a number and only let the number pass the scanner.
=> SAPInstance: be more resilient against broken kill.sap files

heartbeat/mysql-proxy
Use one of the directories where this socket can be provided securely
=> Please don't suggest /tmp/mysql-proxy.sock, that is bad practice.

heartbeat/WAS6
shellcheck was failing on the invalid condition
=> WAS6: fix trap condition

heartbeat/exportfs
Issue: the annoying messages during monitoring,
```
notice: p-exportfs_monitor_30000[32157] error output [ grep: /var/lib/nfs/rmtab: No such file or directory ]
```
=> exportfs: fix the error handling during monitoring

heartbeat/db2
I'm not sure if you can get characters in here that are problematic, but better not to use unsanitized string than be sorry
=> db2: avoid eval with unsanitized values

heartbeat/nfsserver
Symptom:
The distro may have additional drop-in files to override `ExecStart=`, eg. openSUSE. In that case, the result drop-in file is messed up with several ExecStart= generated. For example,
cat
/run/systemd/system/nfs-server.service.d/51-resource-agents-unshare-uts.conf
[Service]
EnvironmentFile=/run/sysconfig/nfs-server-scope
ExecStart=
ExecStart=/usr/bin/unshare --uts /bin/sh -c 'hostname ${NFS_SERVER_SCOPE}; exec "$@"' -- /usr/sbin/rpc.nfsd ExecStart=/usr/bin/unshare --uts /bin/sh -c 'hostname ${NFS_SERVER_SCOPE}; exec "$@"' -- 
ExecStart=-/usr/bin/unshare --uts /bin/sh -c 'hostname ${NFS_SERVER_SCOPE}; exec "$@"' -- /usr/sbin/rpc.nfsd $NFSD_OPTIONS
Indeed, only the last ExecStart= is needed.
=> nfsserver: fix "server scope" to live with additional drop-in files

heartbeat/ocf-shellfuncs.in
Hi All,
The following fixes were made in pacemaker:
- https://github.com/ClusterLabs/pacemaker/pull/3039
For compatibility, specify the option specification explicitly.
Best Regards,
=> Mid: ocf-shellfuncs: Explicitly specify $OCF_RESOURCE_INSTANCE in the p parameter for compatibility.

heartbeat/LVM-activate
There area two changes included:
- Allow the system ID to be changed on a VG when the VG is missing PVs, as long as a majority of PVs are still present. This requires a recent version of lvm that supports the --majoritypvs option for vgchange.
- Use --activationmode degraded when activating LVs so that raid LVs can be activated when legs are missing, as long as sufficient devices are available for raid to provide all the data in the LV.
By David Teigland.
=> LVM-activate: failover with missing PVs

heartbeat/ZFS
The function  `zpool_is_imported` can be improved to use ZFS kstats instead of blocking `zpool list` calls for newer releases of ZFS.
=> ZFS: add non-blocking check if pool was imported

heartbeat/exportfs
Based on feedback [1] from the kernel developer @neilbrown regarding the NFS clustering use case, it has been determined that the fsid= parameter is now considered optional and safe to omit.
[1] https://bugzilla.suse.com/show_bug.cgi?id=1201271#c49 """
Since some time in 2007 NFS has used the UUID of a filesystem as the primary identifier for that filesystem, rather than using the device number.  So from that time there should have been reduced need for the "fsid=" option.  Probably there are some filesystems that this didn't work for.  btrfs has been problematic at time, particularly when subvols are exported.  But for quite some years this has all "just worked" at least for the major filesystems (ext4 xfs btrfs). [...] I would suggest getting rid of the use of fsid= altogether. [...] …
=> exportfs: make the "fsid=" parameter optional

heartbeat/azure-events-az.in, heartbeat/azure-events.in
The fact is, the option "-s" is basically used for showing resource allocation scores. So arguably it was not really appropriate/necessary for "-s" to additionally display "Transition Summary". Now -S have to be used.
=> azure-events*: Use -LS instead of -Ls as parameter to get the Transition Summary

resource-agents.spec.in
Both Fedora and openSUSE now recommends to use SPDX shortname format for License.
=> spec: Migrate to SPDX license

heartbeat/Filesystem
Parsing mount command output in list_mounts() results in a sed error: sed: -e expression #1, char 51: invalid reference \5 on `s' command's RHS
This results in a list_mounts not returning any mounts.
The error is caused due to match_string only providing three capture groups, while the replacement string references a non-existing 5th capture group.
Also, the output for this case differs from the case where the mount list is parsed from /proc/mounts or /etc/mtab as it would include the mount options in the output.
Fixes: a8051cf9e21d ("Filesystem: Support whitespace in device or directory name")
=> Filesystem: list_mounts: fix mount command output parsing

heartbeat/postfix
In the postfix resource agent, changed the check for a writable config directory to use sudo rather than su. Using su is prone to authentication failures while sudo works well.
=> postfix: Update permission check from su to runuser/su

heartbeat/mysql-common.sh
hi , there are situations when MySQL fails to start and the error is sent to standard error/standard out and is not display on the terminal. then i add some log message in ocf_exit_reason . hope it helps
=> mysql-common: improve error message

heartbeat/iSCSILogicalUnit.in, heartbeat/iSCSITarget.in
Add scst (https://github.com/SCST-project/scst/) as a new supported implementation to the iSCSITarget and iSCSILogicalUnit resource agents.
All basic functionality that is supported by the other implementations is supported by scst as well.
=> iSCSI: add support for scst

heartbeat/ocivip
Fix PRIMARY_IFACE variable. In some cases ip commands returns two lines
=> ocivip: Fix PRIMARY_IFACE variable. In some cases ip returns two lines

heartbeat/findif.sh
`tools/ocft/IPaddr2` fails the loopback test because of the missing `table local` parameter:
```
$ ip -o -f inet route list match 127.0.0.3 scope host
$ ip -o -f inet route list match 127.0.0.3 table local scope host
local 127.0.0.0/8 dev lo proto kernel src 127.0.0.1
```
Also rename the function because it is called only in for the special loopback address case.
=> findif.sh: fix loopback handling

heartbeat/aws-vpc-move-ip, heartbeat/aws-vpc-route53.in, heartbeat/awseip, heartbeat/awsvip
Based on  https://github.com/ClusterLabs/resource-agents/pull/1899
=> aws-vpc-move-ip/aws-vpc-route53/awseip/awsvip: add auth_type parameter and AWS Policy based authentication type

heartbeat/IPaddr2
Fixes this warning (which gets logged on every recurring monitor for a Pacemaker resource):
```
$ OCF_ROOT=/usr/lib/ocf OCF_RESKEY_ip=192.168.22.41     \
/usr/lib/ocf/resource.d/heartbeat/IPaddr2 monitor
grep: warning: stray \ before white space
```
=> Low: IPaddr2: Remove stray backslash

configure.ac
Thanks @jfriesse for helping debug the issue.
=> configure: fix "C preprocessor "gcc -E" fails sanity check" error caused by autoconf 2.72

heartbeat/LVM-activate
When lvm.conf file has `volume_list` parameter configured and the cluster is managing the shared storage using `system_id_source`, then the activation of the LV fails to happen. However it is reported as a success.
The fixes will avoid starting of `LVM-activate` resource when the cluster is configured with both `system_id_source` and `volume_list`.
=> LVM-activate: Avoid false positive for VG activation

heartbeat/docker
After running into some failed monitor actions using the docker RA on Ubuntu 22.04, reverting some of the behavior of commit b7ae1bf resolves the issues.
Currently, the Docker resource agent works well if you ___do not___ manage the `docker.service` within Pacemaker. On Ubuntu 22.04 using systemd you can set the Docker service to enabled and start Docker before Pacemaker starts (key part).
However, attempting to manage the `docker.service` within Pacemaker causes some issues during the initial monitoring probe and it also completely breaks `stop-all-resources=true` expected behavior as the Docker resource agent's monitoring operations will always fail if the Docker service isn't running. Clean startup and shutdown are also affected and clearing failed actions is needed before resources …
=> docker: Fix RA behavior when Docker service isn't running

heartbeat/Delay
`stopdelay` and `mondelay` do not default to `startdelay`. Should have been done with fe8a807d.
Also remove comments that are redundant with the metadata, and remove descriptions of this as a "test" resource. This has valid uses in some production environments.
=> Doc: Delay: Drop old comments

heartbeat/portblock
Usually, using the "-n" flag with "iptables -L" will only enable numeric display for hosts and port numbers. Protocols are unaffected and are still shown as "tcp" or "udp", which we rely on in the portblock agent.
iptables version 1.8.9 ships with a regression that breaks this format, displaying the numeric value of the protocol instead. See this bug report for more: https://bugzilla.netfilter.org/show_bug.cgi?id=1729
The issue was fixed in the 1.8.10 release, but some distributions (notably, Debian Bookworm and Fedora 39) have shipped 1.8.9, effectively breaking the portblock agent.
Since both formats are now in use in the wild, we must work around this in the resource agent by allowing both the numeric and string representation of the protocol.
=> portblock: accept numeric protocol from iptables

heartbeat/openstack-info.in
This makes the `openstack_ports` variable match the format specified in the `openstack-info` metadata (see `longdesc`). It should be a comma-separated list of `"SUBNET_ID:PORT_ID"`. It should not be
```
SUBNET_A
SUBNET_B:PORT_1,SUBNET_C
SUBNET_D:PORT_2,
```
But rather
```
SUBNET_A:PORT1,SUBNET_B:PORT1,SUBNET_C:PORT2,SUBNET_D:PORT2
```
The newlines caused parsing issues in an experimental version of Pacemaker. Pacemaker is being fixed
(https://github.com/ClusterLabs/pacemaker/pull/3395), but this illustrated an issue in `openstack-info` that makes parsing rather precarious.
`openstack-virtual-ip` is capable of parsing either format without changes on a stable release of Pacemaker.
However, looking ahead, it should be updated to use `attrd_updater --output-as=xml` to query the attribute, as …
=> Fix: openstack-info: Ensure no newlines in openstack_ports

heartbeat/azure-lb
Using the  "TCP6-LISTENER" causes socat to listen in a dual-stack manner like nc.
=> azure-lb: support IPv6 with Azure load balancer

heartbeat/galera.in
It seems that with recent galera versions, when a galera node joins a cluster, there is a small time window where the node is connected to the primary component of the galera cluster, but it might still be preparing its IST. During this time, it can report itself as being 'not ready' and in 'non-primary' state.
Update the galera resource agent to allow the node to be in non-primary state, but only if running a "promote" operation. Any network partition during the promotion will be caught by the promote timeout.
In reworking the promotion code, we move the check for primary partition into the "galera_monitor" function. The check works as before for regular "monitor" or "probe" operations.
Related-Bug: rhbz#2255414
=> galera: allow joiner to report non-Primary during initial IST

heartbeat/portblock
Currently, the portblock resource agent enables the net.ipv4.tcp_tw_recycle option before sending a tickle ACK packet.
This option is supposed to recycle TCP sockets that are left in the TIME_WAIT state. On the host that initiates the closing of a TCP connection, a socket will be left in this state for about 60 seconds before it finally gets removed (and freed up for further use). This is by design, and it is generally considered useful. [0]
The tcp_tw_recycle option is supposed to shorten the time that a socket spends in the TIME_WAIT state, allowing its slot to be reused more quickly.
Unfortunately, there are no hints left by the previous author about the rationale behind setting this option. One can only guess that they somehow managed to exhaust the number of TCP sockets during …
=> portblock: remove write to tcp_tw_recycle

heartbeat/db2
fix OCF_SUCESS to OCF_SUCCESS  in db2_notify
db2_notify returns RC=1 due to misspelled variable name:
.
.
+ 10:08:48: db2_validate:221: return 0 
+ 10:08:49: main:899: db2_notify
+ 10:08:49: db2_notify:845: local node
+ 10:08:49: db2_notify:848: '[' pre = pre -a demote = start ']'
+ 10:08:49: db2_notify:849: return
+ 10:08:49: main:900: exit 1
=> db2: fix OCF_SUCESS name in db2_notify

heartbeat/azure-lb
My last change causes trouble if IP6 support is disabled (https://bugzilla.suse.com/show_bug.cgi?id=1223554)
Thats why I've introduced a new parameter "listen":
This parameter can have following walues:
```
default: Neither -4 nor -6 will be used. The default behavior of socat and nc will be used.
socat: Listen only on IPv4 addresses
nc: If net.ipv6.bindv6only = 0 => Listen on both IPv4 and IP6 addresses
If net.ipv6.bindv6only = 1 => Listen only on IPv4 addresses
ipv4only: Listen only on IPv4 addresses.
ipv6enable: Enable TCP6 support.
nc: Listen only on IPv6 adresses independent of net.ipv6.bindv6only
socat: If net.ipv6.bindv6only = 0 => Listen on both IPv4 and IP6 addresses.
If net.ipv6.bindv6only = 1 => Listen only on IPv6 adresses.
```
=> azure-lb: fails when using socat if IPv6 is disabled

heartbeat/ocf-shellfuncs.in
Fix for https://github.com/ClusterLabs/resource-agents/issues/1942.
=> ocf-shellfuncs: fix version regex in ocf_local_nodename()

heartbeat/Filesystem
Fixes #1944 by passing to the `fuser` command the argument to tell it to not fallback on other filesystems.
=> Filesystem: fix to avoid killing unrelated processes

heartbeat/conntrackd.in, heartbeat/galera.in, heartbeat/ocf-shellfuncs.in, heartbeat/rabbitmq-cluster.in
Fixes https://github.com/ClusterLabs/resource-agents/issues/1077 and https://github.com/ClusterLabs/resource-agents/issues/1955
=> conntrackd/galera/rabbitmq-cluster: avoid deprecated tool options / ocf-shellfuncs: dont use deprecated validate-with="none" in CIB 

heartbeat/IPaddr2
The `dev` keyword is sometimes required.
=> IPaddr2: Fix bringing up device

heartbeat/powervs-subnet.in
Add argument `route_table`.
In case multiple resources are configured in the cluster then each instance requires an unique `route_table` id.
=> powervs-subnet: Add optional argument route_table

heartbeat/powervs-subnet.in
Private networks in IBM PowerVS now can communicate with private endpoints without a proxy.
Allow a private endpoint also for IBM IAM access.
=> powervs-subnet: Enable access via private endpoint for IBM IAM

heartbeat/http-mon.sh
curl was recently moved to be de default http client, deprecating wget, the former preferred one. However, the curl options being used differ from the ones set for wget, changing the behavior of the agents using the monitor when using one or the other client.
=> apache/http-mon.sh: change curl opts to match wget

heartbeat/podman
- Added handling for containers in a stopping state by checking the state and force-removing if necessary.
- Improved log messages to provide clearer information when force removal is needed.
Related: https://issues.redhat.com/browse/RHEL-58008
=> podman: Improve handling of "stopping" container removal in remove_container()

heartbeat/docker-compose
Fixes https://github.com/ClusterLabs/resource-agents/issues/1974
=> docker-compose: use "docker compose" when not using older docker-compose command

heartbeat/nfsserver
E.g. nfs_no_notify=true nfsv4_only=true nfs_shared_infodir=/nfsmq/nfsinfo would cause a "Failed to unmount a bind mount" error
=> nfsserver: also stop rpc-statd for nfsv4_only to avoid stop failing in some cases

heartbeat/IPaddr2
* check that the label got applied
* return OCF_ERR_GENERIC to avoid false-positive when IP was manually added before starting the resource
* check ip_status after adding IP to fail without having to wait for the first monitor-action
=> IPaddr2: improve fail logic and check ip_status after adding IP

tools/storage_mon.c
Hi,
The following macro variables are defined in storage_mon.c, but it seems they’re unused. To simplify the code, how about removing them?
#define SMON_RESULT_OK "green"
#define SMON_RESULT_NG "red"
#define SMON_RESULT_COMMAND_ERROR "unknown command"
Regards,
=> storage_mon: remove unused macro variables

heartbeat/openstack-cinder-volume
monitor the vol till it´s attached to the host and avoid a race between openstack APIs receiving the request and completing the operation.
=> openstack-cinder-volume: wait for volume to be available

heartbeat/ocf-shellfuncs.in
ocf-shellfuncs: fixed bash systax error added at a25f08cf98d784894df9c52960eff5ccef059393
=> ocf-shellfuncs: fixed bash systax error added at a25f08

heartbeat/Filesystem
Hi!
On RHEL 10.0 beta with pcs 0.12.0+47-1ba3f.
I received the following warning messages when trying to create a Filesystem resource.
```
[root@rh10-b03 ~]# pcs -f filesystem_resources.xml resource create filesystem1 ocf:heartbeat:Filesystem \
device="/dev/vdb2" directory="/dbfp/pgdata" fstype="xfs" fast_stop="yes" force_unmount="safe" \
op start timeout=60s on-fail=restart \
monitor timeout=60s interval=10s on-fail=restart OCF_CHECK_LEVEL=0 \
stop timeout=60s on-fail=fence
Warning: Validating resource options using the resource agent itself is enabled by default and produces warnings. In a future version, this might be changed to errors. Specify --agent-validation to switch to the future behavior.
Warning: Validation result from agent:
Jan 23 11:19:48 INFO: Running validate-all for …
```
=> Filesystem: dont report warnings when creating a Filesystem resource

heartbeat/storage-mon.in
Dashes in function names produce "`storage-mon_usage': not a valid identifier" error when run with sh -x.
=> storage-mon: replace dashes with underscores in functions

heartbeat/storage-mon.in
As suggested by @HideoYamauchi in https://github.com/ClusterLabs/resource-agents/pull/2017.
=> storage-mon: log "storage_mon is already running" in start-action

heartbeat/portblock
With current versions of iptables there are suffixes (nf_tables) or (legacy) after the version string printed by iptables -V
The awk script does not remove those suffixes after the version string. ocf_version_cmp fails to compare this string. wait option will never be added if (nf_tables) or (legacy) is present after vX.Y.Z
In my lab ports listed in block/unblock primitives were never unblocked when a group was stated to be successfully started. DROP entries are accumulating with every restart.
With the corrected version detection this was fixed and worked as expected.
=> portblock: fix iptables version detection

heartbeat/azure-events-az.in
Same as c45ecb0 but with minor change to word order in log about nodes with resources still running.
=> azure-events-az: change variable name allNodesStopped to allResourcesNowStopped

heartbeat/azure-events-az.in
Rewrite of RA does not use this obsolete attribute any more.  Removing unnecessary setAttr action.
=> azure-events-az: remove unused attr_globalPullState variable

heartbeat/azure-events-az.in
Change putNodeOnline block to use value in previously defined attr_healthstate variable instead of "#health-azure" string literal, making it consistent with the earlier putNodeStandby block
=> azure-events-az: use attr_healthstate variable in crm_attribute call in putNodeOnline()

heartbeat/IPaddr2
Currently, it's not possible to use an interface's `altname` by specifying it in the `nic=` proprerty because the `monitor` routine fails to recognize that the IP is configured on the proper interface.
This patch fixes that by returning all the `altname` properties of an interface alongside its main name.
=> IPaddr2: add support for network interfaces altname in the monitor operation

doc/man/Makefile.am, heartbeat/Makefile.am, heartbeat/podman-etcd
Introduce a resource agent for Podman to manage etcd instances
This agent enables Pacemaker to control etcd containers, handling start, stop, monitor, and recovery operations.
=> podman-etcd: new resource agent

heartbeat/Filesystem
If we have such a filesystem structure mounted in our cluster
/dev/drbd50     /export/prq/upgrade_emspq       xfs
/dev/drbd55     /export/prq/upgrade_sharedmsb   xfs
/dev/drbd1      /export/devAGN/share    xfs
/dev/drbd5      /export/dev/archivesn1agn       xfs
When we want to stop the filesystem mounted on
/export/dev/archivesn1agn, we probably will get the wrong entry returned here and thus will try to stop the wrong target.
=> Filesystem: fix getting the wrong block device when doing grep

heartbeat/mdraid
This commit allows the value 'auto' or multiple devices separated by space are set in parameter md_dev.
When 'auto' is assigned, mdraid RA will try to get all md arrays from mdraid_conf then assemble them automatically.
If multiple devices are assigned e.g. '/dev/md2 /dev/md3', the RA will try to assemble them.
The single device syntax is same as the original.
To keep the code and logic simple, global varaiable RAIDDEVS is introduced to record md devices. All entry functions mdraid_(stop|start|mintor) are renamed to mdraid_(stop|start|mintor)_one which are called by new function forall(). In forall(), md_dev and devs are used by mdraid_(stop|start|mintor)_one during iterating RAIDDEVS.
The original mdraid_stop_one is renamed to mdraid_stop_array for naming consistency.
Related: …
=> mdraid: Add 'auto' and multiple devices support to parameter md_dev

heartbeat/azure-events-az.in
Update log line to improve semantic accuracy.  The word "clean" is used incorrectly to describe whether all resources have been "stopped" on the node.
=> azure-events-az: Update wording in log line

heartbeat/podman-etcd
This change ensures learner etcd listens on all interfaces for peer connections, resolving accessibility issues.
Fix: OCPBUGS-56447
=> podman-etcd: fix listen-peer-urls binding

heartbeat/mariadb.in, heartbeat/mysql-common.sh
Needed SSL-Support for a new mariadb-HA-Cluster. Adopted the needed Parameters from mysql RA to keep migration between those too as easy as possible.
=> mariadb: add SSL/TLS-Support

heartbeat/Filesystem
This check cause Warnings and might cause errors in future pcs versions
when running "pcs resource create".
Example:
```
Warning: Validating resource options using the resource agent itself is enabled by default and produces warnings. In a future version, this might be changed to errors. Specify --agent-validation to switch to the future behavior.
Warning: Validation result from agent:
Jun 19 06:13:45 INFO: It seems we do not have ext3 support
```
=> Filesystem: remove validate-all fstype check, as there isnt a reliable and portable way to check

heartbeat/podman-etcd
This change introduces a new `oom` parameter to the `podman-etcd` OCF agent. This allows tuning the Out-Of-Memory (OOM) score adjustment for the etcd container.
The `oom` parameter accepts integer values from -1000 to 1000, defaulting to -997 (system-node-critical equivalent).
see https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#node-out-of-memory-behavior
Key changes:
- Added `OCF_RESKEY_oom` parameter to agent definition (`content type="integer"`).
- Integrated `--oom-score-adj` option into `podman_start()`.
- Implemented input validation for `oom` in `podman_validate()`, ensuring values are within the [-1000:1000] range.
=> OCPBUGS-58324: podman-etcd Add OOM score adjustment for etcd containers

heartbeat/podman-etcd
When trying to determine the node ip address we need to make sure we account for ipv6 and dualstack deployments, and accordingly wrap ipv6 in brackets so it correctly resolves. We also need to prefer ipv6 over ipv4 in dualstack deployments, so when querying for the ip address, we favor ipv6.
=> OCPBUGS-60977: podman-etcd: wrap ipv6 address in brackets for attribute_node_ip

heartbeat/podman-etcd
Implement cluster-wide validation of force_new_cluster attribute to resolve race conditions during automated cluster recovery. The enhancement ensures agents check for the cluster-wide attribute before falling back to local etcd revision comparison.
Key changes:
- Enhanced get_force_new_cluster() to query all cluster nodes
- Ensure force_new_cluster is not set in both nodes to prevent conflicting recovery attempts
- Updated startup logic to prioritize cluster-wide attribute checking
fixes OCPBUGS-61117
=> OCPBUGS-61117: podman-etcd: Add cluster-wide force_new_cluster attribute checking
